# -*- coding: utf-8 -*-
"""neu_efficient_multiclass

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iDtIqB-DBtdb1wcgQDe7C6jSr8cy8-Ox

Transfer-learning EfficientNetV2B0 multiclass pipeline for microstructure
image classification, with stratified evaluation, rich error analysis, and
custom multiclass Score-CAM visualizations.

This cell:
1. Sets seeds, mounts Google Drive, loads a folder-structured multiclass
   microstructure dataset (one subdirectory per class), builds a stable
   class-to-label mapping, resizes/normalizes images, and creates a stratified
   train/validation/test split while saving the test data and mappings for
   reuse.
2. Applies strong data augmentation and class weighting to address limited and
   imbalanced data, converts labels to one-hot encodings, and defines an
   EfficientNetV2B0-based model (ImageNet-initialized backbone with selected
   deeper layers unfrozen) followed by L2-regularized dense blocks and dropout
   with a softmax output for multiclass prediction.
3. Phase 1: Performs stratified K-fold cross-validation, logging accuracy,
   macro/weighted averages, and per-class F1 scores, and saving training
   curves and confusion matrices for each fold to disk.
4. Phase 2: Trains a final EfficientNetV2B0 model on the full augmented
   training set with checkpointing, learning-rate scheduling, and CSV logging,
   evaluates on the held-out test set, generates confusion matrices and a
   per-class precision/recall/F1 bar chart, and saves aggregated performance
   metrics and misclassification counts to CSV.
5. Visualizes misclassified test images with predicted class and confidence,
   writes a detailed misclassification table (including full class probability
   vectors) and a summarized misclassification pattern table, and implements a
   custom multiclass Score-CAM routine that produces triplet panels (original,
   heatmap, overlay) for representative correct and misclassified samples and
   an additional comparison where CAMs are generated for all classes on a
   single image, providing qualitative insight into class-specific attention.
"""

import cv2
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (classification_report, confusion_matrix, ConfusionMatrixDisplay,
                             accuracy_score, precision_score, recall_score, f1_score)
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Input, GlobalAveragePooling2D,
                                     Dense, BatchNormalization, Dropout)
from tensorflow.keras.applications import EfficientNetV2B0
from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, CSVLogger
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from sklearn.utils import class_weight
from google.colab import drive
import pickle

# ============================================================================
# SETUP & REPRODUCIBILITY
# ============================================================================
sns.set_style("darkgrid")
sns.set_palette("colorblind")

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)
os.environ["TF_DETERMINISTIC_OPS"] = "1"

# Mount Drive
drive.mount('/content/drive')

# Paths
image_directory = '/content/drive/My Drive/frost/frost_non_frost/microstructures'
save_dir = '/content/drive/My Drive/frost/models_saved/multiclass'
os.makedirs(save_dir, exist_ok=True)

# Constants
SIZE = 512  # MobileNetV2 standard input size
BATCH_SIZE = 25
EPOCHS = 18
AUGMENTATION_FACTOR = 11
N_FOLDS = 5

# ============================================================================
# DATA LOADING - MULTICLASS
# ============================================================================
print("Loading images from subdirectories...")
dataset = []
labels = []
class_names = []

# Get all subdirectories (each represents a class)
subdirs = [d for d in os.listdir(image_directory)
           if os.path.isdir(os.path.join(image_directory, d))]
subdirs.sort()  # Ensure consistent ordering

print(f"Found {len(subdirs)} classes: {subdirs}")

# Create class name to label mapping
class_to_label = {name: idx for idx, name in enumerate(subdirs)}
label_to_class = {idx: name for name, idx in class_to_label.items()}

print(f"\nClass mapping:")
for name, label in class_to_label.items():
    print(f"  {label}: {name}")

# Load images from each class subdirectory
for class_name in subdirs:
    class_path = os.path.join(image_directory, class_name)
    label = class_to_label[class_name]

    image_count = 0
    for image_name in os.listdir(class_path):
        if image_name.lower().endswith(('tif', 'png', 'jpg', 'jpeg', 'bmp')):
            image_path = os.path.join(class_path, image_name)
            image = cv2.imread(image_path)
            if image is None:
                continue
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            image = cv2.resize(image, (SIZE, SIZE))
            dataset.append(image)
            labels.append(label)
            image_count += 1

    print(f"Loaded {image_count} images from class '{class_name}' (label {label})")

# Normalize to [0, 1]
dataset = np.array(dataset, dtype=np.float32) / 255.0
labels = np.array(labels)
num_classes = len(subdirs)

print(f"\nTotal samples: {len(dataset)}")
print(f"Number of classes: {num_classes}")
unique, counts = np.unique(labels, return_counts=True)
for u, c in zip(unique, counts):
    print(f"  Class {u} ({label_to_class[u]}): {c} samples")

# Save class mapping
with open(os.path.join(save_dir, 'class_mapping.pkl'), 'wb') as f:
    pickle.dump({'class_to_label': class_to_label, 'label_to_class': label_to_class}, f)

# ============================================================================
# DATA SPLITTING (CONSISTENT ACROSS ALL MODELS)
# ============================================================================
print("\nCreating train/val/test splits...")
X_train, X_temp, y_train, y_temp = train_test_split(
    dataset, labels, test_size=0.3, random_state=SEED, stratify=labels
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=SEED, stratify=y_temp
)

print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

# Save splits for consistency
np.save(os.path.join(save_dir, 'X_test.npy'), X_test)
np.save(os.path.join(save_dir, 'y_test.npy'), y_test)

# ============================================================================
# DATA AUGMENTATION
# ============================================================================
print("\nAugmenting training data...")
train_datagen = ImageDataGenerator(
    rotation_range=30,
    horizontal_flip=True,
    vertical_flip=True,
    fill_mode='reflect'
)

def augment_data(X, y, factor=AUGMENTATION_FACTOR):
    aug_images = []
    aug_labels = []
    for i in range(len(X)):
        image = np.expand_dims(X[i], axis=0)
        label = y[i]
        aug_iter = train_datagen.flow(image, batch_size=1)
        for _ in range(factor):
            aug_images.append(next(aug_iter)[0])
            aug_labels.append(label)

    X_aug = np.concatenate([X, np.array(aug_images)], axis=0).astype(np.float32)
    y_aug = np.concatenate([y, np.array(aug_labels)], axis=0).astype(int)
    return X_aug, y_aug

X_train_aug, y_train_aug = augment_data(X_train, y_train)
print(f"Augmented training data: {X_train_aug.shape}")

# Class weights for multiclass
class_weights = class_weight.compute_class_weight(
    'balanced',
    classes=np.unique(y_train_aug),
    y=y_train_aug
)
class_weights = dict(enumerate(class_weights))
print(f"Class weights: {class_weights}")

# Convert labels to categorical for training
y_train_aug_cat = to_categorical(y_train_aug, num_classes)
y_val_cat = to_categorical(y_val, num_classes)
y_test_cat = to_categorical(y_test, num_classes)

# ============================================================================
# MOBILENETV2 MODEL DEFINITION - MULTICLASS
# ============================================================================
def create_efficientnet_model(input_shape=(SIZE, SIZE, 3), num_classes=num_classes):
    # Base EfficientNetV2B0
    base_model = EfficientNetV2B0(include_top=False, weights='imagenet', input_shape=input_shape)

    # Freeze all but the last 15 layers
    for layer in base_model.layers[-15:]:
        layer.trainable = True

    # Functional graph
    inputs = Input(shape=input_shape)
    x = base_model(inputs, training=False)
    x = GlobalAveragePooling2D()(x)

    x = Dense(128, activation='relu', kernel_regularizer=l2(0.0001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.5)(x)

    x = Dense(64, activation='relu', kernel_regularizer=l2(0.0001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.4)(x)

    x = Dense(32, activation='relu', kernel_regularizer=l2(0.0001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.3)(x)

    # Output layer - softmax for multiclass
    outputs = Dense(num_classes, activation='softmax', kernel_regularizer=l2(0.0002))(x)

    model = Model(inputs, outputs)

    model.compile(
        optimizer=Adam(learning_rate=4e-5),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# ============================================================================
# PHASE 1: CROSS-VALIDATION
# ============================================================================
print("\n" + "="*60)
print("PHASE 1: CROSS-VALIDATION")
print("="*60)

skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
cv_results = []

for fold_idx, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train), start=1):
    print(f"\n--- Fold {fold_idx}/{N_FOLDS} ---")

    # Split fold data
    X_fold_train = X_train[train_idx]
    y_fold_train = y_train[train_idx]
    X_fold_val = X_train[val_idx]
    y_fold_val = y_train[val_idx]

    # Augment fold training data
    X_fold_aug, y_fold_aug = augment_data(X_fold_train, y_fold_train)
    y_fold_aug_cat = to_categorical(y_fold_aug, num_classes)
    y_fold_val_cat = to_categorical(y_fold_val, num_classes)

    # Fold class weights
    fold_cw = class_weight.compute_class_weight(
        'balanced', classes=np.unique(y_fold_aug), y=y_fold_aug
    )
    fold_cw = dict(enumerate(fold_cw))

    # Create and train model
    model = create_efficientnet_model()
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-7, verbose=0)

    history = model.fit(
        X_fold_aug, y_fold_aug_cat,
        validation_data=(X_fold_val, y_fold_val_cat),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        shuffle=True,
        class_weight=fold_cw,
        callbacks=[reduce_lr],
        verbose=1
    )

    # Get predictions
    y_pred_probs = model.predict(X_fold_val, batch_size=25, verbose=0)
    y_pred = np.argmax(y_pred_probs, axis=1)

    # Calculate metrics
    report = classification_report(y_fold_val, y_pred, output_dict=True, zero_division=0)

    # Print classification report
    print(f"\nClassification Report - Fold {fold_idx}:")
    print(classification_report(y_fold_val, y_pred,
                                target_names=[label_to_class[i] for i in range(num_classes)],
                                zero_division=0))

    # PLOT 1: Training curves
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy', linewidth=2)
    plt.plot(history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
    plt.title(f'Accuracy - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss', linewidth=2)
    plt.plot(history.history['val_loss'], label='Val Loss', linewidth=2)
    plt.title(f'Loss - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    plt.suptitle(f'Training Curves - Fold {fold_idx}/{N_FOLDS}', fontsize=16)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'efficientnet_fold_{fold_idx}_curves.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # PLOT 2: Confusion matrix
    plt.figure(figsize=(10, 8))
    cm = confusion_matrix(y_fold_val, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                                   display_labels=[label_to_class[i] for i in range(num_classes)])
    disp.plot(cmap='Blues', xticks_rotation=45)
    plt.title(f'Confusion Matrix - Fold {fold_idx}/{N_FOLDS}', fontsize=14, fontweight='bold')
    plt.grid(False)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'efficientnet_fold_{fold_idx}_confusion.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # Save fold results
    fold_result = {
        'Fold': fold_idx,
        'Accuracy': report['accuracy'],
        'Macro_Avg_Precision': report['macro avg']['precision'],
        'Macro_Avg_Recall': report['macro avg']['recall'],
        'Macro_Avg_F1': report['macro avg']['f1-score'],
        'Weighted_Avg_Precision': report['weighted avg']['precision'],
        'Weighted_Avg_Recall': report['weighted avg']['recall'],
        'Weighted_Avg_F1': report['weighted avg']['f1-score'],
        'Loss': history.history['val_loss'][-1]
    }

    # Add per-class F1 scores
    for i in range(num_classes):
        class_label = str(i)
        if class_label in report:
            fold_result[f'F1_{label_to_class[i]}'] = report[class_label]['f1-score']

    cv_results.append(fold_result)

    print(f"Accuracy: {fold_result['Accuracy']:.4f}, Macro F1: {fold_result['Macro_Avg_F1']:.4f}")

    # Clear memory
    del model, history, y_pred_probs, y_pred
    tf.keras.backend.clear_session()

# Save CV results
cv_df = pd.DataFrame(cv_results)
cv_df.to_csv(os.path.join(save_dir, 'efficientnet_cv_results.csv'), index=False)

print("\n" + "="*60)
print("CROSS-VALIDATION SUMMARY")
print("="*60)
print(cv_df.describe())

# ============================================================================
# PHASE 2: FINAL MODEL TRAINING
# ============================================================================
print("\n" + "="*60)
print("PHASE 2: FINAL MODEL TRAINING")
print("="*60)

# Train final model on full augmented training data
final_model = create_efficientnet_model()

checkpoint_cb = ModelCheckpoint(
    filepath=os.path.join(save_dir, 'efficientnet_best_model_multiclass.h5'),
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-7, verbose=1)
csv_logger = CSVLogger(os.path.join(save_dir, 'efficientnet_training_log_multiclass.csv'))

final_history = final_model.fit(
    X_train_aug, y_train_aug_cat,
    validation_data=(X_val, y_val_cat),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    class_weight=class_weights,
    callbacks=[checkpoint_cb, reduce_lr, csv_logger],
    verbose=1
)

# ============================================================================
# FINAL TEST SET EVALUATION
# ============================================================================
print("\n" + "="*60)
print("TEST SET EVALUATION")
print("="*60)

# Predictions on test set
y_test_pred_probs = final_model.predict(X_test, batch_size=25, verbose=0)
y_test_pred = np.argmax(y_test_pred_probs, axis=1)

# Classification report
print("\nClassification Report - Test Set:")
print(classification_report(y_test, y_test_pred,
                            target_names=[label_to_class[i] for i in range(num_classes)]))

# PLOT 1: Training curves for final model
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(final_history.history['accuracy'], label='Train Accuracy', linewidth=2)
plt.plot(final_history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
plt.title('Model Accuracy - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(final_history.history['loss'], label='Train Loss', linewidth=2)
plt.plot(final_history.history['val_loss'], label='Val Loss', linewidth=2)
plt.title('Model Loss - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.suptitle('Final Model Training Curves', fontsize=16)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'efficientnet_final_training_curves.png'), dpi=300, bbox_inches='tight')
plt.show()

# PLOT 2: Confusion Matrix for test set
plt.figure(figsize=(10, 8))
cm = confusion_matrix(y_test, y_test_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                               display_labels=[label_to_class[i] for i in range(num_classes)])
disp.plot(cmap='Blues', xticks_rotation=45)
plt.title("Confusion Matrix - Test Set", fontsize=14, fontweight='bold')
plt.grid(False)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'efficientnet_test_confusion_matrix.png'), dpi=300, bbox_inches='tight')
plt.show()

# PLOT 3: Per-class performance bar chart
test_report = classification_report(y_test, y_test_pred, output_dict=True, zero_division=0)
class_metrics = []
for i in range(num_classes):
    if str(i) in test_report:
        class_metrics.append({
            'Class': label_to_class[i],
            'Precision': test_report[str(i)]['precision'],
            'Recall': test_report[str(i)]['recall'],
            'F1-Score': test_report[str(i)]['f1-score']
        })

metrics_df = pd.DataFrame(class_metrics)
fig, ax = plt.subplots(figsize=(12, 6))
x = np.arange(len(metrics_df))
width = 0.25

ax.bar(x - width, metrics_df['Precision'], width, label='Precision')
ax.bar(x, metrics_df['Recall'], width, label='Recall')
ax.bar(x + width, metrics_df['F1-Score'], width, label='F1-Score')

ax.set_xlabel('Class', fontsize=12)
ax.set_ylabel('Score', fontsize=12)
ax.set_title('Per-Class Performance Metrics - Test Set', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(metrics_df['Class'], rotation=45, ha='right')
ax.legend()
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'efficientnet_per_class_metrics_multiclass.png'), dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# SAVE FINAL RESULTS
# ============================================================================
# Calculate misclassifications
misclassified_idx = np.where(y_test_pred != y_test)[0]

final_results = {
    'Model': 'MobileNetV2_Multiclass',
    'Num_Classes': num_classes,
    'Test_Accuracy': accuracy_score(y_test, y_test_pred),
    'Test_Macro_Precision': precision_score(y_test, y_test_pred, average='macro'),
    'Test_Macro_Recall': recall_score(y_test, y_test_pred, average='macro'),
    'Test_Macro_F1': f1_score(y_test, y_test_pred, average='macro'),
    'Test_Weighted_Precision': precision_score(y_test, y_test_pred, average='weighted'),
    'Test_Weighted_Recall': recall_score(y_test, y_test_pred, average='weighted'),
    'Test_Weighted_F1': f1_score(y_test, y_test_pred, average='weighted'),
    'CV_Accuracy_Mean': cv_df['Accuracy'].mean(),
    'CV_Accuracy_Std': cv_df['Accuracy'].std(),
    'Misclassifications': len(misclassified_idx)
}

pd.DataFrame([final_results]).to_csv(
    os.path.join(save_dir, 'efficientnet_final_results_multiclass.csv'), index=False
)

print("\n" + "="*60)
print("FINAL RESULTS")
print("="*60)
for key, value in final_results.items():
    print(f"{key}: {value}")

print("\n✅ All results saved to:", save_dir)



# ============================================================================
# MISCLASSIFIED IMAGES VISUALIZATION
# ============================================================================
print("\n" + "="*60)
print("VISUALIZING MISCLASSIFIED IMAGES")
print("="*60)

# Find misclassified samples
misclassified_idx = np.where(y_test_pred != y_test)[0]
print(f"Number of misclassified images: {len(misclassified_idx)}")

if len(misclassified_idx) > 0:
    # Visualize up to 20 misclassified images
    num_to_show = min(20, len(misclassified_idx))

    # Create figure with subplots
    fig, axes = plt.subplots(4, 5, figsize=(20, 16))
    axes = axes.flatten()

    for i, idx in enumerate(misclassified_idx[:num_to_show]):
        img = X_test[idx]
        true_label = label_to_class[y_test[idx]]
        pred_label = label_to_class[y_test_pred[idx]]
        confidence = y_test_pred_probs[idx, y_test_pred[idx]]  # Confidence for predicted class

        axes[i].imshow(img)
        axes[i].set_title(f'True: {true_label}\nPred: {pred_label}\nConf: {confidence:.2%}',
                         fontsize=10, fontweight='bold')
        axes[i].axis('off')

    # Hide unused subplots
    for i in range(num_to_show, len(axes)):
        axes[i].axis('off')

    plt.suptitle('Misclassified Images on Test Set', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'efficientnet_misclassified_images_multiclass.png'), dpi=300, bbox_inches='tight')
    plt.show()

    # Save detailed misclassification info
    misclass_info = []
    for i, idx in enumerate(misclassified_idx):
        true_class_idx = y_test[idx]
        pred_class_idx = y_test_pred[idx]

        info_dict = {
            'Sample_Index': int(idx),
            'True_Label': label_to_class[true_class_idx],
            'True_Label_ID': int(true_class_idx),
            'Predicted_Label': label_to_class[pred_class_idx],
            'Predicted_Label_ID': int(pred_class_idx),
            'Confidence': float(y_test_pred_probs[idx, pred_class_idx]),
            'True_Class_Probability': float(y_test_pred_probs[idx, true_class_idx])
        }

        # Add probabilities for all classes
        for class_idx in range(num_classes):
            info_dict[f'Prob_{label_to_class[class_idx]}'] = float(y_test_pred_probs[idx, class_idx])

        misclass_info.append(info_dict)

    misclass_df = pd.DataFrame(misclass_info)
    misclass_df.to_csv(os.path.join(save_dir, 'efficientnet_misclassifications.csv'), index=False)
    print(f"Saved misclassification details to: {os.path.join(save_dir, 'efficientnet_misclassifications.csv')}")

    # Print summary of misclassification patterns
    print("\nMisclassification Summary:")
    print("-" * 40)
    misclass_summary = misclass_df.groupby(['True_Label', 'Predicted_Label']).size().reset_index(name='Count')
    misclass_summary = misclass_summary.sort_values('Count', ascending=False)
    print(misclass_summary.to_string(index=False))

print("\n✅ All results saved to:", save_dir)


# ============================================================================
# SCORE-CAM IMPLEMENTATION FOR MULTICLASS CLASSIFICATION
# ============================================================================
print("\n" + "="*60)
print("SCORE-CAM IMPLEMENTATION & VISUALIZATION (MULTICLASS)")
print("="*60)

# Define ScoreCAM class for multiclass
class ScoreCAMMulticlass:
    def __init__(self, model, layer_name=None):
        self.model = model
        self.layer_name = layer_name

        # Find the last convolutional layer if layer_name is not specified
        if self.layer_name is None:
            # For EfficientNetV2 models, look for the base model layers
            efficientnet_layer = None
            for layer in self.model.layers:
                if 'efficientnet' in layer.name.lower():
                    efficientnet_layer = layer
                    break

            if efficientnet_layer is not None:
                # Look for good layers in EfficientNetV2B0
                # EfficientNetV2 uses 'block' naming convention
                for sublayer in reversed(efficientnet_layer.layers):
                    if ('block6' in sublayer.name and 'add' in sublayer.name) or \
                       ('block6' in sublayer.name and 'project' in sublayer.name) or \
                       ('block5' in sublayer.name and 'add' in sublayer.name):
                        self.layer_name = sublayer.name
                        self.base_model = efficientnet_layer
                        break

                # If not found, try any conv layer in the last few blocks
                if self.layer_name is None:
                    for sublayer in reversed(efficientnet_layer.layers):
                        if 'conv' in sublayer.name.lower() or 'project' in sublayer.name.lower():
                            if hasattr(sublayer, 'output_shape') and len(sublayer.output_shape) == 4:
                                self.layer_name = sublayer.name
                                self.base_model = efficientnet_layer
                                break

        if self.layer_name is None:
            # Manual fallback - use a known good layer name for EfficientNetV2B0
            self.layer_name = 'block5e_add'
            efficientnet_layer = None
            for layer in self.model.layers:
                if 'efficientnet' in layer.name.lower():
                    efficientnet_layer = layer
                    break
            self.base_model = efficientnet_layer

        # Create a model that outputs feature maps from the specified layer
        try:
            if hasattr(self, 'base_model') and self.base_model is not None:
                target_layer = self.base_model.get_layer(self.layer_name)
                self.feature_model = tf.keras.models.Model(
                    inputs=self.base_model.input,
                    outputs=target_layer.output
                )
            else:
                self.feature_model = tf.keras.models.Model(
                    inputs=self.model.input,
                    outputs=self.model.get_layer(self.layer_name).output
                )
        except Exception as e:
            # Try alternative layers for EfficientNetV2B0
            alternative_layers = ['block6a_expand_conv', 'block5e_add', 'block6a_project_conv', 'top_conv']
            for alt_layer in alternative_layers:
                try:
                    if hasattr(self, 'base_model') and self.base_model is not None:
                        target_layer = self.base_model.get_layer(alt_layer)
                        self.feature_model = tf.keras.models.Model(
                            inputs=self.base_model.input,
                            outputs=target_layer.output
                        )
                        self.layer_name = alt_layer
                        break
                except:
                    continue

        print(f"Score-CAM using layer: {self.layer_name}")

    def generate_cam(self, input_image, class_idx=None):
        """
        Generate Score-CAM for a specific class.

        Args:
            input_image: Input image (H, W, 3) or (1, H, W, 3)
            class_idx: Target class index. If None, uses predicted class.

        Returns:
            cam: Class activation map
            original_scores: Full prediction scores for all classes
            target_class_idx: The class index used for CAM generation
        """
        if len(input_image.shape) == 3:
            input_image = np.expand_dims(input_image, axis=0)

        # Get feature maps
        feature_maps = self.feature_model.predict(input_image, verbose=0)

        # Get original prediction scores for all classes
        original_scores = self.model.predict(input_image, verbose=0)[0]

        # Determine target class
        if class_idx is None:
            # Use predicted class (highest probability)
            target_class_idx = np.argmax(original_scores)
        else:
            target_class_idx = class_idx

        print(f"Generating CAM for class {target_class_idx} (confidence: {original_scores[target_class_idx]:.4f})")

        # Initialize weights for each feature map
        weights = []

        # Sample every nth feature map to speed up computation
        n_features = feature_maps.shape[-1]
        step = max(1, n_features // 50)  # Use at most 50 feature maps

        for i in range(0, n_features, step):
            # Extract single feature map
            feature_map = feature_maps[0, :, :, i]

            # Resize feature map to input image size
            resized_feature_map = cv2.resize(feature_map, (input_image.shape[2], input_image.shape[1]))

            # Normalize feature map to [0, 1]
            if resized_feature_map.max() > resized_feature_map.min():
                normalized_feature_map = (resized_feature_map - resized_feature_map.min()) / \
                                       (resized_feature_map.max() - resized_feature_map.min())
            else:
                normalized_feature_map = np.zeros_like(resized_feature_map)

            # Create masked image
            masked_image = input_image[0] * np.expand_dims(normalized_feature_map, axis=-1)
            masked_image = np.expand_dims(masked_image, axis=0)

            # Get prediction score for masked image for TARGET CLASS
            try:
                masked_scores = self.model.predict(masked_image, verbose=0)[0]
                masked_score = masked_scores[target_class_idx]  # Extract score for target class
                weights.append(masked_score)
            except:
                weights.append(0.0)

        weights = np.array(weights)

        # Generate weighted combination of feature maps
        cam = np.zeros((feature_maps.shape[1], feature_maps.shape[2]), dtype=np.float32)

        for idx, i in enumerate(range(0, n_features, step)):
            cam += weights[idx] * feature_maps[0, :, :, i]

        # Apply ReLU and normalize CAM
        cam = np.maximum(cam, 0)
        if cam.max() > cam.min():
            cam = (cam - cam.min()) / (cam.max() - cam.min())

        return cam, original_scores, target_class_idx

def overlay_heatmap_scorecam(img, heatmap, alpha=0.4, colormap=cv2.COLORMAP_JET):
    """
    Overlay heatmap on image.

    Args:
        img: Original image (H, W, 3) in range [0, 1] or any range
        heatmap: Heatmap (H, W) in range [0, 1]
        alpha: Transparency of heatmap
        colormap: OpenCV colormap

    Returns:
        Overlayed image
    """
    # Convert heatmap to RGB
    heatmap_uint8 = np.uint8(255 * heatmap)
    heatmap_colored = cv2.applyColorMap(heatmap_uint8, colormap)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)
    heatmap_colored = heatmap_colored.astype(np.float32) / 255.0

    # Prepare image for display
    img_display = img.copy()

    # Normalize image if needed (handle different ranges)
    if img_display.max() > 1.0 or img_display.min() < 0:
        img_display = (img_display - img_display.min()) / (img_display.max() - img_display.min())

    img_display = np.clip(img_display, 0, 1)

    # Overlay
    overlayed = heatmap_colored * alpha + img_display * (1 - alpha)
    overlayed = np.clip(overlayed, 0, 1)

    return overlayed

# Initialize Score-CAM with the final model
try:
    score_cam = ScoreCAMMulticlass(final_model)
    print("Score-CAM initialized successfully!")
except Exception as e:
    print(f"Error initializing Score-CAM: {e}")
    score_cam = None

# ============================================================================
# VISUALIZATION SETUP
# ============================================================================

# Define your class names here (UPDATE THIS!)
class_names = ['Class 0', 'Class 1', 'Class 2', 'Class 3', 'Class 4']
# Example: class_names = ['Healthy', 'Frost', 'Drought', 'Disease', 'Pest']

# Get predictions for all test samples
y_test_pred = np.argmax(final_model.predict(X_test, verbose=0), axis=1)

# Select samples for Score-CAM visualization
samples_to_visualize = []

# Get correctly classified samples from each class (2 per class)
for class_idx in range(len(class_names)):
    correct_class = np.where((y_test == class_idx) & (y_test_pred == class_idx))[0]
    if len(correct_class) > 0:
        samples_to_visualize.extend(correct_class[:2])

# Add misclassified samples
misclassified_idx = np.where(y_test != y_test_pred)[0]
if len(misclassified_idx) > 0:
    samples_to_visualize.extend(misclassified_idx[:4])

print(f"\nSelected {len(samples_to_visualize)} samples for visualization")

# ============================================================================
# GENERATE SCORE-CAM VISUALIZATIONS
# ============================================================================

if score_cam is not None and len(samples_to_visualize) > 0:
    print(f"\nGenerating Score-CAM for {len(samples_to_visualize)} samples...")

    num_samples = min(len(samples_to_visualize), 12)  # Limit to 12 for readability
    samples_to_visualize = samples_to_visualize[:num_samples]

    fig, axes = plt.subplots(num_samples, 3, figsize=(15, 5*num_samples))
    if num_samples == 1:
        axes = axes.reshape(1, -1)

    for i, idx in enumerate(samples_to_visualize):
        img = X_test[idx]
        true_label = class_names[y_test[idx]]
        pred_label = class_names[y_test_pred[idx]]

        print(f"\nProcessing sample {i+1}/{num_samples} (Index: {idx})")

        try:
            # Generate Score-CAM for the PREDICTED class
            cam, all_scores, target_class = score_cam.generate_cam(img, class_idx=None)

            confidence = all_scores[target_class]

            # Resize CAM to match image size
            cam_resized = cv2.resize(cam, (img.shape[1], img.shape[0]))

            # Create overlay
            overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)

        except Exception as e:
            print(f"Error generating Score-CAM for sample {idx}: {str(e)}")
            cam_resized = np.zeros((img.shape[0], img.shape[1]))
            overlay = img
            confidence = 0.0
            all_scores = np.zeros(len(class_names))

        # Prepare display image
        img_display = img.copy()
        if img_display.max() > 1.0 or img_display.min() < 0:
            img_display = (img_display - img_display.min()) / (img_display.max() - img_display.min())
        img_display = np.clip(img_display, 0, 1)

        # Plot original image
        axes[i, 0].imshow(img_display)

        # Create title with top predictions
        top_3_idx = np.argsort(all_scores)[-3:][::-1]
        title_str = f'Original\nTrue: {true_label}\nPred: {pred_label}\n'
        title_str += '\n'.join([f'{class_names[idx]}: {all_scores[idx]:.2%}' for idx in top_3_idx])

        axes[i, 0].set_title(title_str, fontsize=9, fontweight='bold')
        axes[i, 0].axis('off')

        # Plot heatmap
        im = axes[i, 1].imshow(cam_resized, cmap='jet')
        axes[i, 1].set_title(f'Score-CAM Heatmap\n(Class: {pred_label})',
                            fontsize=9, fontweight='bold')
        axes[i, 1].axis('off')
        plt.colorbar(im, ax=axes[i, 1], fraction=0.046, pad=0.04)

        # Plot overlay
        axes[i, 2].imshow(overlay)
        axes[i, 2].set_title('Overlay', fontsize=9, fontweight='bold')
        axes[i, 2].axis('off')

    plt.suptitle('Score-CAM Visualizations (Multiclass)', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'efficientnet_scorecam_multiclass.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    print("\nScore-CAM visualization complete!")
    print(f"Results saved to: {os.path.join(save_dir, 'efficientnet_scorecam_multiclass.png')}")

    # ========================================================================
    # OPTIONAL: Generate CAM for ALL classes on a single image
    # ========================================================================
    print("\n" + "="*60)
    print("GENERATING MULTI-CLASS CAM COMPARISON")
    print("="*60)

    # Pick one interesting sample (correctly classified with high confidence)
    confident_correct = []
    for idx in range(len(y_test)):
        if y_test[idx] == y_test_pred[idx]:
            pred_scores = final_model.predict(np.expand_dims(X_test[idx], 0), verbose=0)[0]
            if pred_scores[y_test[idx]] > 0.8:
                confident_correct.append((idx, pred_scores[y_test[idx]]))

    if len(confident_correct) > 0:
        # Sort by confidence and pick the most confident
        confident_correct.sort(key=lambda x: x[1], reverse=True)
        sample_idx = confident_correct[0][0]

        img = X_test[sample_idx]
        true_class = y_test[sample_idx]

        print(f"Analyzing sample {sample_idx} (True class: {class_names[true_class]})")

        # Generate CAM for each class
        n_classes = len(class_names)
        fig, axes = plt.subplots(2, (n_classes + 1) // 2, figsize=(4 * ((n_classes + 1) // 2), 8))
        axes = axes.flatten()

        for class_idx in range(n_classes):
            try:
                cam, all_scores, _ = score_cam.generate_cam(img, class_idx=class_idx)
                cam_resized = cv2.resize(cam, (img.shape[1], img.shape[0]))
                overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)

                axes[class_idx].imshow(overlay)
                marker = "✓" if class_idx == true_class else ""
                axes[class_idx].set_title(f'{class_names[class_idx]} {marker}\nScore: {all_scores[class_idx]:.2%}',
                                         fontsize=10, fontweight='bold')
                axes[class_idx].axis('off')
            except Exception as e:
                print(f"Error for class {class_idx}: {e}")
                axes[class_idx].axis('off')

        # Hide extra subplots
        for i in range(n_classes, len(axes)):
            axes[i].axis('off')

        plt.suptitle(f'Score-CAM for All Classes\nTrue Label: {class_names[true_class]}',
                    fontsize=14, fontweight='bold')
        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, 'scorecam_all_classes_comparison.png'),
                   dpi=300, bbox_inches='tight')
        plt.show()

        print("Multi-class comparison complete!")

else:
    print("Score-CAM visualization skipped (no samples or initialization failed)")

print("\n" + "="*60)
print("ALL SCORE-CAM PROCESSING COMPLETE!")
print("="*60)
