# -*- coding: utf-8 -*-
"""neu_resnet_binary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OfI0i2Ub4YgAlFT8z2dFOBmbJAbPa2S7

Transfer-learning ResNet50 pipeline for binary frost vs non-frost classification,
with cross-validation, detailed misclassification logging, and custom Score-CAM
explanations.

This cell:
1. Sets seeds, mounts Google Drive, loads and normalizes the frost/non-frost
   image dataset, constructs a stratified train/validation/test split (saving
   the test split for reuse), then applies data augmentation and computes class
   weights to counteract class imbalance.
2. Defines a ResNet50-based model (ImageNet backbone with its final blocks
   unfrozen) followed by L2-regularized dense layers and dropout with a sigmoid
   output for binary prediction, and runs stratified K-fold cross-validation to
   record per-fold metrics, training curves, and confusion matrices, which are
   saved to disk.
3. Trains a final ResNet50 model on the full augmented training set with
   checkpointing, learning-rate scheduling, and CSV logging, evaluates on the
   held-out test set, reports accuracy/precision/recall/F1, and saves summary
   metrics, cross-validation statistics, and misclassification counts to CSV,
   alongside plots of learning curves and the final confusion matrix.
4. Visualizes misclassified test images with true/predicted labels, confidence,
   and error type (false positive vs false negative), exports a sorted
   misclassification table, and implements a custom Score-CAM routine adapted
   to ResNet50 internals to generate triplets (original, heatmap, overlay) for
   representative correct and misclassified samples, highlighting which image
   regions most influence the model’s decisions.
"""

import cv2
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (classification_report, confusion_matrix, ConfusionMatrixDisplay,
                             accuracy_score, precision_score, recall_score, f1_score)
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Input, GlobalAveragePooling2D,
                                     Dense, BatchNormalization, Dropout)
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, CSVLogger
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from sklearn.utils import class_weight
from google.colab import drive
import pickle

# ============================================================================
# SETUP & REPRODUCIBILITY
# ============================================================================
sns.set_style("darkgrid")
sns.set_palette("colorblind")

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)
os.environ["TF_DETERMINISTIC_OPS"] = "1"

# Mount Drive
drive.mount('/content/drive')

# Paths
image_directory = '/content/drive/My Drive/frost/frost_non_frost'
non_frost_images_path = os.path.join(image_directory, 'non_frost')
frost_images_path = os.path.join(image_directory, 'frost')
save_dir = '/content/drive/My Drive/frost/models_saved'
os.makedirs(save_dir, exist_ok=True)

# Constants
SIZE = 512
BATCH_SIZE = 32
EPOCHS = 25
AUGMENTATION_FACTOR = 4
N_FOLDS = 5

# ============================================================================
# DATA LOADING
# ============================================================================
print("Loading images...")
dataset = []
labels = []

# Load non-frost images (label 0)
for image_name in os.listdir(non_frost_images_path):
    if image_name.lower().endswith(('tif', 'png', 'jpg', 'jpeg')):
        image_path = os.path.join(non_frost_images_path, image_name)
        image = cv2.imread(image_path)
        if image is None:
            continue
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (SIZE, SIZE))
        dataset.append(image)
        labels.append(0)

# Load frost images (label 1)
for image_name in os.listdir(frost_images_path):
    if image_name.lower().endswith(('tif', 'png', 'jpg', 'jpeg')):
        image_path = os.path.join(frost_images_path, image_name)
        image = cv2.imread(image_path)
        if image is None:
            continue
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (SIZE, SIZE))
        dataset.append(image)
        labels.append(1)

# Normalize to [0, 1]
dataset = np.array(dataset, dtype=np.float32) / 255.0
labels = np.array(labels)

print(f"Total samples: {len(dataset)}")
print(f"Class distribution: {np.unique(labels, return_counts=True)}")

# ============================================================================
# DATA SPLITTING (CONSISTENT ACROSS ALL MODELS)
# ============================================================================
print("\nCreating train/val/test splits...")
X_train, X_temp, y_train, y_temp = train_test_split(
    dataset, labels, test_size=0.3, random_state=SEED, stratify=labels
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=SEED, stratify=y_temp
)

print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

# Save splits for consistency across models
np.save(os.path.join(save_dir, 'X_test.npy'), X_test)
np.save(os.path.join(save_dir, 'y_test.npy'), y_test)

# ============================================================================
# DATA AUGMENTATION
# ============================================================================
print("\nAugmenting training data...")
train_datagen = ImageDataGenerator(
    rotation_range=30,
    horizontal_flip=True,
    vertical_flip = True,
    fill_mode='reflect'
)

def augment_data(X, y, factor=AUGMENTATION_FACTOR):
    aug_images = []
    aug_labels = []
    for i in range(len(X)):
        image = np.expand_dims(X[i], axis=0)
        label = y[i]
        aug_iter = train_datagen.flow(image, batch_size=1)
        for _ in range(factor):
            aug_images.append(next(aug_iter)[0])
            aug_labels.append(label)

    X_aug = np.concatenate([X, np.array(aug_images)], axis=0).astype(np.float32)
    y_aug = np.concatenate([y, np.array(aug_labels)], axis=0).astype(int)
    return X_aug, y_aug

X_train_aug, y_train_aug = augment_data(X_train, y_train)
print(f"Augmented training data: {X_train_aug.shape}")

# Class weights
class_weights = class_weight.compute_class_weight(
    'balanced',
    classes=np.unique(y_train_aug),
    y=y_train_aug
)
class_weights = dict(enumerate(class_weights))
print(f"Class weights: {class_weights}")

# ============================================================================
# ResNet50 MODEL DEFINITION
# ============================================================================
def create_resnet_model(input_shape=(SIZE, SIZE, 3)):

    base_model = ResNet50(include_top=False, weights='imagenet', input_shape=input_shape)

    # Freeze all but the last 10 layers
    for layer in base_model.layers[:-10]:
        layer.trainable = False
    for layer in base_model.layers[-10:]:
        layer.trainable = True

    # Functional graph
    inputs = Input(shape=input_shape)
    x = base_model(inputs, training=False)
    x = GlobalAveragePooling2D()(x)

    x = Dense(64, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.4)(x)

    x = Dense(32, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.3)(x)

    x = Dense(8, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.2)(x)

    outputs = Dense(1, activation='sigmoid', kernel_regularizer=l2(0.001))(x)

    model = Model(inputs, outputs)

    model.compile(
        optimizer=Adam(learning_rate=2e-5),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    return model

# ============================================================================
# PHASE 1: CROSS-VALIDATION
# ============================================================================
print("\n" + "="*60)
print("PHASE 1: CROSS-VALIDATION")
print("="*60)

skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
cv_results = []

for fold_idx, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train), start=1):
    print(f"\n--- Fold {fold_idx}/{N_FOLDS} ---")

    # Split fold data
    X_fold_train = X_train[train_idx]
    y_fold_train = y_train[train_idx]
    X_fold_val = X_train[val_idx]
    y_fold_val = y_train[val_idx]

    # Augment fold training data
    X_fold_aug, y_fold_aug = augment_data(X_fold_train, y_fold_train)

    # Fold class weights
    fold_cw = class_weight.compute_class_weight(
        'balanced', classes=np.unique(y_fold_aug), y=y_fold_aug
    )
    fold_cw = dict(enumerate(fold_cw))

    # Create and train model
    model = create_resnet_model()
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-7, verbose=0)

    history = model.fit(
        X_fold_aug, y_fold_aug,
        validation_data=(X_fold_val, y_fold_val),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        shuffle=True,
        class_weight=fold_cw,
        callbacks=[reduce_lr],
        verbose=1
    )

    # Get predictions
    y_pred_probs = model.predict(X_fold_val, batch_size=32, verbose=0)
    y_pred = (y_pred_probs > 0.5).astype(int).flatten()

    # Calculate metrics
    report = classification_report(y_fold_val, y_pred, output_dict=True, zero_division=0)

    # Print classification report
    print(f"\nClassification Report - Fold {fold_idx}:")
    print(classification_report(y_fold_val, y_pred, target_names=['Non-Frost', 'Frost'], zero_division=0))

    # PLOT 1: Training curves
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy', linewidth=2)
    plt.plot(history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
    plt.title(f'Accuracy - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss', linewidth=2)
    plt.plot(history.history['val_loss'], label='Val Loss', linewidth=2)
    plt.title(f'Loss - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    plt.suptitle(f'Training Curves - Fold {fold_idx}/{N_FOLDS}', fontsize=16)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'resnet_fold_{fold_idx}_curves.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # PLOT 2: Confusion matrix
    plt.figure(figsize=(8, 6))
    cm = confusion_matrix(y_fold_val, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Non-Frost', 'Frost'])
    disp.plot(cmap='Blues')
    plt.title(f'Confusion Matrix - Fold {fold_idx}/{N_FOLDS}', fontsize=14, fontweight='bold')
    plt.grid(False)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'resnet_fold_{fold_idx}_confusion.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # Save fold results
    fold_result = {
        'Fold': fold_idx,
        'Accuracy': report['accuracy'],
        'Precision_Frost': report.get('1', {}).get('precision', 0),
        'Recall_Frost': report.get('1', {}).get('recall', 0),
        'F1_Frost': report.get('1', {}).get('f1-score', 0),
        'Precision_Non_Frost': report.get('0', {}).get('precision', 0),
        'Recall_Non_Frost': report.get('0', {}).get('recall', 0),
        'F1_Non_Frost': report.get('0', {}).get('f1-score', 0),
        'Loss': history.history['val_loss'][-1]
    }
    cv_results.append(fold_result)

    print(f"Accuracy: {fold_result['Accuracy']:.4f}, F1 (Frost): {fold_result['F1_Frost']:.4f}")

    # Clear memory
    del model, history, y_pred_probs, y_pred
    tf.keras.backend.clear_session()

# Save CV results
cv_df = pd.DataFrame(cv_results)
cv_df.to_csv(os.path.join(save_dir, 'resnet_cv_results.csv'), index=False)

print("\n" + "="*60)
print("CROSS-VALIDATION SUMMARY")
print("="*60)
print(cv_df.describe())

# ============================================================================
# PHASE 2: FINAL MODEL TRAINING
# ============================================================================
print("\n" + "="*60)
print("PHASE 2: FINAL MODEL TRAINING")
print("="*60)

# Train final model on full augmented training data
final_model = create_resnet_model()

checkpoint_cb = ModelCheckpoint(
    filepath=os.path.join(save_dir, 'resnet_best_model.h5'),
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-7, verbose=1)
csv_logger = CSVLogger(os.path.join(save_dir, 'resnet_training_log.csv'))

final_history = final_model.fit(
    X_train_aug, y_train_aug,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    class_weight=class_weights,
    callbacks=[checkpoint_cb, reduce_lr, csv_logger],
    verbose=1
)

# ============================================================================
# FINAL TEST SET EVALUATION
# ============================================================================
print("\n" + "="*60)
print("TEST SET EVALUATION")
print("="*60)

# Standard predictions on test set
y_test_pred_probs = final_model.predict(X_test, batch_size=32, verbose=0).flatten()
y_test_pred = (y_test_pred_probs > 0.5).astype(int)

# Classification report
print("\nClassification Report - Test Set:")
print(classification_report(y_test, y_test_pred, target_names=['Non-Frost', 'Frost']))

# PLOT 1: Training curves for final model
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(final_history.history['accuracy'], label='Train Accuracy', linewidth=2)
plt.plot(final_history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
plt.title('Model Accuracy - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(final_history.history['loss'], label='Train Loss', linewidth=2)
plt.plot(final_history.history['val_loss'], label='Val Loss', linewidth=2)
plt.title('Model Loss - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.suptitle('Final Model Training Curves', fontsize=16)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'resnet_final_training_curves.png'), dpi=300, bbox_inches='tight')
plt.show()

# PLOT 2: Confusion Matrix for test set
plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_test_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Non-Frost', 'Frost'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix - Test Set", fontsize=14, fontweight='bold')
plt.grid(False)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'resnet_test_confusion_matrix.png'), dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# SAVE FINAL RESULTS
# ============================================================================
# Calculate misclassifications
misclassified_idx = np.where(y_test_pred != y_test)[0]

final_results = {
    'Model': 'ResNet50',
    'Test_Accuracy': accuracy_score(y_test, y_test_pred),
    'Test_Precision': precision_score(y_test, y_test_pred),
    'Test_Recall': recall_score(y_test, y_test_pred),
    'Test_F1': f1_score(y_test, y_test_pred),
    'CV_Accuracy_Mean': cv_df['Accuracy'].mean(),
    'CV_Accuracy_Std': cv_df['Accuracy'].std(),
    'Misclassifications': len(misclassified_idx)
}

pd.DataFrame([final_results]).to_csv(
    os.path.join(save_dir, 'resnet_final_results.csv'), index=False
)

print("\n" + "="*60)
print("FINAL RESULTS")
print("="*60)
for key, value in final_results.items():
    print(f"{key}: {value}")

print("\n✅ All results saved to:", save_dir)

# ============================================================================
# MISCLASSIFIED IMAGES VISUALIZATION
# ============================================================================
print("\n" + "="*60)
print("VISUALIZING MISCLASSIFIED IMAGES")
print("="*60)

# Find misclassified samples
misclassified_idx = np.where(y_test_pred != y_test)[0]
print(f"Number of misclassified images: {len(misclassified_idx)} / {len(y_test)} ({100*len(misclassified_idx)/len(y_test):.1f}%)")

if len(misclassified_idx) > 0:
    # Visualize up to 20 misclassified images
    num_to_show = min(20, len(misclassified_idx))

    # Create figure with subplots
    fig, axes = plt.subplots(4, 5, figsize=(20, 16))
    axes = axes.flatten()

    for i, idx in enumerate(misclassified_idx[:num_to_show]):
        img = X_test[idx]
        true_label = 'Frost' if y_test[idx] == 1 else 'Non-Frost'
        pred_label = 'Frost' if y_test_pred[idx] == 1 else 'Non-Frost'
        confidence = y_test_pred_probs[idx] if y_test_pred[idx] == 1 else (1 - y_test_pred_probs[idx])

        axes[i].imshow(img)
        axes[i].set_title(f'True: {true_label}\nPred: {pred_label}\nConf: {confidence:.2%}',
                         fontsize=10, fontweight='bold')
        axes[i].axis('off')

    # Hide unused subplots
    for i in range(num_to_show, len(axes)):
        axes[i].axis('off')

    plt.suptitle('Misclassified Images on Test Set', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'resnet_misclassified_images.png'), dpi=300, bbox_inches='tight')
    plt.show()

    # Save detailed misclassification info
    misclass_info = []
    for idx in misclassified_idx:
        info_dict = {
            'Sample_Index': int(idx),
            'True_Label': 'Frost' if y_test[idx] == 1 else 'Non-Frost',
            'Predicted_Label': 'Frost' if y_test_pred[idx] == 1 else 'Non-Frost',
            'Confidence': float(y_test_pred_probs[idx]),
            'Prediction_Score': float(y_test_pred_probs[idx]),
            'Error_Type': 'False Positive (Frost predicted, Non-Frost actual)' if (y_test[idx] == 0 and y_test_pred[idx] == 1) else 'False Negative (Non-Frost predicted, Frost actual)'
        }
        misclass_info.append(info_dict)

    misclass_df = pd.DataFrame(misclass_info)
    misclass_df = misclass_df.sort_values('Confidence', ascending=False)
    misclass_df.to_csv(os.path.join(save_dir, 'resnet_misclassifications.csv'), index=False)
    print(f"\n✅ Saved misclassification details to: {os.path.join(save_dir, 'resnet_misclassifications.csv')}")

    # Print error type breakdown
    error_types = misclass_df['Error_Type'].value_counts()
    print("\nError Breakdown:")
    for error_type, count in error_types.items():
        print(f"  {error_type}: {count}")
else:
    print("🎉 Perfect classification! No misclassified images.")

print("\n" + "="*60)
print("TRAINING COMPLETE")
print("="*60)

# ============================================================================
# SCORE-CAM IMPLEMENTATION FOR RESNET50
# ============================================================================
print("\n" + "="*60)
print("SCORE-CAM IMPLEMENTATION & VISUALIZATION (ResNet50)")
print("="*60)

# Define ScoreCAM class
class ScoreCAM:
    def __init__(self, model, layer_name=None):
        self.model = model
        self.layer_name = layer_name

        # Find the last convolutional layer if layer_name is not specified
        if self.layer_name is None:
            # For ResNet50 models, look for the base model layers
            resnet_layer = None
            for layer in self.model.layers:
                if 'resnet' in layer.name.lower():
                    resnet_layer = layer
                    break

            if resnet_layer is not None:
                # Look for good layers in ResNet50
                # ResNet50 uses 'conv' naming convention with blocks
                for sublayer in reversed(resnet_layer.layers):
                    # Try to find the last conv block output
                    if ('conv5_block3' in sublayer.name and ('out' in sublayer.name or 'add' in sublayer.name)) or \
                       ('conv5_block3_3_conv' in sublayer.name) or \
                       ('conv4_block6' in sublayer.name and ('out' in sublayer.name or 'add' in sublayer.name)):
                        self.layer_name = sublayer.name
                        self.base_model = resnet_layer
                        break

                # If not found, try any conv layer in the last stages
                if self.layer_name is None:
                    for sublayer in reversed(resnet_layer.layers):
                        if 'conv' in sublayer.name.lower() and ('conv5' in sublayer.name or 'conv4' in sublayer.name):
                            if hasattr(sublayer, 'output_shape') and len(sublayer.output_shape) == 4:
                                self.layer_name = sublayer.name
                                self.base_model = resnet_layer
                                break
            else:
                # If no ResNet layer found, search in the main model
                for layer in reversed(self.model.layers):
                    if 'conv' in layer.name.lower() and hasattr(layer, 'output_shape') and len(layer.output_shape) == 4:
                        self.layer_name = layer.name
                        break

        if self.layer_name is None:
            # Manual fallback - use a known good layer name for ResNet50
            self.layer_name = 'conv4_block6_out'
            resnet_layer = None
            for layer in self.model.layers:
                if 'resnet' in layer.name.lower():
                    resnet_layer = layer
                    break
            self.base_model = resnet_layer

        # Create a model that outputs feature maps from the specified layer
        try:
            if hasattr(self, 'base_model') and self.base_model is not None:
                target_layer = self.base_model.get_layer(self.layer_name)
                self.feature_model = tf.keras.models.Model(
                    inputs=self.base_model.input,
                    outputs=target_layer.output
                )
            else:
                self.feature_model = tf.keras.models.Model(
                    inputs=self.model.input,
                    outputs=self.model.get_layer(self.layer_name).output
                )
        except Exception as e:
            # Try alternative layers for ResNet50
            alternative_layers = [
                'conv5_block3_out',
                'conv5_block3_add',
                'conv5_block3_3_conv',
                'conv5_block2_out',
                'conv4_block6_out',
                'conv5_block1_out'
            ]
            for alt_layer in alternative_layers:
                try:
                    if hasattr(self, 'base_model') and self.base_model is not None:
                        target_layer = self.base_model.get_layer(alt_layer)
                        self.feature_model = tf.keras.models.Model(
                            inputs=self.base_model.input,
                            outputs=target_layer.output
                        )
                        self.layer_name = alt_layer
                        break
                except:
                    continue

        print(f"Score-CAM using layer: {self.layer_name}")

    def generate_cam(self, input_image):
        if len(input_image.shape) == 3:
            input_image = np.expand_dims(input_image, axis=0)

        # Get feature maps
        feature_maps = self.feature_model.predict(input_image, verbose=0)

        # Get original prediction score
        original_score = self.model.predict(input_image, verbose=0)[0]
        if len(original_score.shape) > 0 and original_score.shape[0] > 0:
            original_score = original_score[0]

        # Initialize weights for each feature map
        weights = []

        # Sample every nth feature map to speed up computation
        n_features = feature_maps.shape[-1]
        step = max(1, n_features // 50)  # Use at most 50 feature maps

        for i in range(0, n_features, step):
            # Extract single feature map
            feature_map = feature_maps[0, :, :, i]

            # Resize feature map to input image size
            resized_feature_map = cv2.resize(feature_map, (input_image.shape[2], input_image.shape[1]))

            # Normalize feature map to [0, 1]
            if resized_feature_map.max() > resized_feature_map.min():
                normalized_feature_map = (resized_feature_map - resized_feature_map.min()) / \
                                       (resized_feature_map.max() - resized_feature_map.min())
            else:
                normalized_feature_map = np.zeros_like(resized_feature_map)

            # Create masked image
            masked_image = input_image[0] * np.expand_dims(normalized_feature_map, axis=-1)
            masked_image = np.expand_dims(masked_image, axis=0)

            # Get prediction score for masked image
            try:
                masked_score = self.model.predict(masked_image, verbose=0)[0]
                if len(masked_score.shape) > 0 and masked_score.shape[0] > 0:
                    masked_score = masked_score[0]
                weights.append(masked_score)
            except:
                weights.append(0.0)

        weights = np.array(weights)

        # Generate weighted combination of feature maps
        cam = np.zeros((feature_maps.shape[1], feature_maps.shape[2]), dtype=np.float32)

        for idx, i in enumerate(range(0, n_features, step)):
            cam += weights[idx] * feature_maps[0, :, :, i]

        # Apply ReLU and normalize CAM
        cam = np.maximum(cam, 0)
        if cam.max() > cam.min():
            cam = (cam - cam.min()) / (cam.max() - cam.min())

        return cam, original_score

def overlay_heatmap_scorecam(img, heatmap, alpha=0.4, colormap=cv2.COLORMAP_JET):
    """
    Overlay heatmap on image.

    Args:
        img: Original image (H, W, 3) in range [0, 1]
        heatmap: Heatmap (H, W) in range [0, 1]
        alpha: Transparency of heatmap
        colormap: OpenCV colormap

    Returns:
        Overlayed image
    """
    # Convert heatmap to RGB
    heatmap_uint8 = np.uint8(255 * heatmap)
    heatmap_colored = cv2.applyColorMap(heatmap_uint8, colormap)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)
    heatmap_colored = heatmap_colored.astype(np.float32) / 255.0

    # Convert image to proper format
    img_display = img.copy()

    # Overlay
    overlayed = heatmap_colored * alpha + img_display * (1 - alpha)
    overlayed = np.clip(overlayed, 0, 1)

    return overlayed

# Initialize Score-CAM with the final model
try:
    score_cam = ScoreCAM(final_model)
    print("Score-CAM initialized successfully!")
except Exception as e:
    print(f"Error initializing Score-CAM: {e}")
    score_cam = None

# Select samples for Score-CAM visualization
samples_to_visualize = []

# Correctly classified frost images
correct_frost = np.where((y_test == 1) & (y_test_pred == 1))[0]
if len(correct_frost) > 0:
    samples_to_visualize.extend(correct_frost[:2])

# Correctly classified non-frost images
correct_non_frost = np.where((y_test == 0) & (y_test_pred == 0))[0]
if len(correct_non_frost) > 0:
    samples_to_visualize.extend(correct_non_frost[:2])

# Misclassified images
if len(misclassified_idx) > 0:
    samples_to_visualize.extend(misclassified_idx[:4])

# Generate Score-CAM for selected samples
if score_cam is not None and len(samples_to_visualize) > 0:
    print(f"Generating Score-CAM for {len(samples_to_visualize)} samples...")

    num_samples = len(samples_to_visualize)
    fig, axes = plt.subplots(num_samples, 3, figsize=(15, 5*num_samples))
    if num_samples == 1:
        axes = axes.reshape(1, -1)

    for i, idx in enumerate(samples_to_visualize):
        img = X_test[idx]
        true_label = 'Frost' if y_test[idx] == 1 else 'Non-Frost'
        pred_label = 'Frost' if y_test_pred[idx] == 1 else 'Non-Frost'
        confidence = y_test_pred_probs[idx]

        try:
            # Generate Score-CAM
            cam, cam_confidence = score_cam.generate_cam(img)

            # Resize CAM to match image size
            cam_resized = cv2.resize(cam, (SIZE, SIZE))

            # Create overlay
            overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)

        except Exception as e:
            print(f"Error generating Score-CAM for sample {idx}: {str(e)}")
            cam_resized = np.zeros((SIZE, SIZE))
            overlay = img

        # Plot original image
        axes[i, 0].imshow(img)
        axes[i, 0].set_title(f'Original\nTrue: {true_label}\nPred: {pred_label} ({confidence:.2%})',
                            fontsize=10, fontweight='bold')
        axes[i, 0].axis('off')

        # Plot heatmap
        im = axes[i, 1].imshow(cam_resized, cmap='jet')
        axes[i, 1].set_title('Score-CAM Heatmap', fontsize=10, fontweight='bold')
        axes[i, 1].axis('off')
        plt.colorbar(im, ax=axes[i, 1], fraction=0.046, pad=0.04)

        # Plot overlay
        axes[i, 2].imshow(overlay)
        axes[i, 2].set_title('Overlay', fontsize=10, fontweight='bold')
        axes[i, 2].axis('off')

    plt.suptitle('Score-CAM Visualizations (ResNet50)', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'resnet50_scorecam_visualization.png'), dpi=300, bbox_inches='tight')
    plt.show()

    print("Score-CAM visualization complete!")
    print(f"Score-CAM results saved to: {os.path.join(save_dir, 'resnet50_scorecam_visualization.png')}")
else:
    print("Score-CAM visualization skipped (no samples or Score-CAM initialization failed)")

print("\n" + "="*60)
print("ALL PROCESSING COMPLETE!")
print("="*60)

"""Extended ResNet50 Score-CAM analysis for the frost vs non-frost classifier,
probing confidence, decision boundary behavior, and error types.

This cell:
1. Reuses the trained ResNet50 model, test predictions, and previously defined
   Score-CAM implementation, checking that all required variables are present
   and (re)initializing Score-CAM as needed, then defines human-readable class
   names for visualization.
2. Generates Score-CAM overlays for: high- vs low-confidence predictions in
   each class, borderline cases near the 0.5 decision threshold, and explicit
   false positives vs false negatives, saving separate figures that show how
   spatial attention differs across confidence regimes and error types.
3. Builds a diverse comparison grid mixing correct frost/non-frost cases,
   misclassifications, and borderline examples, and a confidence-spectrum grid
   that samples images from different probability ranges, to visually relate
   model confidence to the regions it attends to.
4. Prints summary statistics on overall accuracy, counts of each error type,
   the number of borderline and high-confidence correct cases, and lists the
   generated PNG files, providing a compact quantitative overview of the
   extended qualitative analysis.
"""

# ============================================================================
# ADDITIONAL SCORE-CAM VISUALIZATIONS - EXTENDED ANALYSIS (ResNet50)
# Run this cell separately after the main Score-CAM code
# ============================================================================
print("\n" + "="*80)
print("EXTENDED SCORE-CAM ANALYSIS - ResNet50")
print("="*80)

# Check if required variables exist
try:
    _ = final_model, X_test, y_test, y_test_pred, y_test_pred_probs
    print("✓ All required variables found. Proceeding with analysis...")
except NameError as e:
    print(f"✗ Error: Missing required variable - {e}")
    print("Please run the main training and Score-CAM code first!")
    raise

# Check if Score-CAM is initialized
if 'score_cam' not in locals() and 'score_cam' not in globals():
    print("\n⚠ Warning: Score-CAM not found. Initializing now...")
    try:
        score_cam = ScoreCAM(final_model)
        print("✓ Score-CAM initialized successfully!")
    except Exception as e:
        print(f"✗ Error initializing Score-CAM: {e}")
        score_cam = None
elif score_cam is None:
    print("\n⚠ Warning: Score-CAM is None. Re-initializing...")
    try:
        score_cam = ScoreCAM(final_model)
        print("✓ Score-CAM initialized successfully!")
    except Exception as e:
        print(f"✗ Error initializing Score-CAM: {e}")
else:
    print("✓ Score-CAM already initialized")

# Define class names
class_names = ['Non-Frost', 'Frost']

# ============================================================================
# VISUALIZATION 1: CONFIDENCE-BASED ANALYSIS
# ============================================================================
print("\n" + "-"*80)
print("1. HIGH VS LOW CONFIDENCE PREDICTIONS")
print("-"*80)

if score_cam is not None:
    try:
        # Get high and low confidence samples
        high_conf_frost = np.where((y_test_pred == 1) & (y_test_pred_probs > 0.9))[0]
        low_conf_frost = np.where((y_test_pred == 1) & (y_test_pred_probs < 0.7))[0]
        high_conf_nonfrost = np.where((y_test_pred == 0) & (y_test_pred_probs < 0.1))[0]
        low_conf_nonfrost = np.where((y_test_pred == 0) & (y_test_pred_probs > 0.3))[0]

        print(f"  High confidence frost: {len(high_conf_frost)}")
        print(f"  Low confidence frost: {len(low_conf_frost)}")
        print(f"  High confidence non-frost: {len(high_conf_nonfrost)}")
        print(f"  Low confidence non-frost: {len(low_conf_nonfrost)}")

        selected_indices = []
        if len(high_conf_frost) > 0: selected_indices.extend(high_conf_frost[:2])
        if len(low_conf_frost) > 0: selected_indices.extend(low_conf_frost[:2])
        if len(high_conf_nonfrost) > 0: selected_indices.extend(high_conf_nonfrost[:2])
        if len(low_conf_nonfrost) > 0: selected_indices.extend(low_conf_nonfrost[:2])

        if len(selected_indices) > 0:
            fig, axes = plt.subplots(2, 4, figsize=(20, 10))
            axes = axes.ravel()

            for i, idx in enumerate(selected_indices[:8]):
                img = X_test[idx]

                try:
                    cam, cam_confidence = score_cam.generate_cam(img)
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)
                except Exception as e:
                    print(f"  Warning: CAM generation failed for sample {idx}: {e}")
                    overlay = img

                axes[i].imshow(overlay)
                axes[i].axis('off')

                pred_prob = y_test_pred_probs[idx]
                conf_type = "HIGH" if (pred_prob > 0.9 or pred_prob < 0.1) else "LOW"
                status = "✓" if y_test[idx] == y_test_pred[idx] else "✗"

                axes[i].set_title(
                    f"{status} {conf_type} Confidence\n"
                    f"True: {class_names[y_test[idx]]} | Pred: {class_names[y_test_pred[idx]]}\n"
                    f"Prob: {pred_prob:.3f}",
                    fontsize=9, fontweight='bold'
                )

            for i in range(len(selected_indices), 8):
                axes[i].axis('off')

            plt.suptitle("Score-CAM (ResNet50): High vs Low Confidence Predictions",
                        fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'resnet50_scorecam_confidence.png'),
                       dpi=300, bbox_inches='tight')
            plt.show()
            print("✓ Confidence analysis complete!")
        else:
            print("⚠ No samples found matching confidence criteria")

    except Exception as e:
        print(f"✗ Error in confidence analysis: {e}")
        import traceback
        traceback.print_exc()

# ============================================================================
# VISUALIZATION 2: BORDERLINE CASES (AROUND 0.5 THRESHOLD)
# ============================================================================
print("\n" + "-"*80)
print("2. BORDERLINE PREDICTIONS (Near 0.5 threshold)")
print("-"*80)

if score_cam is not None:
    try:
        # Find predictions near the decision boundary
        borderline_indices = np.where(np.abs(y_test_pred_probs - 0.5) < 0.15)[0]
        print(f"  Found {len(borderline_indices)} borderline cases")

        if len(borderline_indices) > 0:
            sample_indices = borderline_indices[:8]

            fig, axes = plt.subplots(2, 4, figsize=(20, 10))
            axes = axes.ravel()

            for i, idx in enumerate(sample_indices):
                img = X_test[idx]

                try:
                    cam, cam_confidence = score_cam.generate_cam(img)
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)
                except Exception as e:
                    print(f"  Warning: CAM generation failed for sample {idx}: {e}")
                    overlay = img

                axes[i].imshow(overlay)
                axes[i].axis('off')

                status = "✓" if y_test[idx] == y_test_pred[idx] else "✗"
                axes[i].set_title(
                    f"{status} True: {class_names[y_test[idx]]} | Pred: {class_names[y_test_pred[idx]]}\n"
                    f"Prob: {y_test_pred_probs[idx]:.3f} (Near threshold)",
                    fontsize=9, fontweight='bold'
                )

            for i in range(len(sample_indices), 8):
                axes[i].axis('off')

            plt.suptitle("Score-CAM (ResNet50): Borderline Predictions (Uncertain Cases)",
                        fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'resnet50_scorecam_borderline.png'),
                       dpi=300, bbox_inches='tight')
            plt.show()
            print("✓ Borderline analysis complete!")
        else:
            print("⚠ No borderline cases found")

    except Exception as e:
        print(f"✗ Error in borderline analysis: {e}")
        import traceback
        traceback.print_exc()

# ============================================================================
# VISUALIZATION 3: FALSE POSITIVES VS FALSE NEGATIVES
# ============================================================================
print("\n" + "-"*80)
print("3. DETAILED MISCLASSIFICATION ANALYSIS")
print("-"*80)

if score_cam is not None:
    try:
        # Get false positives and false negatives
        false_positives = np.where((y_test == 0) & (y_test_pred == 1))[0]
        false_negatives = np.where((y_test == 1) & (y_test_pred == 0))[0]

        print(f"  False Positives: {len(false_positives)}")
        print(f"  False Negatives: {len(false_negatives)}")

        if len(false_positives) > 0 or len(false_negatives) > 0:
            # Select up to 4 of each type
            fp_samples = false_positives[:4]
            fn_samples = false_negatives[:4]

            n_fp = len(fp_samples)
            n_fn = len(fn_samples)
            n_total = n_fp + n_fn

            if n_total > 0:
                n_cols = 4
                n_rows = (n_total + n_cols - 1) // n_cols

                fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 5*n_rows))
                if n_rows == 1:
                    axes = np.array([axes]) if n_cols == 1 else axes
                axes = axes.ravel() if n_rows > 1 or n_cols > 1 else [axes]

                plot_idx = 0

                # Plot false positives
                for idx in fp_samples:
                    img = X_test[idx]

                    try:
                        cam, cam_confidence = score_cam.generate_cam(img)
                        cam_resized = cv2.resize(cam, (SIZE, SIZE))
                        overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)
                    except Exception as e:
                        print(f"  Warning: CAM generation failed for FP sample {idx}: {e}")
                        overlay = img

                    axes[plot_idx].imshow(overlay)
                    axes[plot_idx].axis('off')
                    axes[plot_idx].set_title(
                        f"FALSE POSITIVE\n"
                        f"True: Non-Frost | Pred: Frost\n"
                        f"Confidence: {y_test_pred_probs[idx]:.3f}",
                        fontsize=10, fontweight='bold', color='red'
                    )
                    plot_idx += 1

                # Plot false negatives
                for idx in fn_samples:
                    img = X_test[idx]

                    try:
                        cam, cam_confidence = score_cam.generate_cam(img)
                        cam_resized = cv2.resize(cam, (SIZE, SIZE))
                        overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)
                    except Exception as e:
                        print(f"  Warning: CAM generation failed for FN sample {idx}: {e}")
                        overlay = img

                    axes[plot_idx].imshow(overlay)
                    axes[plot_idx].axis('off')
                    axes[plot_idx].set_title(
                        f"FALSE NEGATIVE\n"
                        f"True: Frost | Pred: Non-Frost\n"
                        f"Confidence: {y_test_pred_probs[idx]:.3f}",
                        fontsize=10, fontweight='bold', color='orange'
                    )
                    plot_idx += 1

                # Hide unused subplots
                for i in range(plot_idx, len(axes)):
                    axes[i].axis('off')

                plt.suptitle("Score-CAM (ResNet50): Detailed Error Analysis",
                            fontsize=16, fontweight='bold')
                plt.tight_layout()
                plt.savefig(os.path.join(save_dir, 'resnet50_scorecam_errors_detailed.png'),
                           dpi=300, bbox_inches='tight')
                plt.show()
                print("✓ Error analysis complete!")
        else:
            print("⚠ Perfect predictions! No misclassifications found!")

    except Exception as e:
        print(f"✗ Error in misclassification analysis: {e}")
        import traceback
        traceback.print_exc()

# ============================================================================
# VISUALIZATION 4: COMPARISON GRID - DIVERSE SAMPLES
# ============================================================================
print("\n" + "-"*80)
print("4. DIVERSE SAMPLE COMPARISON")
print("-"*80)

if score_cam is not None:
    try:
        # Create a diverse set: correct frost, correct non-frost, FP, FN, borderline
        diverse_samples = []

        # 3 correct frost
        correct_frost = np.where((y_test == 1) & (y_test_pred == 1))[0]
        if len(correct_frost) >= 3:
            diverse_samples.extend(correct_frost[:3])
            print(f"  Added {min(3, len(correct_frost))} correct frost predictions")

        # 3 correct non-frost
        correct_nonfrost = np.where((y_test == 0) & (y_test_pred == 0))[0]
        if len(correct_nonfrost) >= 3:
            diverse_samples.extend(correct_nonfrost[:3])
            print(f"  Added {min(3, len(correct_nonfrost))} correct non-frost predictions")

        # 2 false positives
        if len(false_positives) >= 2:
            diverse_samples.extend(false_positives[:2])
            print(f"  Added {min(2, len(false_positives))} false positives")

        # 2 false negatives
        if len(false_negatives) >= 2:
            diverse_samples.extend(false_negatives[:2])
            print(f"  Added {min(2, len(false_negatives))} false negatives")

        # 2 borderline
        if len(borderline_indices) >= 2:
            diverse_samples.extend(borderline_indices[:2])
            print(f"  Added {min(2, len(borderline_indices))} borderline cases")

        if len(diverse_samples) > 0:
            n_samples = min(len(diverse_samples), 12)
            diverse_samples = diverse_samples[:n_samples]
            print(f"  Total diverse samples: {n_samples}")

            fig, axes = plt.subplots(3, 4, figsize=(20, 15))
            axes = axes.ravel()

            for i, idx in enumerate(diverse_samples):
                img = X_test[idx]

                try:
                    cam, cam_confidence = score_cam.generate_cam(img)
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)
                except Exception as e:
                    print(f"  Warning: CAM generation failed for sample {idx}: {e}")
                    overlay = img

                axes[i].imshow(overlay)
                axes[i].axis('off')

                status = "✓" if y_test[idx] == y_test_pred[idx] else "✗"
                axes[i].set_title(
                    f"{status} True: {class_names[y_test[idx]]} | Pred: {class_names[y_test_pred[idx]]}\n"
                    f"Confidence: {y_test_pred_probs[idx]:.3f}",
                    fontsize=9
                )

            for i in range(n_samples, 12):
                axes[i].axis('off')

            plt.suptitle("Score-CAM (ResNet50): Diverse Sample Comparison",
                        fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'resnet50_scorecam_diverse.png'),
                       dpi=300, bbox_inches='tight')
            plt.show()
            print("✓ Diverse sample analysis complete!")
        else:
            print("⚠ No diverse samples available")

    except Exception as e:
        print(f"✗ Error in diverse sample analysis: {e}")
        import traceback
        traceback.print_exc()

# ============================================================================
# VISUALIZATION 5: CONFIDENCE DISTRIBUTION ANALYSIS
# ============================================================================
print("\n" + "-"*80)
print("5. CONFIDENCE DISTRIBUTION WITH SCORE-CAM SAMPLES")
print("-"*80)

if score_cam is not None:
    try:
        # Select samples across confidence spectrum
        confidence_bins = [
            (0.0, 0.1, 'Very High Non-Frost'),
            (0.1, 0.3, 'High Non-Frost'),
            (0.3, 0.5, 'Leaning Non-Frost'),
            (0.5, 0.7, 'Leaning Frost'),
            (0.7, 0.9, 'High Frost'),
            (0.9, 1.0, 'Very High Frost')
        ]

        samples_per_bin = []
        for low, high, label in confidence_bins:
            bin_samples = np.where((y_test_pred_probs >= low) & (y_test_pred_probs < high))[0]
            if len(bin_samples) > 0:
                samples_per_bin.append((bin_samples[0], label))

        if len(samples_per_bin) > 0:
            n_samples = len(samples_per_bin)
            fig, axes = plt.subplots(2, 3, figsize=(18, 12))
            axes = axes.ravel()

            for i, (idx, label) in enumerate(samples_per_bin[:6]):
                img = X_test[idx]

                try:
                    cam, cam_confidence = score_cam.generate_cam(img)
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)
                except:
                    overlay = img

                axes[i].imshow(overlay)
                axes[i].axis('off')

                status = "✓" if y_test[idx] == y_test_pred[idx] else "✗"
                axes[i].set_title(
                    f"{status} {label}\n"
                    f"True: {class_names[y_test[idx]]} | Pred: {class_names[y_test_pred[idx]]}\n"
                    f"Confidence: {y_test_pred_probs[idx]:.3f}",
                    fontsize=9, fontweight='bold'
                )

            for i in range(len(samples_per_bin), 6):
                axes[i].axis('off')

            plt.suptitle("Score-CAM (ResNet50): Confidence Spectrum Analysis",
                        fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'resnet50_scorecam_confidence_spectrum.png'),
                       dpi=300, bbox_inches='tight')
            plt.show()
            print("✓ Confidence spectrum analysis complete!")
        else:
            print("⚠ Not enough samples across confidence spectrum")

    except Exception as e:
        print(f"✗ Error in confidence spectrum analysis: {e}")
        import traceback
        traceback.print_exc()

# ============================================================================
# SUMMARY STATISTICS
# ============================================================================
print("\n" + "="*80)
print("SUMMARY STATISTICS")
print("="*80)

if score_cam is not None:
    try:
        print(f"\n📊 OVERALL PERFORMANCE")
        print(f"  Total test samples: {len(X_test)}")
        print(f"  Correct predictions: {np.sum(y_test == y_test_pred)} ({100*np.sum(y_test == y_test_pred)/len(X_test):.2f}%)")
        print(f"  Incorrect predictions: {np.sum(y_test != y_test_pred)} ({100*np.sum(y_test != y_test_pred)/len(X_test):.2f}%)")

        print(f"\n❌ ERROR BREAKDOWN")
        print(f"  False Positives: {len(false_positives)}")
        print(f"  False Negatives: {len(false_negatives)}")

        print(f"\n🎯 CONFIDENCE ANALYSIS")
        print(f"  Borderline cases (prob 0.35-0.65): {len(borderline_indices)}")
        high_conf_correct = np.sum(((y_test_pred_probs > 0.9) | (y_test_pred_probs < 0.1)) & (y_test == y_test_pred))
        low_conf_correct = np.sum(((y_test_pred_probs >= 0.1) & (y_test_pred_probs <= 0.9)) & (y_test == y_test_pred))
        print(f"  High confidence correct (>0.9 or <0.1): {high_conf_correct}")
        print(f"  Low confidence correct (0.1-0.9): {low_conf_correct}")

        print(f"\n💾 OUTPUT FILES")
        print(f"  All Score-CAM visualizations saved to: {save_dir}")
        print(f"    • resnet50_scorecam_confidence.png")
        print(f"    • resnet50_scorecam_borderline.png")
        print(f"    • resnet50_scorecam_errors_detailed.png")
        print(f"    • resnet50_scorecam_diverse.png")
        print(f"    • resnet50_scorecam_confidence_spectrum.png")

    except Exception as e:
        print(f"✗ Error generating summary: {e}")
        import traceback
        traceback.print_exc()

print("\n" + "="*80)
print("✅ EXTENDED SCORE-CAM ANALYSIS COMPLETE!")
print("="*80)
