# -*- coding: utf-8 -*-
"""neu_cnn_multiclass

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HYyLD7l-r-kN99mJXIE_pRLxuyy2ria
"""

!pip install tf-keras-vis

"""End-to-end multiclass CNN pipeline for microstructure image classification,
with detailed misclassification analysis and optional Score-CAM explanations.

This cell:
1. Sets seeds, mounts Google Drive, and loads a folder-structured multiclass
   microstructure dataset (one subdirectory per class), resizing and
   normalizing images, encoding labels, and saving a stratified train/
   validation/test split for reuse.
2. Applies strong data augmentation (rotations, flips, height shifts) and
   class weighting to address limited data and imbalance, then defines a
   multiclass CNN with a dedicated penultimate convolutional layer for
   visualization, global max pooling, and L2-regularized dense layers.
3. Phase 1: Performs stratified K-fold cross-validation, logging per-fold
   accuracy, macro/weighted F1, and per-class precision/recall/F1, and
   saving training curves and confusion matrices to disk.
4. Phase 2: Trains a final CNN on the full augmented training set with
   checkpointing, learning-rate scheduling, and CSV logging, evaluates on
   the held-out test set, and stores global performance metrics and
   misclassification counts.
5. Visualizes misclassified test samples with top-2 predicted classes and
   confidences, summarizes confusion patterns and per-class error rates,
   and optionally generates multiclass Score-CAM heatmaps for a diverse
   subset of correct, misclassified, and low-confidence test images to
   inspect class-specific attention patterns.
"""

import cv2
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (classification_report, confusion_matrix, ConfusionMatrixDisplay,
                             accuracy_score, precision_score, recall_score, f1_score)
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Input, Conv2D, MaxPooling2D, GlobalMaxPooling2D,
                                     Dense, BatchNormalization, Dropout)
from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, CSVLogger
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from sklearn.utils import class_weight
from google.colab import drive
import pickle

# ============================================================================
# SETUP & REPRODUCIBILITY
# ============================================================================
sns.set_style("darkgrid")
sns.set_palette("colorblind")

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)
os.environ["TF_DETERMINISTIC_OPS"] = "1"

# Mount Drive
drive.mount('/content/drive')

# Paths
image_directory = '/content/drive/My Drive/frost/frost_non_frost/microstructures'
save_dir = '/content/drive/My Drive/frost/models_saved'
os.makedirs(save_dir, exist_ok=True)

# Constants
SIZE = 512
BATCH_SIZE = 32
EPOCHS = 20
AUGMENTATION_FACTOR = 10
N_FOLDS = 5

# ============================================================================
# DATA LOADING - MULTICLASS
# ============================================================================
print("Loading images from subdirectories...")
dataset = []
labels = []
class_names = []

# Automatically detect class folders
for class_idx, class_name in enumerate(sorted(os.listdir(image_directory))):
    class_path = os.path.join(image_directory, class_name)

    # Skip if not a directory
    if not os.path.isdir(class_path):
        continue

    class_names.append(class_name)
    print(f"Loading class {class_idx}: {class_name}")

    # Load images from this class
    for image_name in os.listdir(class_path):
        if image_name.lower().endswith(('tif', 'png', 'jpg', 'jpeg')):
            image_path = os.path.join(class_path, image_name)
            image = cv2.imread(image_path)
            if image is None:
                continue
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            image = cv2.resize(image, (SIZE, SIZE))
            dataset.append(image)
            labels.append(class_idx)

# Normalize to [0, 1]
dataset = np.array(dataset, dtype=np.float32) / 255.0
labels = np.array(labels)
NUM_CLASSES = len(class_names)

print(f"\nTotal samples: {len(dataset)}")
print(f"Number of classes: {NUM_CLASSES}")
print(f"Class names: {class_names}")
print(f"Class distribution: {np.unique(labels, return_counts=True)}")

# Save class names for later use
with open(os.path.join(save_dir, 'class_names.pkl'), 'wb') as f:
    pickle.dump(class_names, f)

# ============================================================================
# DATA SPLITTING (CONSISTENT ACROSS ALL MODELS)
# ============================================================================
print("\nCreating train/val/test splits...")
X_train, X_temp, y_train, y_temp = train_test_split(
    dataset, labels, test_size=0.3, random_state=SEED, stratify=labels
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=SEED, stratify=y_temp
)

print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

# Save splits for consistency across models
np.save(os.path.join(save_dir, 'X_test.npy'), X_test)
np.save(os.path.join(save_dir, 'y_test.npy'), y_test)

# ============================================================================
# DATA AUGMENTATION
# ============================================================================
print("\nAugmenting training data...")
train_datagen = ImageDataGenerator(
    rotation_range=40,
    horizontal_flip=True,
    vertical_flip=True,
    height_shift_range=0.2,
    fill_mode='reflect'
)

def augment_data(X, y, factor=AUGMENTATION_FACTOR):
    aug_images = []
    aug_labels = []
    for i in range(len(X)):
        image = np.expand_dims(X[i], axis=0)
        label = y[i]
        aug_iter = train_datagen.flow(image, batch_size=1)
        for _ in range(factor):
            aug_images.append(next(aug_iter)[0])
            aug_labels.append(label)

    X_aug = np.concatenate([X, np.array(aug_images)], axis=0).astype(np.float32)
    y_aug = np.concatenate([y, np.array(aug_labels)], axis=0).astype(int)
    return X_aug, y_aug

X_train_aug, y_train_aug = augment_data(X_train, y_train)
print(f"Augmented training data: {X_train_aug.shape}")

# Class weights
class_weights = class_weight.compute_class_weight(
    'balanced',
    classes=np.unique(y_train_aug),
    y=y_train_aug
)
class_weights = dict(enumerate(class_weights))
print(f"Class weights: {class_weights}")

# ============================================================================
# MULTICLASS CNN MODEL DEFINITION
# ============================================================================
def create_cnn_model(input_shape=(SIZE, SIZE, 3), num_classes=NUM_CLASSES):
    inputs = Input(shape=input_shape)

    # Keep MaxPooling for better feature localization
    x = Conv2D(32, (3, 3), activation='relu')(inputs)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = Conv2D(64, (3, 3), activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)


    # Additional conv layer for richer features (better Score-CAM)
    x = Conv2D(140, (3, 3), activation='relu', name='last_conv')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    # Use GlobalMaxPooling for better spatial feature retention
    x = GlobalMaxPooling2D()(x)

    # Larger dense layers for better feature learning
    x = Dense(45, activation='relu', kernel_regularizer=l2(0.0001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.4)(x)

    x = Dense(16, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.3)(x)

#    x = Dense(16, activation='relu', kernel_regularizer=l2(0.0001))(x)
#    x = BatchNormalization()(x)
#    x = Dropout(0.2)(x)

    outputs = Dense(num_classes, activation='softmax', kernel_regularizer=l2(0.0001))(x)

    model = Model(inputs=inputs, outputs=outputs)
    model.compile(
        optimizer=Adam(learning_rate=0.0003),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# ============================================================================
# PHASE 1: CROSS-VALIDATION
# ============================================================================
print("\n" + "="*60)
print("PHASE 1: CROSS-VALIDATION")
print("="*60)

skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
cv_results = []

for fold_idx, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train), start=1):
    print(f"\n--- Fold {fold_idx}/{N_FOLDS} ---")

    # Split fold data
    X_fold_train = X_train[train_idx]
    y_fold_train = y_train[train_idx]
    X_fold_val = X_train[val_idx]
    y_fold_val = y_train[val_idx]

    # Augment fold training data
    X_fold_aug, y_fold_aug = augment_data(X_fold_train, y_fold_train)

    # Fold class weights
    fold_cw = class_weight.compute_class_weight(
        'balanced', classes=np.unique(y_fold_aug), y=y_fold_aug
    )
    fold_cw = dict(enumerate(fold_cw))

    # Create and train model
    model = create_cnn_model()
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-6, verbose=0)

    history = model.fit(
        X_fold_aug, y_fold_aug,
        validation_data=(X_fold_val, y_fold_val),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        shuffle=True,
        class_weight=fold_cw,
        callbacks=[reduce_lr],
        verbose=1
    )

    # Get predictions
    y_pred_probs = model.predict(X_fold_val, batch_size=32, verbose=0)
    y_pred = np.argmax(y_pred_probs, axis=1)

    # Calculate metrics
    report = classification_report(y_fold_val, y_pred, output_dict=True, zero_division=0)

    # Print classification report
    print(f"\nClassification Report - Fold {fold_idx}:")
    print(classification_report(y_fold_val, y_pred, target_names=class_names, zero_division=0))

    # PLOT 1: Training curves
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy', linewidth=2)
    plt.plot(history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
    plt.title(f'Accuracy - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss', linewidth=2)
    plt.plot(history.history['val_loss'], label='Val Loss', linewidth=2)
    plt.title(f'Loss - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    plt.suptitle(f'Training Curves - Fold {fold_idx}/{N_FOLDS}', fontsize=16)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'cnn_fold_{fold_idx}_curves.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # PLOT 2: Confusion matrix
    plt.figure(figsize=(10, 8))
    cm = confusion_matrix(y_fold_val, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
    disp.plot(cmap='Blues')
    plt.title(f'Confusion Matrix - Fold {fold_idx}/{N_FOLDS}', fontsize=14, fontweight='bold')
    plt.grid(False)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'cnn_fold_{fold_idx}_confusion.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # Save fold results with per-class metrics
    fold_result = {
        'Fold': fold_idx,
        'Accuracy': report['accuracy'],
        'Macro_Avg_Precision': report['macro avg']['precision'],
        'Macro_Avg_Recall': report['macro avg']['recall'],
        'Macro_Avg_F1': report['macro avg']['f1-score'],
        'Weighted_Avg_F1': report['weighted avg']['f1-score'],
        'Loss': history.history['val_loss'][-1],
    }

    # Add per-class metrics
    for i, class_name in enumerate(class_names):
        if str(i) in report:
            fold_result[f'F1_{class_name}'] = report[str(i)]['f1-score']
            fold_result[f'Precision_{class_name}'] = report[str(i)]['precision']
            fold_result[f'Recall_{class_name}'] = report[str(i)]['recall']

    cv_results.append(fold_result)

    print(f"Accuracy: {fold_result['Accuracy']:.4f}, Macro F1: {fold_result['Macro_Avg_F1']:.4f}")

    # Clear memory
    del model, history, y_pred_probs, y_pred
    tf.keras.backend.clear_session()

# Save CV results
cv_df = pd.DataFrame(cv_results)
cv_df.to_csv(os.path.join(save_dir, 'cnn_cv_results.csv'), index=False)

print("\n" + "="*60)
print("CROSS-VALIDATION SUMMARY")
print("="*60)
print(cv_df.describe())

# ============================================================================
# PHASE 2: FINAL MODEL TRAINING
# ============================================================================
print("\n" + "="*60)
print("PHASE 2: FINAL MODEL TRAINING")
print("="*60)

# Train final model on full augmented training data
final_model = create_cnn_model()

checkpoint_cb = ModelCheckpoint(
    filepath=os.path.join(save_dir, 'cnn_best_model_multiclass.h5'),
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-6, verbose=1)
csv_logger = CSVLogger(os.path.join(save_dir, 'cnn_training_log_multiclass.csv'))

final_history = final_model.fit(
    X_train_aug, y_train_aug,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    class_weight=class_weights,
    callbacks=[checkpoint_cb, reduce_lr, csv_logger],
    verbose=1
)

# ============================================================================
# FINAL TEST SET EVALUATION
# ============================================================================
print("\n" + "="*60)
print("TEST SET EVALUATION")
print("="*60)

# Standard predictions on test set
y_test_pred_probs = final_model.predict(X_test, batch_size=32, verbose=0)
y_test_pred = np.argmax(y_test_pred_probs, axis=1)

# Classification report
print("\nClassification Report - Test Set:")
print(classification_report(y_test, y_test_pred, target_names=class_names))

# PLOT 1: Training curves for final model
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(final_history.history['accuracy'], label='Train Accuracy', linewidth=2)
plt.plot(final_history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
plt.title('Model Accuracy - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(final_history.history['loss'], label='Train Loss', linewidth=2)
plt.plot(final_history.history['val_loss'], label='Val Loss', linewidth=2)
plt.title('Model Loss - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.suptitle('Final Model Training Curves', fontsize=16)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'cnn_final_training_curves.png'), dpi=300, bbox_inches='tight')
plt.show()

# PLOT 2: Confusion Matrix for test set
plt.figure(figsize=(10, 8))
cm = confusion_matrix(y_test, y_test_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap='Blues')
plt.title("Confusion Matrix - Test Set", fontsize=14, fontweight='bold')
plt.grid(False)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'cnn_test_confusion_matrix.png'), dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# SAVE FINAL RESULTS
# ============================================================================
# Calculate misclassifications
misclassified_idx = np.where(y_test_pred != y_test)[0]

final_results = {
    'Model': 'CNN_Multiclass',
    'Num_Classes': NUM_CLASSES,
    'Test_Accuracy': accuracy_score(y_test, y_test_pred),
    'Test_Macro_Precision': precision_score(y_test, y_test_pred, average='macro'),
    'Test_Macro_Recall': recall_score(y_test, y_test_pred, average='macro'),
    'Test_Macro_F1': f1_score(y_test, y_test_pred, average='macro'),
    'Test_Weighted_F1': f1_score(y_test, y_test_pred, average='weighted'),
    'CV_Accuracy_Mean': cv_df['Accuracy'].mean(),
    'CV_Accuracy_Std': cv_df['Accuracy'].std(),
    'Misclassifications': len(misclassified_idx)
}

pd.DataFrame([final_results]).to_csv(
    os.path.join(save_dir, 'cnn_final_results.csv'), index=False
)

print("\n" + "="*60)
print("FINAL RESULTS")
print("="*60)
for key, value in final_results.items():
    print(f"{key}: {value}")

print("\n✅ All results saved to:", save_dir)


# ============================================================================
# VISUALIZE MISCLASSIFIED IMAGES
# ============================================================================
print("\n" + "="*60)
print("MISCLASSIFIED IMAGES ANALYSIS")
print("="*60)

misclassified_idx = np.where(y_test_pred != y_test)[0]
print(f"Total misclassified: {len(misclassified_idx)} out of {len(y_test)} ({len(misclassified_idx)/len(y_test)*100:.1f}%)")

if len(misclassified_idx) > 0:
    n_samples = min(12, len(misclassified_idx))

    fig = plt.figure(figsize=(16, 12))

    for i, idx in enumerate(misclassified_idx[:n_samples]):
        plt.subplot(3, 4, i + 1)
        img = X_test[idx]
        plt.imshow(np.clip(img, 0, 1))
        plt.axis('off')

        true_class = class_names[y_test[idx]]
        pred_class = class_names[y_test_pred[idx]]
        confidence = y_test_pred_probs[idx, y_test_pred[idx]]

        # Get top 2 predictions for context
        top2_idx = np.argsort(y_test_pred_probs[idx])[-2:][::-1]
        second_pred = class_names[top2_idx[1]]
        second_conf = y_test_pred_probs[idx, top2_idx[1]]

        plt.title(
            f"True: {true_class}\n"
            f"Pred: {pred_class} ({confidence:.2f})\n"
            f"2nd: {second_pred} ({second_conf:.2f})",
            fontsize=9,
            color='red'
        )

    plt.suptitle(f"Misclassified Test Images (n={len(misclassified_idx)})",
                 fontsize=16, fontweight='bold')
    plt.tight_layout(rect=(0, 0, 1, 0.96))
    plt.savefig(os.path.join(save_dir, 'cnn_misclassified_images.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # Confusion pattern analysis
    print("\n" + "="*40)
    print("CONFUSION PATTERNS")
    print("="*40)

    confusion_pairs = {}
    for idx in misclassified_idx:
        true_label = class_names[y_test[idx]]
        pred_label = class_names[y_test_pred[idx]]
        pair = f"{true_label} → {pred_label}"
        confusion_pairs[pair] = confusion_pairs.get(pair, 0) + 1

    print("\nMost common misclassifications:")
    for pair, count in sorted(confusion_pairs.items(), key=lambda x: x[1], reverse=True):
        print(f"  {pair}: {count} times")

    # Per-class error analysis
    print("\n" + "="*40)
    print("PER-CLASS ERROR RATES")
    print("="*40)

    for i, class_name in enumerate(class_names):
        class_mask = (y_test == i)
        class_total = np.sum(class_mask)
        class_errors = np.sum((y_test == i) & (y_test_pred != i))
        error_rate = class_errors / class_total * 100 if class_total > 0 else 0

        print(f"{class_name}: {class_errors}/{class_total} errors ({error_rate:.1f}%)")

        # Show what this class gets confused with
        if class_errors > 0:
            confused_with = y_test_pred[(y_test == i) & (y_test_pred != i)]
            unique, counts = np.unique(confused_with, return_counts=True)
            print(f"  Confused with:")
            for pred_class, count in zip(unique, counts):
                print(f"    - {class_names[pred_class]}: {count} times")

else:
    print("No misclassified images - perfect accuracy!")

print("\n✅ Misclassification analysis complete")


# ============================================================================
# SCORE-CAM VISUALIZATION (Optional Analysis)
# ============================================================================
RUN_SCORECAM = True  # Set to False to skip

if RUN_SCORECAM:
    print("\n" + "="*60)
    print("SCORE-CAM VISUALIZATION")
    print("="*60)

    try:
        from tf_keras_vis.scorecam import ScoreCAM
        from tf_keras_vis.utils.model_modifiers import ReplaceToLinear

        # Load best model
        print("Loading best model for Score-CAM...")
        best_model = tf.keras.models.load_model(
            os.path.join(save_dir, 'cnn_best_model_multiclass.h5')
        )

        # Score function for multiclass
        def score_function(output):
            # For each sample, return the predicted class score
            return tf.reduce_max(output, axis=-1)

        # Create Score-CAM object with model modifier
        def model_modifier(m):
            m.layers[-1].activation = tf.keras.activations.linear
            return m

        scorecam = ScoreCAM(best_model, model_modifier=model_modifier)

        # Select diverse samples to visualize
        correct_idx = np.where(y_test_pred == y_test)[0]

        # For CNN: select samples with lowest confidence (max probability closest to 1/NUM_CLASSES)
        max_probs = y_test_pred_probs.max(axis=1)
        low_confidence_idx = np.argsort(max_probs)[:10]  # Bottom 10 by max probability

        # Get sample indices
        sample_indices = []
        if len(correct_idx) >= 3:
            sample_indices.extend(correct_idx[:3])
        if len(misclassified_idx) >= 3:
            sample_indices.extend(misclassified_idx[:3])
        if len(low_confidence_idx) >= 3:
            sample_indices.extend(low_confidence_idx[:3])

        sample_indices = np.array(sample_indices[:9])

        if len(sample_indices) > 0:
            print(f"Generating Score-CAM for {len(sample_indices)} samples...")

            X_samples = X_test[sample_indices]
            cam = scorecam(
                score_function,
                X_samples,
                penultimate_layer='last_conv'
            )

            # Visualize
            n_rows = (len(sample_indices) + 2) // 3
            fig, axes = plt.subplots(n_rows, 3, figsize=(15, 5*n_rows))
            if n_rows > 1:
                axes = axes.ravel()
            elif n_rows == 1:
                axes = axes if isinstance(axes, np.ndarray) else np.array(axes)

            for i, idx in enumerate(sample_indices):
                ax = axes[i]
                img = X_test[idx]

                # Overlay CAM
                heatmap = cam[i]
                heatmap = np.uint8(255 * heatmap)
                heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
                heatmap = cv2.resize(heatmap, (SIZE, SIZE))

                superimposed = cv2.addWeighted(
                    (img * 255).astype(np.uint8), 0.6,
                    heatmap, 0.4, 0
                )

                ax.imshow(superimposed)
                ax.axis('off')

                true_label = class_names[y_test[idx]]
                pred_label = class_names[y_test_pred[idx]]
                confidence = y_test_pred_probs[idx, y_test_pred[idx]]

                status = "✓" if y_test[idx] == y_test_pred[idx] else "✗"
                ax.set_title(
                    f"{status} True: {true_label} | Pred: {pred_label}\n"
                    f"Confidence: {confidence:.2f}",
                    fontsize=10
                )

            for i in range(len(sample_indices), len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM Visualizations - CNN Multiclass", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'cnn_scorecam.png'), dpi=300, bbox_inches='tight')
            plt.show()

            print(f"✓ Score-CAM visualizations saved")
        else:
            print("⚠ Not enough samples for Score-CAM visualization")

    except ImportError:
        print("⚠ tf-keras-vis not installed. Run: pip install tf-keras-vis")
    except Exception as e:
        print(f"⚠ Score-CAM failed: {str(e)}")
        import traceback
        print(traceback.format_exc())
else:
    print("\n⏭ Skipping Score-CAM (set RUN_SCORECAM=True to enable)")

print("\n" + "="*60)
print("✅ ANALYSIS COMPLETE")
print("="*60)

"""Additional multiclass Score-CAM visualizations to explore CNN attention
patterns across test and validation data and across confidence regimes.

This cell:
1. Reuses the trained multiclass CNN, the existing ScoreCAM object, and stored
   predictions to generate extra heatmaps on held-out samples.
2. Produces Score-CAM overlays for: (a) randomly sampled test images annotated
   with predicted class and confidence, (b) selected validation images that are
   correctly classified or misclassified, and (c) correctly classified examples
   from each class to visualize per-class attention patterns.
3. Compares low- vs high-confidence correctly classified test samples via paired
   Score-CAM panels, highlighting how spatial focus varies with prediction
   confidence, and saves all resulting figures (random test, validation subset,
   per-class panels, and confidence comparison) to disk.
"""

# ============================================================================
# ADDITIONAL SCORE-CAM VISUALIZATIONS - MULTICLASS
# ============================================================================
print("\n" + "="*60)
print("ADDITIONAL SCORE-CAM ANALYSIS")
print("="*60)

if RUN_SCORECAM:
    try:
        # We already have the ScoreCAM object from previous cell
        print("Generating additional Score-CAM visualizations...")

        # Option 1: Show more test samples (random selection)
        print("\n--- Random Test Samples ---")
        np.random.seed(42)  # For reproducible selection
        random_test_indices = np.random.choice(len(X_test), size=6, replace=False)

        X_random = X_test[random_test_indices]
        cam_random = scorecam(score_function, X_random, penultimate_layer='last_conv')

        fig, axes = plt.subplots(2, 3, figsize=(15, 10))
        axes = axes.ravel()

        for i, idx in enumerate(random_test_indices):
            ax = axes[i]

            # Original image
            img = X_test[idx]

            # Overlay CAM
            heatmap = cam_random[i]
            heatmap = np.uint8(255 * heatmap)
            heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
            heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
            heatmap = cv2.resize(heatmap, (SIZE, SIZE))

            # Superimpose
            superimposed = cv2.addWeighted(
                (img * 255).astype(np.uint8), 0.6,
                heatmap, 0.4, 0
            )

            ax.imshow(superimposed)
            ax.axis('off')

            # Get prediction for this sample
            pred_class = y_test_pred[idx]
            true_class = y_test[idx]
            confidence = y_test_pred_probs[idx, pred_class]

            true_label = class_names[true_class]
            pred_label = class_names[pred_class]
            status = "✓" if true_class == pred_class else "✗"

            ax.set_title(
                f"{status} True: {true_label} | Pred: {pred_label}\n"
                f"Confidence: {confidence:.2f}",
                fontsize=10
            )

        plt.suptitle("Score-CAM: Random Test Samples", fontsize=16, fontweight='bold')
        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, 'cnn_scorecam_random.png'), dpi=300, bbox_inches='tight')
        plt.show()

        # Option 2: Show validation samples
        print("\n--- Validation Samples ---")

        # Get validation predictions
        val_pred_probs = final_model.predict(X_val, batch_size=32, verbose=0)
        val_pred = np.argmax(val_pred_probs, axis=1)

        # Select interesting validation samples
        val_correct = np.where(val_pred == y_val)[0]
        val_misclassified = np.where(val_pred != y_val)[0]

        val_sample_indices = []
        if len(val_correct) >= 3:
            val_sample_indices.extend(val_correct[:3])
        if len(val_misclassified) >= 3:
            val_sample_indices.extend(val_misclassified[:3])

        if len(val_sample_indices) > 0:
            val_sample_indices = np.array(val_sample_indices[:6])  # Max 6 samples

            X_val_samples = X_val[val_sample_indices]
            cam_val = scorecam(score_function, X_val_samples, penultimate_layer='last_conv')

            n_val_samples = len(val_sample_indices)
            n_rows_val = (n_val_samples + 2) // 3

            fig, axes = plt.subplots(n_rows_val, 3, figsize=(15, 5*n_rows_val))
            if n_rows_val == 1:
                axes = axes if isinstance(axes, np.ndarray) else np.array([axes])
            else:
                axes = axes.ravel()

            for i, idx in enumerate(val_sample_indices):
                ax = axes[i]

                # Original image
                img = X_val[idx]

                # Overlay CAM
                heatmap = cam_val[i]
                heatmap = np.uint8(255 * heatmap)
                heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
                heatmap = cv2.resize(heatmap, (SIZE, SIZE))

                # Superimpose
                superimposed = cv2.addWeighted(
                    (img * 255).astype(np.uint8), 0.6,
                    heatmap, 0.4, 0
                )

                ax.imshow(superimposed)
                ax.axis('off')

                # Validation predictions
                true_label = class_names[y_val[idx]]
                pred_label = class_names[val_pred[idx]]
                pred_prob = val_pred_probs[idx, val_pred[idx]]
                status = "✓" if y_val[idx] == val_pred[idx] else "✗"

                ax.set_title(
                    f"{status} True: {true_label} | Pred: {pred_label}\n"
                    f"Confidence: {pred_prob:.2f}",
                    fontsize=10
                )

            # Hide unused subplots
            for i in range(len(val_sample_indices), len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: Validation Samples", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'cnn_scorecam_validation.png'), dpi=300, bbox_inches='tight')
            plt.show()
        else:
            print("No validation samples available for Score-CAM")

        # Option 3: Per-Class Analysis (show samples from each class)
        print("\n--- Per-Class Analysis ---")

        # Get correctly classified samples from each class
        per_class_samples = []
        for class_idx in range(NUM_CLASSES):
            class_test_indices = np.where(y_test == class_idx)[0]
            class_correct = [idx for idx in class_test_indices if y_test_pred[idx] == class_idx]

            # Take up to 2 samples per class
            if len(class_correct) >= 2:
                per_class_samples.extend(class_correct[:2])
            elif len(class_correct) == 1:
                per_class_samples.append(class_correct[0])

        if len(per_class_samples) >= 3:
            per_class_samples = per_class_samples[:9]  # Max 9 samples (3x3 grid)

            X_class_samples = X_test[per_class_samples]
            cam_class = scorecam(score_function, X_class_samples, penultimate_layer='last_conv')

            n_samples = len(per_class_samples)
            n_rows = (n_samples + 2) // 3

            fig, axes = plt.subplots(n_rows, 3, figsize=(15, 5*n_rows))
            if n_rows == 1:
                axes = axes if isinstance(axes, np.ndarray) else np.array([axes])
            else:
                axes = axes.ravel()

            for i, idx in enumerate(per_class_samples):
                ax = axes[i]

                # Original image
                img = X_test[idx]

                # Overlay CAM
                heatmap = cam_class[i]
                heatmap = np.uint8(255 * heatmap)
                heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
                heatmap = cv2.resize(heatmap, (SIZE, SIZE))

                # Superimpose
                superimposed = cv2.addWeighted(
                    (img * 255).astype(np.uint8), 0.6,
                    heatmap, 0.4, 0
                )

                ax.imshow(superimposed)
                ax.axis('off')

                true_label = class_names[y_test[idx]]
                pred_class = y_test_pred[idx]
                confidence = y_test_pred_probs[idx, pred_class]

                ax.set_title(
                    f"✓ {true_label}\n"
                    f"Confidence: {confidence:.2f}",
                    fontsize=11
                )

            # Hide unused subplots
            for i in range(len(per_class_samples), len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: Per-Class Attention Patterns",
                        fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'cnn_scorecam_per_class.png'), dpi=300, bbox_inches='tight')
            plt.show()

        # Option 4: High vs Low Confidence Comparison
        print("\n--- Confidence Comparison ---")

        # Get highest and lowest confidence samples (that are correctly classified)
        correct_indices = np.where(y_test_pred == y_test)[0]

        # Get max probability for each correct prediction
        correct_confidences = y_test_pred_probs[correct_indices].max(axis=1)

        # Sort by confidence
        sorted_correct_idx = correct_indices[np.argsort(correct_confidences)]

        low_conf_samples = sorted_correct_idx[:3]  # 3 lowest confidence
        high_conf_samples = sorted_correct_idx[-3:]  # 3 highest confidence

        confidence_samples = np.concatenate([low_conf_samples, high_conf_samples])

        if len(confidence_samples) >= 4:
            X_conf_samples = X_test[confidence_samples]
            cam_conf = scorecam(score_function, X_conf_samples, penultimate_layer='last_conv')

            fig, axes = plt.subplots(2, 3, figsize=(15, 10))
            axes = axes.ravel()

            for i, idx in enumerate(confidence_samples):
                ax = axes[i]

                # Original image
                img = X_test[idx]

                # Overlay CAM
                heatmap = cam_conf[i]
                heatmap = np.uint8(255 * heatmap)
                heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
                heatmap = cv2.resize(heatmap, (SIZE, SIZE))

                # Superimpose
                superimposed = cv2.addWeighted(
                    (img * 255).astype(np.uint8), 0.6,
                    heatmap, 0.4, 0
                )

                ax.imshow(superimposed)
                ax.axis('off')

                true_label = class_names[y_test[idx]]
                pred_class = y_test_pred[idx]
                confidence = y_test_pred_probs[idx, pred_class]

                conf_level = "LOW" if i < 3 else "HIGH"

                ax.set_title(
                    f"✓ {true_label} ({conf_level} CONF)\n"
                    f"Confidence: {confidence:.2f}",
                    fontsize=10
                )

            plt.suptitle("Score-CAM: Low Confidence (Top) vs High Confidence (Bottom)",
                        fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'cnn_scorecam_confidence.png'), dpi=300, bbox_inches='tight')
            plt.show()

        print("✓ Additional Score-CAM visualizations complete!")

    except Exception as e:
        print(f"⚠ Additional Score-CAM failed: {str(e)}")
        import traceback
        print(traceback.format_exc())

else:
    print("⏭ Skipping additional Score-CAM (RUN_SCORECAM is False)")

print("\n" + "="*60)
print("✅ ALL VISUALIZATIONS COMPLETE")
print("="*60)
