# -*- coding: utf-8 -*-
"""neu_mobile_binary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bI5kKH1HzPCR-tVNKocZjQv9ztwnp9rR

Transfer-learning MobileNetV2 pipeline for binary frost vs non-frost
classification, with detailed error analysis and custom Score-CAM explainability.

This cell:
1. Sets seeds, mounts Google Drive, loads and normalizes the frost/non-frost
   image dataset, and creates a stratified train/validation/test split (with
   the test split saved for reuse), then augments the training data and
   computes class weights to mitigate imbalance.
2. Defines a MobileNetV2-based model (Imagenet-initialized backbone with
   partially frozen layers) followed by L2-regularized dense blocks and
   dropout, and runs stratified K-fold cross-validation to log per-fold
   performance, training curves, and confusion matrices to disk.
3. Trains a final MobileNetV2 model on the full augmented training set using
   checkpointing, learning-rate scheduling, and CSV logging, evaluates it on
   the held-out test set, and summarizes accuracy, precision, recall, F1, and
   misclassification counts, along with saved plots of learning curves and
   the final confusion matrix.
4. Visualizes misclassified test images (with true label, predicted label, and
   confidence), stores a detailed CSV of false positives/negatives, implements
   a custom Score-CAM class tailored to MobileNetV2 internals, and generates
   triplet panels (original, heatmap, overlay) for representative correct and
   misclassified samples to highlight the image regions driving model decisions.
"""

import cv2
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (classification_report, confusion_matrix, ConfusionMatrixDisplay,
                             accuracy_score, precision_score, recall_score, f1_score)
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Input, GlobalAveragePooling2D,
                                     Dense, BatchNormalization, Dropout)
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, CSVLogger
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from sklearn.utils import class_weight
from google.colab import drive
import pickle

# ============================================================================
# SETUP & REPRODUCIBILITY
# ============================================================================
sns.set_style("darkgrid")
sns.set_palette("colorblind")

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)
os.environ["TF_DETERMINISTIC_OPS"] = "1"

# Mount Drive
drive.mount('/content/drive')

# Paths
image_directory = '/content/drive/My Drive/frost/frost_non_frost'
non_frost_images_path = os.path.join(image_directory, 'non_frost')
frost_images_path = os.path.join(image_directory, 'frost')
save_dir = '/content/drive/My Drive/frost/models_saved'
os.makedirs(save_dir, exist_ok=True)

# Constants
SIZE = 512  # MobileNetV2 standard input size (changed from 512)
BATCH_SIZE = 32
EPOCHS = 25
AUGMENTATION_FACTOR = 4
N_FOLDS = 5

# ============================================================================
# DATA LOADING
# ============================================================================
print("Loading images...")
dataset = []
labels = []

# Load non-frost images (label 0)
for image_name in os.listdir(non_frost_images_path):
    if image_name.lower().endswith(('tif', 'png', 'jpg', 'jpeg')):
        image_path = os.path.join(non_frost_images_path, image_name)
        image = cv2.imread(image_path)
        if image is None:
            continue
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (SIZE, SIZE))
        dataset.append(image)
        labels.append(0)

# Load frost images (label 1)
for image_name in os.listdir(frost_images_path):
    if image_name.lower().endswith(('tif', 'png', 'jpg', 'jpeg')):
        image_path = os.path.join(frost_images_path, image_name)
        image = cv2.imread(image_path)
        if image is None:
            continue
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (SIZE, SIZE))
        dataset.append(image)
        labels.append(1)

# Normalize to [0, 1]
dataset = np.array(dataset, dtype=np.float32) / 255.0
labels = np.array(labels)

print(f"Total samples: {len(dataset)}")
print(f"Class distribution: {np.unique(labels, return_counts=True)}")

# ============================================================================
# DATA SPLITTING (CONSISTENT ACROSS ALL MODELS)
# ============================================================================
print("\nCreating train/val/test splits...")
X_train, X_temp, y_train, y_temp = train_test_split(
    dataset, labels, test_size=0.3, random_state=SEED, stratify=labels
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=SEED, stratify=y_temp
)

print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

# Save splits for consistency across models
np.save(os.path.join(save_dir, 'X_test.npy'), X_test)
np.save(os.path.join(save_dir, 'y_test.npy'), y_test)

# ============================================================================
# DATA AUGMENTATION
# ============================================================================
print("\nAugmenting training data...")
train_datagen = ImageDataGenerator(
    rotation_range=30,
    horizontal_flip=True,
    fill_mode='reflect'
)

def augment_data(X, y, factor=AUGMENTATION_FACTOR):
    aug_images = []
    aug_labels = []
    for i in range(len(X)):
        image = np.expand_dims(X[i], axis=0)
        label = y[i]
        aug_iter = train_datagen.flow(image, batch_size=1)
        for _ in range(factor):
            aug_images.append(next(aug_iter)[0])
            aug_labels.append(label)

    X_aug = np.concatenate([X, np.array(aug_images)], axis=0).astype(np.float32)
    y_aug = np.concatenate([y, np.array(aug_labels)], axis=0).astype(int)
    return X_aug, y_aug

X_train_aug, y_train_aug = augment_data(X_train, y_train)
print(f"Augmented training data: {X_train_aug.shape}")

# Class weights
class_weights = class_weight.compute_class_weight(
    'balanced',
    classes=np.unique(y_train_aug),
    y=y_train_aug
)
class_weights = dict(enumerate(class_weights))
print(f"Class weights: {class_weights}")

# ============================================================================
# MOBILENETV2 MODEL DEFINITION
# ============================================================================
def create_mobilenet_model(input_shape=(SIZE, SIZE, 3)):
    # Base MobileNetV2
    base_model = MobileNetV2(include_top=False, weights='imagenet', input_shape=input_shape)

    # Freeze all but the last 10 layers
    for layer in base_model.layers[:-15]:
        layer.trainable = False
    for layer in base_model.layers[-15:]:
        layer.trainable = True

    # Functional graph
    inputs = Input(shape=input_shape)
    x = base_model(inputs, training=False)
    x = GlobalAveragePooling2D()(x)

    x = Dense(64, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.4)(x)

    x = Dense(32, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.3)(x)

    x = Dense(8, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.2)(x)

    outputs = Dense(1, activation='sigmoid', kernel_regularizer=l2(0.001))(x)

    model = Model(inputs, outputs)

    model.compile(
        optimizer=Adam(learning_rate=2e-5),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    return model

# ============================================================================
# PHASE 1: CROSS-VALIDATION
# ============================================================================
print("\n" + "="*60)
print("PHASE 1: CROSS-VALIDATION")
print("="*60)

skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
cv_results = []

for fold_idx, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train), start=1):
    print(f"\n--- Fold {fold_idx}/{N_FOLDS} ---")

    # Split fold data
    X_fold_train = X_train[train_idx]
    y_fold_train = y_train[train_idx]
    X_fold_val = X_train[val_idx]
    y_fold_val = y_train[val_idx]

    # Augment fold training data
    X_fold_aug, y_fold_aug = augment_data(X_fold_train, y_fold_train)

    # Fold class weights
    fold_cw = class_weight.compute_class_weight(
        'balanced', classes=np.unique(y_fold_aug), y=y_fold_aug
    )
    fold_cw = dict(enumerate(fold_cw))

    # Create and train model
    model = create_mobilenet_model()
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-7, verbose=0)

    history = model.fit(
        X_fold_aug, y_fold_aug,
        validation_data=(X_fold_val, y_fold_val),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        shuffle=True,
        class_weight=fold_cw,
        callbacks=[reduce_lr],
        verbose=1
    )

    # Get predictions
    y_pred_probs = model.predict(X_fold_val, batch_size=32, verbose=0)
    y_pred = (y_pred_probs > 0.5).astype(int).flatten()

    # Calculate metrics
    report = classification_report(y_fold_val, y_pred, output_dict=True, zero_division=0)

    # Print classification report
    print(f"\nClassification Report - Fold {fold_idx}:")
    print(classification_report(y_fold_val, y_pred, target_names=['Non-Frost', 'Frost'], zero_division=0))

    # PLOT 1: Training curves
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy', linewidth=2)
    plt.plot(history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
    plt.title(f'Accuracy - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss', linewidth=2)
    plt.plot(history.history['val_loss'], label='Val Loss', linewidth=2)
    plt.title(f'Loss - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    plt.suptitle(f'Training Curves - Fold {fold_idx}/{N_FOLDS}', fontsize=16)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'mobilenet_fold_{fold_idx}_curves.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # PLOT 2: Confusion matrix
    plt.figure(figsize=(8, 6))
    cm = confusion_matrix(y_fold_val, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Non-Frost', 'Frost'])
    disp.plot(cmap='Blues')
    plt.title(f'Confusion Matrix - Fold {fold_idx}/{N_FOLDS}', fontsize=14, fontweight='bold')
    plt.grid(False)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'mobilenet_fold_{fold_idx}_confusion.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # Save fold results
    fold_result = {
        'Fold': fold_idx,
        'Accuracy': report['accuracy'],
        'Precision_Frost': report.get('1', {}).get('precision', 0),
        'Recall_Frost': report.get('1', {}).get('recall', 0),
        'F1_Frost': report.get('1', {}).get('f1-score', 0),
        'Precision_Non_Frost': report.get('0', {}).get('precision', 0),
        'Recall_Non_Frost': report.get('0', {}).get('recall', 0),
        'F1_Non_Frost': report.get('0', {}).get('f1-score', 0),
        'Loss': history.history['val_loss'][-1]
    }
    cv_results.append(fold_result)

    print(f"Accuracy: {fold_result['Accuracy']:.4f}, F1 (Frost): {fold_result['F1_Frost']:.4f}")

    # Clear memory
    del model, history, y_pred_probs, y_pred
    tf.keras.backend.clear_session()

# Save CV results
cv_df = pd.DataFrame(cv_results)
cv_df.to_csv(os.path.join(save_dir, 'mobilenet_cv_results.csv'), index=False)

print("\n" + "="*60)
print("CROSS-VALIDATION SUMMARY")
print("="*60)
print(cv_df.describe())

# ============================================================================
# PHASE 2: FINAL MODEL TRAINING
# ============================================================================
print("\n" + "="*60)
print("PHASE 2: FINAL MODEL TRAINING")
print("="*60)

# Train final model on full augmented training data
final_model = create_mobilenet_model()

checkpoint_cb = ModelCheckpoint(
    filepath=os.path.join(save_dir, 'mobilenet_best_model.h5'),
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-7, verbose=1)
csv_logger = CSVLogger(os.path.join(save_dir, 'mobilenet_training_log.csv'))

final_history = final_model.fit(
    X_train_aug, y_train_aug,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    class_weight=class_weights,
    callbacks=[checkpoint_cb, reduce_lr, csv_logger],
    verbose=1
)

# ============================================================================
# FINAL TEST SET EVALUATION
# ============================================================================
print("\n" + "="*60)
print("TEST SET EVALUATION")
print("="*60)

# Standard predictions on test set
y_test_pred_probs = final_model.predict(X_test, batch_size=32, verbose=0).flatten()
y_test_pred = (y_test_pred_probs > 0.5).astype(int)

# Classification report
print("\nClassification Report - Test Set:")
print(classification_report(y_test, y_test_pred, target_names=['Non-Frost', 'Frost']))

# PLOT 1: Training curves for final model
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(final_history.history['accuracy'], label='Train Accuracy', linewidth=2)
plt.plot(final_history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
plt.title('Model Accuracy - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(final_history.history['loss'], label='Train Loss', linewidth=2)
plt.plot(final_history.history['val_loss'], label='Val Loss', linewidth=2)
plt.title('Model Loss - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.suptitle('Final Model Training Curves', fontsize=16)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'mobilenet_final_training_curves.png'), dpi=300, bbox_inches='tight')
plt.show()

# PLOT 2: Confusion Matrix for test set
plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_test_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Non-Frost', 'Frost'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix - Test Set", fontsize=14, fontweight='bold')
plt.grid(False)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'mobilenet_test_confusion_matrix.png'), dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# SAVE FINAL RESULTS
# ============================================================================
# Calculate misclassifications
misclassified_idx = np.where(y_test_pred != y_test)[0]

final_results = {
    'Model': 'MobileNetV2',
    'Test_Accuracy': accuracy_score(y_test, y_test_pred),
    'Test_Precision': precision_score(y_test, y_test_pred),
    'Test_Recall': recall_score(y_test, y_test_pred),
    'Test_F1': f1_score(y_test, y_test_pred),
    'CV_Accuracy_Mean': cv_df['Accuracy'].mean(),
    'CV_Accuracy_Std': cv_df['Accuracy'].std(),
    'Misclassifications': len(misclassified_idx)
}

pd.DataFrame([final_results]).to_csv(
    os.path.join(save_dir, 'mobilenet_final_results.csv'), index=False
)

print("\n" + "="*60)
print("FINAL RESULTS")
print("="*60)
for key, value in final_results.items():
    print(f"{key}: {value}")

print("\n✅ All results saved to:", save_dir)

# ============================================================================
# MISCLASSIFIED IMAGES VISUALIZATION
# ============================================================================
print("\n" + "="*60)
print("VISUALIZING MISCLASSIFIED IMAGES")
print("="*60)

# Find misclassified samples
misclassified_idx = np.where(y_test_pred != y_test)[0]
print(f"Number of misclassified images: {len(misclassified_idx)}")

if len(misclassified_idx) > 0:
    # Visualize up to 20 misclassified images
    num_to_show = min(20, len(misclassified_idx))

    # Create figure with subplots
    fig, axes = plt.subplots(4, 5, figsize=(20, 16))
    axes = axes.flatten()

    for i, idx in enumerate(misclassified_idx[:num_to_show]):
        img = X_test[idx]
        true_label = 'Frost' if y_test[idx] == 1 else 'Non-Frost'
        pred_label = 'Frost' if y_test_pred[idx] == 1 else 'Non-Frost'
        confidence = y_test_pred_probs[idx] if y_test_pred[idx] == 1 else (1 - y_test_pred_probs[idx])

        axes[i].imshow(img)
        axes[i].set_title(f'True: {true_label}\nPred: {pred_label}\nConf: {confidence:.2%}',
                         fontsize=10, fontweight='bold')
        axes[i].axis('off')

    # Hide unused subplots
    for i in range(num_to_show, len(axes)):
        axes[i].axis('off')

    plt.suptitle('Misclassified Images on Test Set', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'mobilenet_misclassified_images.png'), dpi=300, bbox_inches='tight')
    plt.show()

    # Save detailed misclassification info
    misclass_info = []
    for i, idx in enumerate(misclassified_idx):
        info_dict = {
            'Sample_Index': int(idx),
            'True_Label': 'Frost' if y_test[idx] == 1 else 'Non-Frost',
            'Predicted_Label': 'Frost' if y_test_pred[idx] == 1 else 'Non-Frost',
            'Confidence': float(y_test_pred_probs[idx]),
            'Error_Type': 'False Positive' if (y_test[idx] == 0 and y_test_pred[idx] == 1) else 'False Negative'
        }

        # Add image path if available
        try:
            if 'paths_test' in locals() or 'paths_test' in globals():
                info_dict['Image_Path'] = os.path.basename(paths_test[idx])
        except:
            pass

        misclass_info.append(info_dict)

    misclass_df = pd.DataFrame(misclass_info)
    misclass_df.to_csv(os.path.join(save_dir, 'mobilenet_misclassifications.csv'), index=False)
    print(f"Saved misclassification details to: {os.path.join(save_dir, 'mobilenet_misclassifications.csv')}")


# ============================================================================
# SCORE-CAM VISUALIZATION
# ============================================================================
# ============================================================================
# SCORE-CAM IMPLEMENTATION
# ============================================================================
print("\n" + "="*60)
print("SCORE-CAM IMPLEMENTATION & VISUALIZATION")
print("="*60)

# Define ScoreCAM class
class ScoreCAM:
    def __init__(self, model, layer_name=None):
        self.model = model
        self.layer_name = layer_name

        # Find the last convolutional layer if layer_name is not specified
        if self.layer_name is None:
            # For MobileNetV2 models, look for the base model layers
            mobilenet_layer = None
            for layer in self.model.layers:
                if 'mobilenet' in layer.name.lower():
                    mobilenet_layer = layer
                    break

            if mobilenet_layer is not None:
                # Look for good layers in MobileNetV2
                for sublayer in reversed(mobilenet_layer.layers):
                    if ('block_16' in sublayer.name and 'project' in sublayer.name) or \
                       ('block_15' in sublayer.name and 'project' in sublayer.name) or \
                       ('block_14' in sublayer.name and 'project' in sublayer.name):
                        self.layer_name = sublayer.name
                        self.base_model = mobilenet_layer
                        break

                # If not found, try any conv layer in the last few blocks
                if self.layer_name is None:
                    for sublayer in reversed(mobilenet_layer.layers):
                        if 'conv' in sublayer.name.lower() or 'project' in sublayer.name.lower():
                            if hasattr(sublayer, 'output_shape') and len(sublayer.output_shape) == 4:
                                self.layer_name = sublayer.name
                                self.base_model = mobilenet_layer
                                break

        if self.layer_name is None:
            # Manual fallback - use a known good layer name
            self.layer_name = 'block_13_project'
            mobilenet_layer = None
            for layer in self.model.layers:
                if 'mobilenet' in layer.name.lower():
                    mobilenet_layer = layer
                    break
            self.base_model = mobilenet_layer

        # Create a model that outputs feature maps from the specified layer
        try:
            if hasattr(self, 'base_model') and self.base_model is not None:
                target_layer = self.base_model.get_layer(self.layer_name)
                self.feature_model = tf.keras.models.Model(
                    inputs=self.base_model.input,
                    outputs=target_layer.output
                )
            else:
                self.feature_model = tf.keras.models.Model(
                    inputs=self.model.input,
                    outputs=self.model.get_layer(self.layer_name).output
                )
        except Exception as e:
            # Try alternative layers
            alternative_layers = ['block_15_project', 'block_14_project', 'block_16_project', 'Conv_1']
            for alt_layer in alternative_layers:
                try:
                    if hasattr(self, 'base_model') and self.base_model is not None:
                        target_layer = self.base_model.get_layer(alt_layer)
                        self.feature_model = tf.keras.models.Model(
                            inputs=self.base_model.input,
                            outputs=target_layer.output
                        )
                        self.layer_name = alt_layer
                        break
                except:
                    continue

        print(f"Score-CAM using layer: {self.layer_name}")

    def generate_cam(self, input_image):
        if len(input_image.shape) == 3:
            input_image = np.expand_dims(input_image, axis=0)

        # Get feature maps
        feature_maps = self.feature_model.predict(input_image, verbose=0)

        # Get original prediction score
        original_score = self.model.predict(input_image, verbose=0)[0]
        if len(original_score.shape) > 0 and original_score.shape[0] > 0:
            original_score = original_score[0]

        # Initialize weights for each feature map
        weights = []

        # Sample every nth feature map to speed up computation
        n_features = feature_maps.shape[-1]
        step = max(1, n_features // 50)  # Use at most 50 feature maps

        for i in range(0, n_features, step):
            # Extract single feature map
            feature_map = feature_maps[0, :, :, i]

            # Resize feature map to input image size
            resized_feature_map = cv2.resize(feature_map, (input_image.shape[2], input_image.shape[1]))

            # Normalize feature map to [0, 1]
            if resized_feature_map.max() > resized_feature_map.min():
                normalized_feature_map = (resized_feature_map - resized_feature_map.min()) / \
                                       (resized_feature_map.max() - resized_feature_map.min())
            else:
                normalized_feature_map = np.zeros_like(resized_feature_map)

            # Create masked image
            masked_image = input_image[0] * np.expand_dims(normalized_feature_map, axis=-1)
            masked_image = np.expand_dims(masked_image, axis=0)

            # Get prediction score for masked image
            try:
                masked_score = self.model.predict(masked_image, verbose=0)[0]
                if len(masked_score.shape) > 0 and masked_score.shape[0] > 0:
                    masked_score = masked_score[0]
                weights.append(masked_score)
            except:
                weights.append(0.0)

        weights = np.array(weights)

        # Generate weighted combination of feature maps
        cam = np.zeros((feature_maps.shape[1], feature_maps.shape[2]), dtype=np.float32)

        for idx, i in enumerate(range(0, n_features, step)):
            cam += weights[idx] * feature_maps[0, :, :, i]

        # Apply ReLU and normalize CAM
        cam = np.maximum(cam, 0)
        if cam.max() > cam.min():
            cam = (cam - cam.min()) / (cam.max() - cam.min())

        return cam, original_score

def overlay_heatmap_scorecam(img, heatmap, alpha=0.4, colormap=cv2.COLORMAP_JET):
    """
    Overlay heatmap on image.

    Args:
        img: Original image (H, W, 3) in range [0, 1]
        heatmap: Heatmap (H, W) in range [0, 1]
        alpha: Transparency of heatmap
        colormap: OpenCV colormap

    Returns:
        Overlayed image
    """
    # Convert heatmap to RGB
    heatmap_uint8 = np.uint8(255 * heatmap)
    heatmap_colored = cv2.applyColorMap(heatmap_uint8, colormap)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)
    heatmap_colored = heatmap_colored.astype(np.float32) / 255.0

    # Convert image to proper format
    img_display = img.copy()

    # Overlay
    overlayed = heatmap_colored * alpha + img_display * (1 - alpha)
    overlayed = np.clip(overlayed, 0, 1)

    return overlayed

# Initialize Score-CAM with the final model
try:
    score_cam = ScoreCAM(final_model)
    print("Score-CAM initialized successfully!")
except Exception as e:
    print(f"Error initializing Score-CAM: {e}")
    score_cam = None

# Select samples for Score-CAM visualization
samples_to_visualize = []

# Correctly classified frost images
correct_frost = np.where((y_test == 1) & (y_test_pred == 1))[0]
if len(correct_frost) > 0:
    samples_to_visualize.extend(correct_frost[:2])

# Correctly classified non-frost images
correct_non_frost = np.where((y_test == 0) & (y_test_pred == 0))[0]
if len(correct_non_frost) > 0:
    samples_to_visualize.extend(correct_non_frost[:2])

# Misclassified images
if len(misclassified_idx) > 0:
    samples_to_visualize.extend(misclassified_idx[:4])

# Generate Score-CAM for selected samples
if score_cam is not None and len(samples_to_visualize) > 0:
    print(f"Generating Score-CAM for {len(samples_to_visualize)} samples...")

    num_samples = len(samples_to_visualize)
    fig, axes = plt.subplots(num_samples, 3, figsize=(15, 5*num_samples))
    if num_samples == 1:
        axes = axes.reshape(1, -1)

    for i, idx in enumerate(samples_to_visualize):
        img = X_test[idx]
        true_label = 'Frost' if y_test[idx] == 1 else 'Non-Frost'
        pred_label = 'Frost' if y_test_pred[idx] == 1 else 'Non-Frost'
        confidence = y_test_pred_probs[idx]

        try:
            # Generate Score-CAM
            cam, cam_confidence = score_cam.generate_cam(img)

            # Resize CAM to match image size
            cam_resized = cv2.resize(cam, (SIZE, SIZE))

            # Create overlay
            overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)

        except Exception as e:
            print(f"Error generating Score-CAM for sample {idx}: {str(e)}")
            cam_resized = np.zeros((SIZE, SIZE))
            overlay = img

        # Plot original image
        axes[i, 0].imshow(img)
        axes[i, 0].set_title(f'Original\nTrue: {true_label}\nPred: {pred_label} ({confidence:.2%})',
                            fontsize=10, fontweight='bold')
        axes[i, 0].axis('off')

        # Plot heatmap
        im = axes[i, 1].imshow(cam_resized, cmap='jet')
        axes[i, 1].set_title('Score-CAM Heatmap', fontsize=10, fontweight='bold')
        axes[i, 1].axis('off')
        plt.colorbar(im, ax=axes[i, 1], fraction=0.046, pad=0.04)

        # Plot overlay
        axes[i, 2].imshow(overlay)
        axes[i, 2].set_title('Overlay', fontsize=10, fontweight='bold')
        axes[i, 2].axis('off')

    plt.suptitle('Score-CAM Visualizations', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'mobilenet_scorecam_visualization.png'), dpi=300, bbox_inches='tight')
    plt.show()

    print("Score-CAM visualization complete!")
    print(f"Score-CAM results saved to: {os.path.join(save_dir, 'mobilenet_scorecam_visualization.png')}")
else:
    print("Score-CAM visualization skipped (no samples or Score-CAM initialization failed)")

print("\n" + "="*60)
print("ALL PROCESSING COMPLETE!")
print("="*60)

# ============================================================================
# SAVE FINAL RESULTS
# ============================================================================
final_results = {
    'Model': 'MobileNetV2',
    'Test_Accuracy': accuracy_score(y_test, y_test_pred),
    'Test_Precision': precision_score(y_test, y_test_pred),
    'Test_Recall': recall_score(y_test, y_test_pred),
    'Test_F1': f1_score(y_test, y_test_pred),
    'CV_Accuracy_Mean': cv_df['Accuracy'].mean(),
    'CV_Accuracy_Std': cv_df['Accuracy'].std(),
    'Misclassifications': len(misclassified_idx),
    'False_Positives': len(np.where((y_test == 0) & (y_test_pred == 1))[0]),
    'False_Negatives': len(np.where((y_test == 1) & (y_test_pred == 0))[0])
}

pd.DataFrame([final_results]).to_csv(
    os.path.join(save_dir, 'mobilenet_final_results.csv'), index=False
)

print("\n" + "="*60)
print("FINAL RESULTS")
print("="*60)
for key, value in final_results.items():
    print(f"{key}: {value}")

print("\n✅ All results saved to:", save_dir)

"""Extended Score-CAM analysis for the MobileNetV2 frost vs non-frost classifier,
focusing on confidence, decision boundary behavior, and error types.

This cell:
1. Reuses the trained MobileNetV2 model, test/validation predictions, and a
   custom Score-CAM implementation to generate additional, post-hoc
   visualizations without retraining, after verifying that all required
   variables are available from the main training script.
2. Examines high- vs low-confidence correct predictions with Score-CAM
   overlays, highlights borderline cases near the 0.5 decision threshold,
   and contrasts false positives with false negatives to assess how spatial
   attention differs across error types.
3. Builds a diverse comparison grid (correct frost/non-frost, FPs, FNs, and
   borderline examples), saves all corresponding Score-CAM panels to disk,
   and reports summary statistics on confidence regimes, misclassification
   counts, and borderline frequency, providing a rich qualitative complement
   to the quantitative performance metrics.
"""

# ============================================================================
# ADDITIONAL SCORE-CAM VISUALIZATIONS - EXTENDED ANALYSIS
# Run this cell separately after the main training code
# ============================================================================
print("\n" + "="*80)
print("EXTENDED SCORE-CAM ANALYSIS")
print("="*80)

# Check if required variables exist
try:
    _ = final_model, X_test, y_test, y_test_pred, y_test_pred_probs, X_val, y_val
    print("All required variables found. Proceeding with analysis...")
except NameError as e:
    print(f"Error: Missing required variable - {e}")
    print("Please run the main training code first!")
    raise

# Define class names
class_names = ['Non-Frost', 'Frost']

# Initialize Score-CAM if not already done
if 'score_cam' not in locals() and 'score_cam' not in globals():
    print("\nInitializing Score-CAM...")
    try:
        score_cam = ScoreCAM(final_model)
        print("Score-CAM initialized successfully!")
    except Exception as e:
        print(f"Error initializing Score-CAM: {e}")
        score_cam = None

# ============================================================================
# VISUALIZATION 1: CONFIDENCE-BASED ANALYSIS
# ============================================================================
print("\n" + "-"*80)
print("1. HIGH VS LOW CONFIDENCE PREDICTIONS")
print("-"*80)

if score_cam is not None:
    try:
        # Get high and low confidence samples
        high_conf_frost = np.where((y_test_pred == 1) & (y_test_pred_probs > 0.9))[0]
        low_conf_frost = np.where((y_test_pred == 1) & (y_test_pred_probs < 0.7))[0]
        high_conf_nonfrost = np.where((y_test_pred == 0) & (y_test_pred_probs < 0.1))[0]
        low_conf_nonfrost = np.where((y_test_pred == 0) & (y_test_pred_probs > 0.3))[0]

        selected_indices = []
        if len(high_conf_frost) > 0: selected_indices.extend(high_conf_frost[:2])
        if len(low_conf_frost) > 0: selected_indices.extend(low_conf_frost[:2])
        if len(high_conf_nonfrost) > 0: selected_indices.extend(high_conf_nonfrost[:2])
        if len(low_conf_nonfrost) > 0: selected_indices.extend(low_conf_nonfrost[:2])

        if len(selected_indices) > 0:
            fig, axes = plt.subplots(2, 4, figsize=(20, 10))
            axes = axes.ravel()

            for i, idx in enumerate(selected_indices[:8]):
                img = X_test[idx]

                try:
                    cam, cam_confidence = score_cam.generate_cam(img)
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap(img, cam_resized, alpha=0.4)
                except:
                    overlay = img

                axes[i].imshow(overlay)
                axes[i].axis('off')

                pred_prob = y_test_pred_probs[idx]
                conf_type = "HIGH" if (pred_prob > 0.9 or pred_prob < 0.1) else "LOW"
                status = "✓" if y_test[idx] == y_test_pred[idx] else "✗"

                axes[i].set_title(
                    f"{status} {conf_type} Confidence\n"
                    f"True: {class_names[y_test[idx]]} | Pred: {class_names[y_test_pred[idx]]}\n"
                    f"Prob: {pred_prob:.3f}",
                    fontsize=9, fontweight='bold'
                )

            for i in range(len(selected_indices), 8):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: High vs Low Confidence Predictions", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'mobilenet_scorecam_confidence.png'), dpi=300, bbox_inches='tight')
            plt.show()
            print("Confidence analysis complete!")
        else:
            print("No samples found matching confidence criteria")

    except Exception as e:
        print(f"Error in confidence analysis: {e}")

# ============================================================================
# VISUALIZATION 2: BORDERLINE CASES (AROUND 0.5 THRESHOLD)
# ============================================================================
print("\n" + "-"*80)
print("2. BORDERLINE PREDICTIONS (Near 0.5 threshold)")
print("-"*80)

if score_cam is not None:
    try:
        # Find predictions near the decision boundary
        borderline_indices = np.where(np.abs(y_test_pred_probs - 0.5) < 0.15)[0]

        if len(borderline_indices) > 0:
            sample_indices = borderline_indices[:8]

            fig, axes = plt.subplots(2, 4, figsize=(20, 10))
            axes = axes.ravel()

            for i, idx in enumerate(sample_indices):
                img = X_test[idx]

                try:
                    cam, cam_confidence = score_cam.generate_cam(img)
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap(img, cam_resized, alpha=0.4)
                except:
                    overlay = img

                axes[i].imshow(overlay)
                axes[i].axis('off')

                status = "✓" if y_test[idx] == y_test_pred[idx] else "✗"
                axes[i].set_title(
                    f"{status} True: {class_names[y_test[idx]]} | Pred: {class_names[y_test_pred[idx]]}\n"
                    f"Prob: {y_test_pred_probs[idx]:.3f} (Near threshold)",
                    fontsize=9, fontweight='bold'
                )

            for i in range(len(sample_indices), 8):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: Borderline Predictions (Uncertain Cases)", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'mobilenet_scorecam_borderline.png'), dpi=300, bbox_inches='tight')
            plt.show()
            print(f"Found {len(borderline_indices)} borderline cases")
        else:
            print("No borderline cases found")

    except Exception as e:
        print(f"Error in borderline analysis: {e}")

# ============================================================================
# VISUALIZATION 3: FALSE POSITIVES VS FALSE NEGATIVES
# ============================================================================
print("\n" + "-"*80)
print("3. DETAILED MISCLASSIFICATION ANALYSIS")
print("-"*80)

if score_cam is not None:
    try:
        # Get false positives and false negatives
        false_positives = np.where((y_test == 0) & (y_test_pred == 1))[0]
        false_negatives = np.where((y_test == 1) & (y_test_pred == 0))[0]

        print(f"False Positives: {len(false_positives)}")
        print(f"False Negatives: {len(false_negatives)}")

        if len(false_positives) > 0 or len(false_negatives) > 0:
            # Select up to 4 of each type
            fp_samples = false_positives[:4]
            fn_samples = false_negatives[:4]

            n_fp = len(fp_samples)
            n_fn = len(fn_samples)
            n_total = n_fp + n_fn

            if n_total > 0:
                n_cols = 4
                n_rows = (n_total + n_cols - 1) // n_cols

                fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 5*n_rows))
                if n_rows == 1:
                    axes = np.array([axes]) if n_cols == 1 else axes
                axes = axes.ravel() if n_rows > 1 or n_cols > 1 else [axes]

                plot_idx = 0

                # Plot false positives
                for idx in fp_samples:
                    img = X_test[idx]

                    try:
                        cam, cam_confidence = score_cam.generate_cam(img)
                        cam_resized = cv2.resize(cam, (SIZE, SIZE))
                        overlay = overlay_heatmap(img, cam_resized, alpha=0.4)
                    except:
                        overlay = img

                    axes[plot_idx].imshow(overlay)
                    axes[plot_idx].axis('off')
                    axes[plot_idx].set_title(
                        f"FALSE POSITIVE\n"
                        f"True: Non-Frost | Pred: Frost\n"
                        f"Confidence: {y_test_pred_probs[idx]:.3f}",
                        fontsize=10, fontweight='bold', color='red'
                    )
                    plot_idx += 1

                # Plot false negatives
                for idx in fn_samples:
                    img = X_test[idx]

                    try:
                        cam, cam_confidence = score_cam.generate_cam(img)
                        cam_resized = cv2.resize(cam, (SIZE, SIZE))
                        overlay = overlay_heatmap(img, cam_resized, alpha=0.4)
                    except:
                        overlay = img

                    axes[plot_idx].imshow(overlay)
                    axes[plot_idx].axis('off')
                    axes[plot_idx].set_title(
                        f"FALSE NEGATIVE\n"
                        f"True: Frost | Pred: Non-Frost\n"
                        f"Confidence: {y_test_pred_probs[idx]:.3f}",
                        fontsize=10, fontweight='bold', color='orange'
                    )
                    plot_idx += 1

                # Hide unused subplots
                for i in range(plot_idx, len(axes)):
                    axes[i].axis('off')

                plt.suptitle("Score-CAM: Detailed Error Analysis", fontsize=16, fontweight='bold')
                plt.tight_layout()
                plt.savefig(os.path.join(save_dir, 'mobilenet_scorecam_errors_detailed.png'), dpi=300, bbox_inches='tight')
                plt.show()
                print("Error analysis complete!")
        else:
            print("No misclassifications found!")

    except Exception as e:
        print(f"Error in misclassification analysis: {e}")

# ============================================================================
# VISUALIZATION 4: COMPARISON GRID - DIVERSE SAMPLES
# ============================================================================
print("\n" + "-"*80)
print("4. DIVERSE SAMPLE COMPARISON")
print("-"*80)

if score_cam is not None:
    try:
        # Create a diverse set: correct frost, correct non-frost, FP, FN, borderline
        diverse_samples = []

        # 3 correct frost
        correct_frost = np.where((y_test == 1) & (y_test_pred == 1))[0]
        if len(correct_frost) >= 3:
            diverse_samples.extend(correct_frost[:3])

        # 3 correct non-frost
        correct_nonfrost = np.where((y_test == 0) & (y_test_pred == 0))[0]
        if len(correct_nonfrost) >= 3:
            diverse_samples.extend(correct_nonfrost[:3])

        # 2 false positives
        if len(false_positives) >= 2:
            diverse_samples.extend(false_positives[:2])

        # 2 false negatives
        if len(false_negatives) >= 2:
            diverse_samples.extend(false_negatives[:2])

        # 2 borderline
        if len(borderline_indices) >= 2:
            diverse_samples.extend(borderline_indices[:2])

        if len(diverse_samples) > 0:
            n_samples = min(len(diverse_samples), 12)
            diverse_samples = diverse_samples[:n_samples]

            fig, axes = plt.subplots(3, 4, figsize=(20, 15))
            axes = axes.ravel()

            for i, idx in enumerate(diverse_samples):
                img = X_test[idx]

                try:
                    cam, cam_confidence = score_cam.generate_cam(img)
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap(img, cam_resized, alpha=0.4)
                except:
                    overlay = img

                axes[i].imshow(overlay)
                axes[i].axis('off')

                status = "✓" if y_test[idx] == y_test_pred[idx] else "✗"
                axes[i].set_title(
                    f"{status} True: {class_names[y_test[idx]]} | Pred: {class_names[y_test_pred[idx]]}\n"
                    f"Confidence: {y_test_pred_probs[idx]:.3f}",
                    fontsize=9
                )

            for i in range(n_samples, 12):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: Diverse Sample Comparison", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'mobilenet_scorecam_diverse.png'), dpi=300, bbox_inches='tight')
            plt.show()
            print("Diverse sample analysis complete!")

    except Exception as e:
        print(f"Error in diverse sample analysis: {e}")

# ============================================================================
# SUMMARY STATISTICS
# ============================================================================
print("\n" + "="*80)
print("SUMMARY STATISTICS")
print("="*80)

if score_cam is not None:
    try:
        print(f"\nTotal test samples: {len(X_test)}")
        print(f"Correct predictions: {np.sum(y_test == y_test_pred)}")
        print(f"Incorrect predictions: {np.sum(y_test != y_test_pred)}")
        print(f"\nFalse Positives: {len(false_positives)}")
        print(f"False Negatives: {len(false_negatives)}")
        print(f"Borderline cases (prob 0.35-0.65): {len(borderline_indices)}")
        print(f"\nHigh confidence correct (>0.9 or <0.1): {np.sum(((y_test_pred_probs > 0.9) | (y_test_pred_probs < 0.1)) & (y_test == y_test_pred))}")
        print(f"Low confidence correct (0.1-0.9): {np.sum(((y_test_pred_probs >= 0.1) & (y_test_pred_probs <= 0.9)) & (y_test == y_test_pred))}")

        print(f"\nAll Score-CAM visualizations saved to: {save_dir}")

    except Exception as e:
        print(f"Error generating summary: {e}")

print("\n" + "="*80)
print("EXTENDED SCORE-CAM ANALYSIS COMPLETE!")
print("="*80)

