# -*- coding: utf-8 -*-
"""photomicrgraphs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-m7P9u1keP7_O9S3-G-fRmOpVnUexl-

# Full Photomicrograph Classification + Score‑CAM + Metrics
"""

import os
os.environ["TF_FORCE_GPU_ALLOW_GROWTH"] = "true"

import tensorflow as tf
from tensorflow import keras
from google.colab import drive

drive.mount('/content/drive')

!pip install tf-keras-vis

"""Overview
The pipeline:

Loads full‑resolution photomicrographs from a folder structure with frost/ and non_frost/ subdirectories.

Resizes each image to 512×512 and normalizes pixel values for model input.

Runs inference with five pre‑trained models:

Custom CNN,Bayesian CNN (BNN) with Monte Carlo Dropout, MobileNetV2,EfficientNetV2B0,ResNet50

Computes:

Class probabilities (frost vs non_frost) for all models

Epistemic uncertainty (prediction variance) for the BNN

Standard classification metrics (accuracy, precision, recall, F1, confusion matrix)

Generates Score‑CAM heatmaps and overlays to visualize which image regions drive each model’s decision.

Saves all figures and metrics to disk (TIFF/PNG figures + CSV tables).
"""

"""
Full Photomicrograph Classification + Score-CAM + Metrics
==========================================================
Resizes full photomicrographs to 512x512 for inference across all 5
architectures (CNN, BNN, MobileNetV2, EfficientNetV2B0, ResNet50).
Generates Score-CAM heatmaps, BNN uncertainty, and classification metrics.

Expected folder structure:
    full_photomicrographs_test/
    ├── frost/
    │   ├── image_001.tif
    │   └── ...
    └── non_frost/
        ├── image_042.tif
        └── ...

Run in Google Colab with GPU runtime.
"""

# ============================================================================
# 0. IMPORTS & DRIVE
# ============================================================================
import os
import numpy as np
import tensorflow as tf
from tensorflow import keras
from PIL import Image
import matplotlib.pyplot as plt
import cv2
from scipy.ndimage import zoom
from pathlib import Path
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, confusion_matrix)
import seaborn as sns
import pandas as pd

# Suppress decompression bomb warnings for large images
Image.MAX_IMAGE_PIXELS = None

# Mount Google Drive (uncomment if not already mounted)
from google.colab import drive
drive.mount('/content/drive')

# ============================================================================
# 1. CONFIGURATION
# ============================================================================
TARGET_SIZE = (512, 512)
MC_PASSES = 20        # BNN Monte Carlo passes for predictions
SCORECAM_MC = 5       # BNN MC samples for Score-CAM (per activation map)

model_paths = {
    'CNN':              '/content/drive/MyDrive/frost/models_saved/neu_cnn_binary/cnn_best_model.h5',
    'BNN':              '/content/drive/MyDrive/frost/models_saved/neu_bnn_binary/bnn_best_model.h5',
    'MobileNetV2':      '/content/drive/MyDrive/frost/models_saved/neu_mobile_binary/mobilenet_best_model.h5',
    'EfficientNetV2B0': '/content/drive/MyDrive/frost/models_saved/neu_efficientnet_binary/efficientnet_best_model.h5',
    'ResNet50':         '/content/drive/MyDrive/frost/models_saved/neu_resnet_binary/resnet_best_model.h5',
}

input_dir  = '/content/drive/MyDrive/frost/full_photomicrographs_test'
output_dir = '/content/drive/MyDrive/frost/full_photomicrographs_results'
os.makedirs(output_dir, exist_ok=True)

# Plotting style
sns.set_style('darkgrid')
palette = sns.color_palette('colorblind')


# ============================================================================
# 2. MCDropout CLASS
# ============================================================================
class MCDropout(tf.keras.layers.Dropout):
    def call(self, inputs, training=None):
        return super().call(inputs, training=True)


# ============================================================================
# 3. PREPROCESSING
# ============================================================================
def preprocess_image(img_pil, target_size=TARGET_SIZE):
    """Resize full photomicrograph to model input size and normalize."""
    if img_pil.mode != 'RGB':
        img_pil = img_pil.convert('RGB')
    img_resized = img_pil.resize(target_size, Image.Resampling.LANCZOS)
    img_array = np.array(img_resized, dtype=np.float32) / 255.0
    return img_array


# ============================================================================
# 4. PREDICTION FUNCTIONS
# ============================================================================
def predict_standard(model, img_array):
    """Single forward pass for CNN and transfer learning models."""
    img_batch = np.expand_dims(img_array, axis=0)
    prediction = model.predict(img_batch, verbose=0)

    if prediction.shape[-1] == 1:
        frost_prob = float(prediction[0][0])
    else:
        frost_prob = float(prediction[0][1])

    return frost_prob


def predict_bnn(model, img_array, n_samples=20):
    """
    BNN prediction with Monte Carlo Dropout uncertainty.
    Returns: frost_prob_mean, frost_prob_std, all_predictions
    """
    img_batch = np.expand_dims(img_array, axis=0)
    predictions = []

    for _ in range(n_samples):
        pred = model.predict(img_batch, verbose=0)
        if pred.shape[-1] == 1:
            predictions.append(float(pred[0][0]))
        else:
            predictions.append(float(pred[0][1]))

    predictions = np.array(predictions)
    return np.mean(predictions), np.std(predictions), predictions


# ============================================================================
# 5. SCORE-CAM FUNCTIONS
# ============================================================================

def make_scorecam_heatmap(img_array, model, last_conv_layer_name):
    """
    Score-CAM for CNN and transfer learning models.
    img_array: (1, 512, 512, 3) preprocessed image batch.
    """
    conv_layer_model = tf.keras.models.Model(
        [model.inputs],
        [model.get_layer(last_conv_layer_name).output]
    )
    conv_outputs = conv_layer_model(img_array)[0].numpy()

    input_height, input_width = img_array.shape[1], img_array.shape[2]
    conv_height, conv_width, num_channels = conv_outputs.shape

    scores = []
    for i in range(num_channels):
        activation_map = conv_outputs[:, :, i]

        amin, amax = activation_map.min(), activation_map.max()
        if amax - amin != 0:
            activation_map_norm = (activation_map - amin) / (amax - amin)
        else:
            activation_map_norm = activation_map

        zoom_factor = (input_height / conv_height, input_width / conv_width)
        activation_map_resized = zoom(activation_map_norm, zoom_factor, order=1)

        mask = np.expand_dims(activation_map_resized, axis=-1)
        masked_input = img_array[0] * mask
        masked_input = np.expand_dims(masked_input, axis=0)

        masked_prediction = model.predict(masked_input, verbose=0)
        if masked_prediction.shape[-1] == 1:
            score = masked_prediction[0, 0]
        else:
            score = masked_prediction[0, 1]
        scores.append(score)

    scores = np.array(scores)
    if scores.max() - scores.min() != 0:
        scores = (scores - scores.min()) / (scores.max() - scores.min())

    heatmap = np.zeros((conv_height, conv_width))
    for i in range(num_channels):
        heatmap += scores[i] * conv_outputs[:, :, i]

    heatmap = np.maximum(heatmap, 0)
    if heatmap.max() != 0:
        heatmap = heatmap / heatmap.max()

    return heatmap


def make_scorecam_heatmap_bnn(img_array, model, last_conv_layer_name, mc_samples=5):
    """
    Score-CAM for BNN with MC sampling for consistency.
    Averages predictions across mc_samples forward passes per masked input.
    """
    conv_layer_model = tf.keras.models.Model(
        [model.inputs],
        [model.get_layer(last_conv_layer_name).output]
    )
    conv_outputs = conv_layer_model(img_array)[0].numpy()

    input_height, input_width = img_array.shape[1], img_array.shape[2]
    conv_height, conv_width, num_channels = conv_outputs.shape

    scores = []
    for i in range(num_channels):
        activation_map = conv_outputs[:, :, i]

        amin, amax = activation_map.min(), activation_map.max()
        if amax - amin != 0:
            activation_map_norm = (activation_map - amin) / (amax - amin)
        else:
            activation_map_norm = activation_map

        zoom_factor = (input_height / conv_height, input_width / conv_width)
        activation_map_resized = zoom(activation_map_norm, zoom_factor, order=1)

        mask = np.expand_dims(activation_map_resized, axis=-1)
        masked_input = img_array[0] * mask
        masked_input = np.expand_dims(masked_input, axis=0)

        mc_preds = []
        for _ in range(mc_samples):
            masked_pred = model.predict(masked_input, verbose=0)
            if masked_pred.shape[-1] == 1:
                mc_preds.append(masked_pred[0, 0])
            else:
                mc_preds.append(masked_pred[0, 1])
        score = np.mean(mc_preds)
        scores.append(score)

    scores = np.array(scores)
    if scores.max() - scores.min() != 0:
        scores = (scores - scores.min()) / (scores.max() - scores.min())

    heatmap = np.zeros((conv_height, conv_width))
    for i in range(num_channels):
        heatmap += scores[i] * conv_outputs[:, :, i]

    heatmap = np.maximum(heatmap, 0)
    if heatmap.max() != 0:
        heatmap = heatmap / heatmap.max()

    return heatmap


class ScoreCAM_Transfer:
    """Score-CAM for transfer learning models (MobileNetV2, EfficientNet, ResNet50).
    These have nested base models, so we need to navigate into the sub-model."""
    def __init__(self, model, base_name, layer_candidates):
        self.model = model
        self.layer_name = None
        self.feature_model = None

        base_layer = None
        for layer in model.layers:
            if base_name in layer.name.lower():
                base_layer = layer
                break

        if base_layer is not None:
            for candidate in layer_candidates:
                try:
                    target = base_layer.get_layer(candidate)
                    self.feature_model = tf.keras.models.Model(
                        inputs=base_layer.input, outputs=target.output
                    )
                    self.layer_name = candidate
                    break
                except:
                    continue

            if self.feature_model is None:
                for sublayer in reversed(base_layer.layers):
                    if 'conv' in sublayer.name.lower() or 'project' in sublayer.name.lower():
                        try:
                            if len(sublayer.output_shape) == 4:
                                self.feature_model = tf.keras.models.Model(
                                    inputs=base_layer.input, outputs=sublayer.output
                                )
                                self.layer_name = sublayer.name
                                break
                        except:
                            continue

        if self.feature_model is None:
            raise ValueError(f"Could not find suitable layer for {base_name}")

        feat_shape = self.feature_model.output_shape
        print(f"    Layer: {self.layer_name} | Resolution: {feat_shape[1]}x{feat_shape[2]}")

    def generate_cam(self, input_image):
        if len(input_image.shape) == 3:
            input_image = np.expand_dims(input_image, axis=0)

        feature_maps = self.feature_model.predict(input_image, verbose=0)
        original_score = self.model.predict(input_image, verbose=0)[0]
        if len(original_score.shape) > 0:
            original_score = original_score[0]

        weights = []
        n_features = feature_maps.shape[-1]
        step = max(1, n_features // 50)

        for i in range(0, n_features, step):
            fm = feature_maps[0, :, :, i]
            resized = cv2.resize(fm, (input_image.shape[2], input_image.shape[1]))
            if resized.max() > resized.min():
                normed = (resized - resized.min()) / (resized.max() - resized.min())
            else:
                normed = np.zeros_like(resized)

            masked = input_image[0] * np.expand_dims(normed, axis=-1)
            masked = np.expand_dims(masked, axis=0)
            try:
                score = self.model.predict(masked, verbose=0)[0]
                if len(score.shape) > 0:
                    score = score[0]
                weights.append(score)
            except:
                weights.append(0.0)

        weights = np.array(weights)
        cam = np.zeros((feature_maps.shape[1], feature_maps.shape[2]), dtype=np.float32)
        for idx, i in enumerate(range(0, n_features, step)):
            cam += weights[idx] * feature_maps[0, :, :, i]

        cam = np.maximum(cam, 0)
        if cam.max() > cam.min():
            cam = (cam - cam.min()) / (cam.max() - cam.min())

        cam_resized = cv2.resize(cam, (TARGET_SIZE[0], TARGET_SIZE[1]))
        return cam_resized, original_score


def overlay_heatmap(img_pil, heatmap, alpha=0.4):
    """Overlay Score-CAM heatmap on original full-resolution image."""
    img_array = np.array(img_pil.convert('RGB'))
    heatmap_resized = cv2.resize(heatmap, (img_array.shape[1], img_array.shape[0]))
    heatmap_colored = cv2.applyColorMap(np.uint8(255 * heatmap_resized), cv2.COLORMAP_JET)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)
    superimposed = heatmap_colored * alpha + img_array
    superimposed = np.clip(superimposed, 0, 255).astype(np.uint8)
    return Image.fromarray(superimposed)


def find_last_conv_layer(model):
    """Find the last convolutional layer in a model."""
    for layer in reversed(model.layers):
        if 'conv' in layer.name.lower() and hasattr(layer, 'output'):
            return layer.name
    return None


# ============================================================================
# 6. FIGURE HELPERS
# ============================================================================
def save_fig(fig, path_no_ext):
    """Save figure as TIFF (300 dpi) and PNG."""
    fig.savefig(path_no_ext + '.tiff', dpi=300, bbox_inches='tight',
                format='tiff', pil_kwargs={'compression': 'tiff_lzw'})
    fig.savefig(path_no_ext + '.png', dpi=300, bbox_inches='tight')
    print(f"  Saved: {os.path.basename(path_no_ext)}.tiff / .png")


# ============================================================================
# 7. LOAD IMAGES WITH LABELS
# ============================================================================
print("=" * 60)
print("STEP 1: LOADING FULL PHOTOMICROGRAPHS")
print("=" * 60)

image_extensions = {'.tif', '.tiff', '.jpg', '.jpeg', '.png', '.bmp'}
images_data = {}

for class_name, label in [('frost', 1), ('non_frost', 0)]:
    class_dir = os.path.join(input_dir, class_name)
    if not os.path.isdir(class_dir):
        print(f"\n  WARNING: {class_dir} not found! Skipping.")
        continue

    files = sorted([
        f for f in os.listdir(class_dir)
        if Path(f).suffix.lower() in image_extensions
    ])
    print(f"\n  {class_name}/ -> {len(files)} images (label={label})")

    for fname in files:
        path = os.path.join(class_dir, fname)
        try:
            img = Image.open(path)
            width, height = img.size
            name_key = os.path.splitext(fname)[0]

            images_data[name_key] = {
                'path': path,
                'image': img,
                'label': label,
                'class': class_name,
                'size': (width, height),
                'mode': img.mode,
            }
            print(f"    + {fname} - {width}x{height} ({img.mode})")

        except Exception as e:
            print(f"    x ERROR loading {fname}: {e}")

n_total = len(images_data)
n_frost = sum(1 for v in images_data.values() if v['label'] == 1)
n_nonfrost = n_total - n_frost
print(f"\nTotal: {n_total} images ({n_frost} frost, {n_nonfrost} non-frost)")

print("\nImage size distribution:")
sizes = [v['size'] for v in images_data.values()]
for size in sorted(set(sizes)):
    count = sizes.count(size)
    print(f"  {size[0]} x {size[1]}: {count} image(s)")


# ============================================================================
# 8. MAIN INFERENCE LOOP - ALL 5 MODELS
# ============================================================================
print("\n" + "=" * 60)
print("STEP 2: CLASSIFICATION + SCORE-CAM FOR ALL MODELS")
print("=" * 60)

metrics_data = {mn: {'y_true': [], 'y_pred': [], 'y_prob': [], 'y_std': []}
                for mn in model_paths.keys()}

all_results = {}
all_heatmap_results = {}

for model_name, model_path in model_paths.items():
    print(f"\n{'='*60}")
    print(f"MODEL: {model_name}")
    print(f"{'='*60}")

    # Load model
    print(f"\n  Loading model...", end=" ")
    if model_name == 'BNN':
        model = keras.models.load_model(
            model_path, custom_objects={'MCDropout': MCDropout}
        )
    else:
        model = keras.models.load_model(model_path)

    print("Done!")
    print(f"  Input shape: {model.input_shape}")
    print(f"  Output shape: {model.output_shape}")
    print(f"  Parameters: {model.count_params():,}")

    if model_name == 'BNN':
        mcdropout_count = sum(1 for l in model.layers if isinstance(l, MCDropout))
        print(f"  MCDropout layers: {mcdropout_count}")

    # Find last conv layer (for CNN and BNN only)
    last_conv_name = find_last_conv_layer(model)
    print(f"  Last conv layer: {last_conv_name}")

    # Initialize ScoreCAM_Transfer for transfer learning models
    cam_obj = None
    if model_name == 'MobileNetV2':
        candidates = ['block_16_project_BN', 'block_16_project',
                       'block_15_project', 'block_14_project', 'Conv_1']
        cam_obj = ScoreCAM_Transfer(model, 'mobilenet', candidates)
    elif model_name == 'EfficientNetV2B0':
        candidates = ['block6h_add', 'block6a_expand_conv', 'block5e_add',
                       'block6a_project_conv', 'top_conv']
        cam_obj = ScoreCAM_Transfer(model, 'efficientnet', candidates)
    elif model_name == 'ResNet50':
        candidates = ['conv5_block3_out', 'conv5_block3_add',
                       'conv5_block3_3_conv', 'conv4_block6_out']
        cam_obj = ScoreCAM_Transfer(model, 'resnet', candidates)

    model_heatmap_results = {}
    model_predictions = {}

    for img_name, img_info in images_data.items():
        true_label = img_info['label']
        true_class = img_info['class']

        print(f"\n  ---")
        print(f"  Image: {img_name} ({img_info['size'][0]}x{img_info['size'][1]})")
        print(f"  True label: {true_class}")

        # Preprocess (resize to 512x512)
        img_preprocessed = preprocess_image(img_info['image'])
        img_batch = np.expand_dims(img_preprocessed, axis=0)

        # Prediction
        if model_name == 'BNN':
            print(f"  Running {MC_PASSES} MC forward passes...", end=" ")
            frost_prob, frost_std, all_preds = predict_bnn(
                model, img_preprocessed, n_samples=MC_PASSES
            )
            print("Done!")
            pred_label = 1 if frost_prob > 0.5 else 0
            pred_class = 'FROST' if pred_label == 1 else 'NON-FROST'
            confidence = max(frost_prob, 1 - frost_prob)

            print(f"  Prediction: {pred_class}")
            print(f"    Frost probability:     {frost_prob:.3f} ({frost_prob*100:.1f}%)")
            print(f"    Epistemic uncertainty: {frost_std:.3f}")
            print(f"    Confidence: {confidence*100:.1f}%")

            model_predictions[img_name] = {
                'predicted_class': pred_class,
                'frost_probability': frost_prob,
                'uncertainty': frost_std,
                'confidence': confidence,
            }

        else:
            frost_prob = predict_standard(model, img_preprocessed)
            frost_std = None
            pred_label = 1 if frost_prob > 0.5 else 0
            pred_class = 'FROST' if pred_label == 1 else 'NON-FROST'
            confidence = max(frost_prob, 1 - frost_prob)

            print(f"  Prediction: {pred_class}")
            print(f"    Frost probability: {frost_prob:.3f} ({frost_prob*100:.1f}%)")
            print(f"    Confidence: {confidence*100:.1f}%")

            model_predictions[img_name] = {
                'predicted_class': pred_class,
                'frost_probability': frost_prob,
                'uncertainty': None,
                'confidence': confidence,
            }

        correct_str = 'CORRECT' if pred_label == true_label else 'WRONG'
        print(f"  Result: {correct_str}")

        # Store for metrics
        metrics_data[model_name]['y_true'].append(true_label)
        metrics_data[model_name]['y_pred'].append(pred_label)
        metrics_data[model_name]['y_prob'].append(frost_prob)
        metrics_data[model_name]['y_std'].append(frost_std)

        # Score-CAM (model-specific dispatch)
        print(f"  Generating Score-CAM...", end=" ")
        try:
            if model_name == 'CNN':
                heatmap = make_scorecam_heatmap(
                    img_batch, model, last_conv_name
                )
            elif model_name == 'BNN':
                heatmap = make_scorecam_heatmap_bnn(
                    img_batch, model, last_conv_name, mc_samples=SCORECAM_MC
                )
            elif model_name in ('MobileNetV2', 'EfficientNetV2B0', 'ResNet50'):
                heatmap, _ = cam_obj.generate_cam(img_preprocessed)
            else:
                heatmap = None

            if heatmap is not None:
                overlay_img = overlay_heatmap(img_info['image'], heatmap, alpha=0.5)
                model_heatmap_results[img_name] = {
                    'heatmap': heatmap,
                    'overlay': overlay_img
                }
                print("Done!")
            else:
                print("Skipped (unknown model type)")
        except Exception as e:
            print(f"Error: {e}")

        # Store for CSV
        if img_name not in all_results:
            all_results[img_name] = {
                'true_label': true_label,
                'true_class': true_class,
            }
        all_results[img_name][model_name] = {
            'frost_prob': frost_prob,
            'std': frost_std,
            'pred_label': pred_label,
            'pred_class': pred_class,
        }

    all_heatmap_results[model_name] = {
        'predictions': model_predictions,
        'heatmaps': model_heatmap_results,
    }

    # Cleanup
    del model
    if cam_obj is not None:
        del cam_obj
    tf.keras.backend.clear_session()
    print(f"\n  {model_name} complete. Session cleared.")


# ============================================================================
# 9. SCORE-CAM VISUALIZATIONS - PER MODEL
# ============================================================================
print("\n" + "=" * 60)
print("STEP 3: SCORE-CAM VISUALIZATIONS")
print("=" * 60)

for model_name in model_paths.keys():
    heatmap_results = all_heatmap_results[model_name]['heatmaps']
    predictions = all_heatmap_results[model_name]['predictions']

    if not heatmap_results:
        continue

    n_images = len(heatmap_results)
    fig, axes = plt.subplots(n_images, 3, figsize=(18, 6 * n_images))

    if n_images == 1:
        axes = axes.reshape(1, -1)

    for idx, (img_name, result) in enumerate(sorted(heatmap_results.items())):
        pred = predictions[img_name]
        img_data = images_data[img_name]
        true_str = 'Frost' if img_data['label'] == 1 else 'Non-Frost'

        # Column 1: Original
        axes[idx, 0].imshow(img_data['image'])
        axes[idx, 0].axis('off')
        axes[idx, 0].set_title(f"Original\n{img_name}\nTrue: {true_str}",
                               fontsize=11, weight='bold')

        # Column 2: Heatmap
        im = axes[idx, 1].imshow(result['heatmap'], cmap='jet', vmin=0, vmax=1)
        axes[idx, 1].axis('off')
        axes[idx, 1].set_title(f"Score-CAM Activation\n(0=low, 1=high)",
                               fontsize=11, weight='bold')
        cbar = plt.colorbar(im, ax=axes[idx, 1], fraction=0.046, pad=0.04)
        cbar.set_label('Activation', rotation=270, labelpad=15)

        # Column 3: Overlay
        axes[idx, 2].imshow(result['overlay'])
        axes[idx, 2].axis('off')

        pred_text = f"Overlay\n{pred['predicted_class']}\n"
        pred_text += f"Prob: {pred['frost_probability']:.3f}"
        if pred['uncertainty'] is not None:
            pred_text += f"\nUnc: {pred['uncertainty']:.3f}"

        pred_label = 1 if pred['frost_probability'] > 0.5 else 0
        correct = pred_label == img_data['label']
        color = 'green' if correct else 'red'
        axes[idx, 2].set_title(pred_text, fontsize=11, weight='bold', color=color)

    model_label = f"{model_name} (BNN, {MC_PASSES} MC passes)" if model_name == 'BNN' else model_name
    plt.suptitle(f"Score-CAM Results - {model_label}",
                 fontsize=16, weight='bold', y=1.01)
    plt.tight_layout()
    save_fig(fig, os.path.join(output_dir, f'scorecam_{model_name}'))
    plt.show()
    plt.close(fig)


# ============================================================================
# 10. CLASSIFICATION METRICS
# ============================================================================
print("\n" + "=" * 60)
print("STEP 4: CLASSIFICATION METRICS")
print("=" * 60)

model_names = list(model_paths.keys())
metrics_summary = {}

for model_name in model_names:
    y_true = np.array(metrics_data[model_name]['y_true'])
    y_pred = np.array(metrics_data[model_name]['y_pred'])

    acc  = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec  = recall_score(y_true, y_pred, zero_division=0)
    f1   = f1_score(y_true, y_pred, zero_division=0)
    cm   = confusion_matrix(y_true, y_pred, labels=[0, 1])

    metrics_summary[model_name] = {
        'accuracy': acc, 'precision': prec, 'recall': rec, 'f1': f1, 'cm': cm
    }

    print(f"\n--- {model_name} ---")
    print(f"  Accuracy:  {acc:.3f}")
    print(f"  Precision: {prec:.3f}")
    print(f"  Recall:    {rec:.3f}")
    print(f"  F1-score:  {f1:.3f}")
    print(f"  Confusion matrix (rows=true, cols=pred):")
    print(f"              Non-Frost  Frost")
    print(f"  Non-Frost   {cm[0,0]:>5}      {cm[0,1]:>5}")
    print(f"  Frost       {cm[1,0]:>5}      {cm[1,1]:>5}")


# ============================================================================
# 11. METRICS COMPARISON FIGURES
# ============================================================================
print("\n" + "=" * 60)
print("STEP 5: METRICS COMPARISON FIGURES")
print("=" * 60)

# 11a. Grouped bar chart
metric_names = ['Accuracy', 'Precision', 'Recall', 'F1-score']
metric_keys  = ['accuracy', 'precision', 'recall', 'f1']

x = np.arange(len(model_names))
width = 0.18

fig, ax = plt.subplots(figsize=(12, 6))
for i, (mname, mkey) in enumerate(zip(metric_names, metric_keys)):
    values = [metrics_summary[mn][mkey] for mn in model_names]
    bars = ax.bar(x + i * width, values, width, label=mname, color=palette[i])
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2., bar.get_height() + 0.01,
                f'{val:.2f}', ha='center', va='bottom', fontsize=8, fontweight='bold')

ax.set_xlabel('Model', fontsize=12)
ax.set_ylabel('Score', fontsize=12)
#ax.set_title('Classification Metrics - Full Photomicrographs',
#             fontsize=14, fontweight='bold')
ax.set_xticks(x + width * 1.5)
ax.set_xticklabels(model_names, fontsize=10)
ax.set_ylim(0, 1.15)
ax.legend(loc='upper right', fontsize=10)
ax.axhline(y=0.5, color='gray', linestyle='--', alpha=0.5)

plt.tight_layout()
save_fig(fig, os.path.join(output_dir, 'metrics_comparison_bar'))
plt.show()
plt.close(fig)

# 11b. Confusion matrices side by side
n_models = len(model_names)
fig, axes = plt.subplots(1, n_models, figsize=(4 * n_models, 4))
if n_models == 1:
    axes = [axes]

for ax, mn in zip(axes, model_names):
    cm = metrics_summary[mn]['cm']
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['Non-Frost', 'Frost'],
                yticklabels=['Non-Frost', 'Frost'],
                cbar=False, annot_kws={'size': 14, 'fontweight': 'bold'})
    ax.set_title(f"{mn}\nF1={metrics_summary[mn]['f1']:.3f}",
                 fontsize=11, fontweight='bold')
    ax.set_xlabel('Predicted')
    ax.set_ylabel('True')

#plt.suptitle('Confusion Matrices - Full Photomicrographs',
#             fontsize=14, fontweight='bold', y=1.03)
plt.tight_layout()
save_fig(fig, os.path.join(output_dir, 'confusion_matrices'))
plt.show()
plt.close(fig)


# ============================================================================
# 12. COMPACT OVERVIEW - ALL MODELS x ALL IMAGES
# ============================================================================
print("\n" + "=" * 60)
print("STEP 6: COMPACT OVERVIEW")
print("=" * 60)

n_imgs = len(images_data)
n_mods = len(model_names)

fig, axes = plt.subplots(n_imgs, n_mods + 1, figsize=(5 * (n_mods + 1), 5 * n_imgs))
if n_imgs == 1:
    axes = axes.reshape(1, -1)

img_names_sorted = sorted(images_data.keys())

for row, img_name in enumerate(img_names_sorted):
    img_info = images_data[img_name]
    true_str = 'Frost' if img_info['label'] == 1 else 'Non-Frost'

    # First column: original
    axes[row, 0].imshow(img_info['image'])
    axes[row, 0].axis('off')
    axes[row, 0].set_title(f"Original\n{img_name}\nTrue: {true_str}",
                           fontsize=10, weight='bold')

    # One column per model
    for col, mn in enumerate(model_names):
        heatmap_data = all_heatmap_results[mn]['heatmaps']
        pred_data = all_heatmap_results[mn]['predictions']

        if img_name in heatmap_data:
            axes[row, col + 1].imshow(heatmap_data[img_name]['overlay'])
        else:
            axes[row, col + 1].imshow(img_info['image'])

        axes[row, col + 1].axis('off')

        pred = pred_data[img_name]
        pred_label_val = 1 if pred['frost_probability'] > 0.5 else 0
        correct = pred_label_val == img_info['label']
        color = 'green' if correct else 'red'
        correct_str = 'OK' if correct else 'WRONG'

        title = f"{mn}\n{pred['predicted_class']}: {pred['frost_probability']:.2f}"
        if pred['uncertainty'] is not None:
            title += f"\nUnc: {pred['uncertainty']:.3f}"
        title += f"  [{correct_str}]"

        axes[row, col + 1].set_title(title, fontsize=9, weight='bold', color=color)

plt.suptitle('All Models x All Images: Score-CAM Overlays',
             fontsize=16, weight='bold', y=1.01)
plt.tight_layout()
save_fig(fig, os.path.join(output_dir, 'compact_all_models_all_images'))
plt.show()
plt.close(fig)


# ============================================================================
# 13. SAVE RESULTS TO CSV
# ============================================================================
print("\n" + "=" * 60)
print("STEP 7: SAVING RESULTS")
print("=" * 60)

# Per-image predictions
csv_path = os.path.join(output_dir, 'prediction_summary.csv')
rows_csv = []
for img_name in images_data.keys():
    r = all_results[img_name]
    row = {
        'image': img_name,
        'true_class': r['true_class'],
        'true_label': r['true_label'],
    }
    for mn in model_names:
        mr = r[mn]
        correct = 1 if mr['pred_label'] == r['true_label'] else 0
        row[f'{mn}_prob'] = f"{mr['frost_prob']:.4f}"
        row[f'{mn}_std'] = f"{mr['std']:.4f}" if mr['std'] is not None else 'NA'
        row[f'{mn}_pred'] = mr['pred_class']
        row[f'{mn}_correct'] = correct
    rows_csv.append(row)

df_predictions = pd.DataFrame(rows_csv)
df_predictions.to_csv(csv_path, index=False)
print(f"\n  Prediction summary saved to: {csv_path}")

# Classification metrics
metrics_csv_path = os.path.join(output_dir, 'classification_metrics.csv')
rows_metrics = []
for mn in model_names:
    m = metrics_summary[mn]
    cm = m['cm']
    rows_metrics.append({
        'model': mn,
        'accuracy': f"{m['accuracy']:.4f}",
        'precision': f"{m['precision']:.4f}",
        'recall': f"{m['recall']:.4f}",
        'f1': f"{m['f1']:.4f}",
        'TN': cm[0, 0], 'FP': cm[0, 1],
        'FN': cm[1, 0], 'TP': cm[1, 1],
    })

df_metrics = pd.DataFrame(rows_metrics)
df_metrics.to_csv(metrics_csv_path, index=False)
print(f"  Classification metrics saved to: {metrics_csv_path}")

# Final summary table
print("\n" + "=" * 60)
print("FINAL SUMMARY")
print("=" * 60)

print(f"\n{'Model':<20} {'Acc':>6} {'Prec':>6} {'Rec':>6} {'F1':>6}")
print("-" * 50)
for mn in model_names:
    m = metrics_summary[mn]
    print(f"{mn:<20} {m['accuracy']:>6.3f} {m['precision']:>6.3f} "
          f"{m['recall']:>6.3f} {m['f1']:>6.3f}")

print("\n" + "=" * 60)
print("Done!")
print("=" * 60)

# ============================================================================
# 12c. RANDOM EXAMPLE PANEL: 2 NON-FROST + 2 FROST, COLUMNS = MODELS
# ============================================================================
print("\n" + "=" * 60)
print("STEP 6c: RANDOM EXAMPLE PANEL")
print("=" * 60)

import random

# Reproducible random selection
RANDOM_SEED = 42
random.seed(RANDOM_SEED)

# Separate images by class
frost_imgs = sorted([name for name, info in images_data.items() if info['label'] == 1])
nonfrost_imgs = sorted([name for name, info in images_data.items() if info['label'] == 0])

# Pick 2 random from each class
n_pick_frost = min(2, len(frost_imgs))
n_pick_nonfrost = min(2, len(nonfrost_imgs))

selected_frost = random.sample(frost_imgs, n_pick_frost)
selected_nonfrost = random.sample(nonfrost_imgs, n_pick_nonfrost)

selected_imgs = selected_nonfrost + selected_frost

print("Selected non-frost images:", selected_nonfrost)
print("Selected frost images:", selected_frost)

# Figure layout: rows = images, cols = original + all models
n_rows = len(selected_imgs)
n_cols = len(model_names) + 1

fig, axes = plt.subplots(n_rows, n_cols, figsize=(4.8 * n_cols, 4.8 * n_rows))

if n_rows == 1:
    axes = axes.reshape(1, -1)

# Column headers
col_titles = ['Original'] + model_names
for col, title in enumerate(col_titles):
    axes[0, col].set_title(title, fontsize=13, weight='bold')

for row, img_name in enumerate(selected_imgs):
    img_info = images_data[img_name]
    true_label = img_info['label']
    true_str = 'Frost' if true_label == 1 else 'Non-Frost'

    # Column 0: original image
    axes[row, 0].imshow(img_info['image'])
    axes[row, 0].axis('off')
    axes[row, 0].text(
        0.5, -0.08,
        f"{img_name}\nTrue: {true_str}",
        transform=axes[row, 0].transAxes,
        ha='center', va='top',
        fontsize=10, fontweight='bold'
    )

    # Remaining columns: model overlays
    for col, mn in enumerate(model_names, start=1):
        pred = all_heatmap_results[mn]['predictions'][img_name]
        heatmap_data = all_heatmap_results[mn]['heatmaps']

        if img_name in heatmap_data:
            axes[row, col].imshow(heatmap_data[img_name]['overlay'])
        else:
            axes[row, col].imshow(img_info['image'])

        axes[row, col].axis('off')

        pred_label_val = 1 if pred['frost_probability'] > 0.5 else 0
        correct = pred_label_val == true_label
        color = 'green' if correct else 'red'
        correct_str = 'OK' if correct else 'WRONG'

        txt = f"{pred['predicted_class']}\nP={pred['frost_probability']:.2f}"
        if pred['uncertainty'] is not None:
            txt += f"\nU={pred['uncertainty']:.3f}"
        txt += f"\n[{correct_str}]"

        axes[row, col].text(
            0.5, -0.08,
            txt,
            transform=axes[row, col].transAxes,
            ha='center', va='top',
            fontsize=9, fontweight='bold', color=color
        )

#plt.suptitle(
#    'Random full photomicrographs: model predictions and Score-CAM overlays\n'
#    '(2 non-frost, 2 frost)',
#    fontsize=16, fontweight='bold', y=1.02
#)
plt.tight_layout()
save_fig(fig, os.path.join(output_dir, 'random_4_images_all_models_overlay'))
plt.show()
plt.close(fig)