# -*- coding: utf-8 -*-
"""long_tail

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DrbUfVBgFblytXlraa_xaabPD22UmHaY

Score-CAM comparative analysis across five binary frost vs non-frost models
(CNN, BNN, MobileNetV2, EfficientNetV2B0, ResNet50), producing side-by-side
visual and quantitative summaries of where each architecture focuses.

This script:
1. Mounts Google Drive, loads a small set of hand-picked visibility images, and
   loads five trained models (classic CNN, BNN with MC-dropout, and three
   transfer-learning backbones). It builds Score-CAM generators tailored to
   each model type, including a Monte Carlo Score-CAM variant for the BNN to
   capture predictive uncertainty across multiple stochastic forward passes.
2. For every model–image pair, computes a Score-CAM heatmap and prediction,
   stores them in memory, and then creates:
   - Grid 1: top-X% pixel masks (e.g. top 20% most important pixels) for all
     models, overlaid on the original image with the fraction of total CAM
     mass covered by those pixels.
   - Grid 2: standard heatmap overlays (JET colormap on top of the RGB image)
     for all models and images.
   - Grid 3: multi-threshold masks (e.g. top 10/20/50% pixels) per image,
     comparing how concentrated each model’s attention is under different
     importance thresholds.
3. Translates the heatmaps into cumulative “long-tail” curves of activation
   mass vs. pixel fraction by sorting CAM intensities, and plots:
   - Grid 4: per-image curves with all models overlaid, plus a uniform
     reference line to show how quickly each model concentrates mass.
   - Grid 5: combined curves for all models and all images, highlighting global
     differences in attention concentration across architectures.
   - Grid 6: per-model panels where curves from different images are overlaid
     with different linestyles, showing how consistent each model’s spatial
     behavior is across examples.
4. For all grids, uses a dark Seaborn style and a colorblind-safe palette,
   saving figures as 300 dpi .tif files to a dedicated output directory. It
   also prints a compact summary table that, for each model and image, reports
   what percentage of pixels is needed to capture given CAM mass thresholds
   (e.g. 50%, 80%, 90%, 95%), which numerically complements the visual
   comparisons.
"""

!pip install tf-keras-vis

# ============================================================================
# SCORE-CAM COMPARATIVE GRID — ALL 5 MODELS
# ============================================================================
# Generates comparative figures:
#   Grid 1: Top 20% pixel masks — all models side by side
#   Grid 2: Score-CAM heatmap overlays — all models side by side
#   Grid 3: Multi-threshold pixel masks per image
#   Grid 4: Cumulative curves — per image (all models overlaid)
#   Grid 5: Cumulative curves — all models, all images combined
#   Grid 6: Cumulative curves — per model (images overlaid)
#
# All figures: sns.darkgrid, colorblind palette, saved as .tif @ 300 dpi
#
# Run in Google Colab with GPU runtime.
# ============================================================================

import os
import numpy as np
import tensorflow as tf
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.lines import Line2D
from glob import glob
from google.colab import drive

# Mount Google Drive
print("Mounting Google Drive...")
drive.mount('/content/drive')
print("Google Drive mounted successfully!\n")

# ============================================================================
# PLOT SETTINGS
# ============================================================================
sns.set_style('darkgrid')
CB_PALETTE = sns.color_palette('colorblind')

# Consistent model colors (colorblind-safe)
MODEL_COLORS = {
    'CNN':              CB_PALETTE[0],
    'BNN':              CB_PALETTE[2],
    'MobileNetV2':      CB_PALETTE[4],
    'EfficientNetV2B0': CB_PALETTE[9],
    'ResNet50':         CB_PALETTE[3],
}

# Save settings
SAVE_DPI = 300
SAVE_FORMAT = 'tif'

def save_fig(fig, filepath_no_ext):
    """Save figure as .tif at 300 dpi."""
    full_path = f"{filepath_no_ext}.{SAVE_FORMAT}"
    fig.savefig(full_path, dpi=SAVE_DPI, bbox_inches='tight', format=SAVE_FORMAT)
    print(f"  Saved: {full_path}")

# ============================================================================
# CONFIGURATION
# ============================================================================
SIZE = 512
MC_PASSES = 20
TOP_PCT = 20

image_directory = '/content/drive/My Drive/voting_poll/images/visibility'

SELECTED_IMAGES = ['vis_img_006', 'vis_img_010', 'vis_img_005']

model_paths = {
    'CNN':              '/content/drive/MyDrive/frost/models_saved/neu_cnn_binary/cnn_best_model.h5',
    'BNN':              '/content/drive/MyDrive/frost/models_saved/neu_bnn_binary/bnn_best_model.h5',
    'MobileNetV2':      '/content/drive/MyDrive/frost/models_saved/neu_mobile_binary/mobilenet_best_model.h5',
    'EfficientNetV2B0': '/content/drive/MyDrive/frost/models_saved/neu_efficientnet_binary/efficientnet_best_model.h5',
    'ResNet50':         '/content/drive/MyDrive/frost/models_saved/neu_resnet_binary/resnet_best_model.h5',
}

output_dir = '/content/drive/MyDrive/frost/scorecam_comparative'
os.makedirs(output_dir, exist_ok=True)

# ============================================================================
# MCDropout + ScoreCAM classes
# ============================================================================

class MCDropout(tf.keras.layers.Dropout):
    def call(self, inputs, training=None):
        return super().call(inputs, training=True)


class ScoreCAM_Transfer:
    """Score-CAM for transfer learning models (MobileNetV2, EfficientNet, ResNet50)."""
    def __init__(self, model, base_name, layer_candidates):
        self.model = model
        self.layer_name = None
        self.feature_model = None

        base_layer = None
        for layer in model.layers:
            if base_name in layer.name.lower():
                base_layer = layer
                break

        if base_layer is not None:
            for candidate in layer_candidates:
                try:
                    target = base_layer.get_layer(candidate)
                    self.feature_model = tf.keras.models.Model(
                        inputs=base_layer.input, outputs=target.output
                    )
                    self.layer_name = candidate
                    break
                except:
                    continue

            if self.feature_model is None:
                for sublayer in reversed(base_layer.layers):
                    if 'conv' in sublayer.name.lower() or 'project' in sublayer.name.lower():
                        try:
                            if len(sublayer.output_shape) == 4:
                                self.feature_model = tf.keras.models.Model(
                                    inputs=base_layer.input, outputs=sublayer.output
                                )
                                self.layer_name = sublayer.name
                                break
                        except:
                            continue

        if self.feature_model is None:
            raise ValueError(f"Could not find suitable layer for {base_name}")

        feat_shape = self.feature_model.output_shape
        print(f"  Layer: {self.layer_name} | Resolution: {feat_shape[1]}x{feat_shape[2]}")

    def generate_cam(self, input_image):
        if len(input_image.shape) == 3:
            input_image = np.expand_dims(input_image, axis=0)

        feature_maps = self.feature_model.predict(input_image, verbose=0)
        original_score = self.model.predict(input_image, verbose=0)[0]
        if len(original_score.shape) > 0:
            original_score = original_score[0]

        weights = []
        n_features = feature_maps.shape[-1]
        step = max(1, n_features // 50)

        for i in range(0, n_features, step):
            fm = feature_maps[0, :, :, i]
            resized = cv2.resize(fm, (input_image.shape[2], input_image.shape[1]))
            if resized.max() > resized.min():
                normed = (resized - resized.min()) / (resized.max() - resized.min())
            else:
                normed = np.zeros_like(resized)

            masked = input_image[0] * np.expand_dims(normed, axis=-1)
            masked = np.expand_dims(masked, axis=0)

            try:
                score = self.model.predict(masked, verbose=0)[0]
                if len(score.shape) > 0:
                    score = score[0]
                weights.append(score)
            except:
                weights.append(0.0)

        weights = np.array(weights)
        cam = np.zeros((feature_maps.shape[1], feature_maps.shape[2]), dtype=np.float32)
        for idx, i in enumerate(range(0, n_features, step)):
            cam += weights[idx] * feature_maps[0, :, :, i]

        cam = np.maximum(cam, 0)
        if cam.max() > cam.min():
            cam = (cam - cam.min()) / (cam.max() - cam.min())

        cam_resized = cv2.resize(cam, (SIZE, SIZE))
        return cam_resized, original_score


def scorecam_cnn(model, input_image, conv_layer_name):
    from tf_keras_vis.scorecam import ScoreCAM

    def score_function(output):
        return output[:, 0]

    def model_modifier(m):
        m.layers[-1].activation = tf.keras.activations.linear
        return m

    scorecam = ScoreCAM(model, model_modifier=model_modifier)

    if len(input_image.shape) == 3:
        input_image = np.expand_dims(input_image, axis=0)

    cam = scorecam(score_function, input_image, penultimate_layer=conv_layer_name)
    pred = model.predict(input_image, verbose=0).flatten()[0]
    return cam[0], pred


def scorecam_bnn_mc(model, input_image, conv_layer_name, mc_passes=20):
    def get_conv_and_pred(model, img, layer_name):
        conv_layer = model.get_layer(layer_name)
        intermediate = tf.keras.Model(
            inputs=model.input, outputs=[conv_layer.output, model.output]
        )
        conv_out, pred = intermediate(img, training=False)
        return conv_out, pred

    def single_pass(model, img, layer_name):
        img = tf.cast(img, tf.float32)
        if len(img.shape) == 3:
            img = tf.expand_dims(img, 0)

        conv_out, base_pred = get_conv_and_pred(model, img, layer_name)
        conv_out = conv_out.numpy()[0]
        num_filters = conv_out.shape[-1]
        h, w = conv_out.shape[0], conv_out.shape[1]
        input_h, input_w = img.shape[1], img.shape[2]

        scores = np.zeros(num_filters)
        for f in range(num_filters):
            act = conv_out[:, :, f]
            act = cv2.resize(act, (input_w, input_h))
            amin, amax = act.min(), act.max()
            if amax - amin > 1e-8:
                act = (act - amin) / (amax - amin)
            else:
                act = np.zeros_like(act)

            masked = img.numpy()[0] * act[:, :, np.newaxis]
            masked = tf.expand_dims(masked, 0)
            masked_pred = model(masked, training=False)
            scores[f] = masked_pred.numpy()[0, 0]

        scores_exp = np.exp(scores - scores.max())
        weights = scores_exp / scores_exp.sum()

        heatmap = np.zeros((h, w), dtype=np.float32)
        for f in range(num_filters):
            heatmap += weights[f] * conv_out[:, :, f]

        heatmap = np.maximum(heatmap, 0)
        heatmap = cv2.resize(heatmap, (input_w, input_h))
        hm_max = heatmap.max()
        if hm_max > 1e-8:
            heatmap = heatmap / hm_max
        return heatmap

    mc_heatmaps = []
    mc_preds = []
    for t in range(mc_passes):
        hm = single_pass(model, input_image, layer_name=conv_layer_name)
        mc_heatmaps.append(hm)
        p = model(tf.expand_dims(input_image, 0), training=False).numpy()[0, 0]
        mc_preds.append(p)

    mean_heatmap = np.mean(mc_heatmaps, axis=0)
    mean_pred = np.mean(mc_preds)
    std_pred = np.std(mc_preds)

    return mean_heatmap, mean_pred, std_pred


# ============================================================================
# HELPERS
# ============================================================================

def make_pixel_mask_overlay(image, heatmap, top_pct=20):
    flat = heatmap.flatten()
    threshold_val = np.percentile(flat, 100 - top_pct)
    mask = (heatmap >= threshold_val).astype(np.float32)

    overlay = image.copy()
    for c in range(3):
        overlay[:, :, c] = image[:, :, c] * 0.3 + image[:, :, c] * mask * 0.7

    red_overlay = np.zeros_like(overlay)
    red_overlay[:, :, 0] = mask * 0.3
    overlay = np.clip(overlay + red_overlay, 0, 1)

    if flat.sum() > 0:
        flat_norm = flat / flat.sum()
        mass_covered = flat_norm[flat >= threshold_val].sum() * 100
    else:
        mass_covered = 0

    return overlay, mass_covered


def compute_cumulative_curve(heatmap):
    flat = heatmap.flatten()
    if flat.sum() == 0:
        return None, None
    flat_norm = flat / flat.sum()
    sorted_vals = np.sort(flat_norm)[::-1]
    cumsum = np.cumsum(sorted_vals)
    x_pct = np.linspace(0, 100, len(cumsum))
    return x_pct, cumsum * 100


# ============================================================================
# LOAD IMAGES
# ============================================================================
print("Loading images...")
all_vis_files = sorted(glob(os.path.join(image_directory, '*')))
file_map = {}
for f in all_vis_files:
    name_no_ext = os.path.splitext(os.path.basename(f))[0]
    file_map[name_no_ext] = f


def load_and_preprocess(path, size=SIZE):
    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (size, size))
    img = img.astype(np.float32) / 255.0
    return img


selected_images = {}
for name in SELECTED_IMAGES:
    if name in file_map:
        selected_images[name] = load_and_preprocess(file_map[name])
        print(f"  Loaded: {name}")
    else:
        print(f"  WARNING: {name} not found!")

print(f"\nLoaded {len(selected_images)} images.\n")

# ============================================================================
# RUN SCORE-CAM FOR EACH MODEL
# ============================================================================
print("=" * 60)
print("GENERATING SCORE-CAM HEATMAPS")
print("=" * 60)

model_heatmaps = {}
model_names_list = list(model_paths.keys())

for model_name, model_path in model_paths.items():
    print(f"\n--- {model_name} ---")

    if model_name == 'BNN':
        model = tf.keras.models.load_model(
            model_path, custom_objects={'MCDropout': MCDropout}
        )
    else:
        model = tf.keras.models.load_model(model_path)

    model_heatmaps[model_name] = {}

    for img_name, img in selected_images.items():
        print(f"  {img_name}...", end=" ")

        if model_name == 'CNN':
            conv_name = None
            for layer in reversed(model.layers):
                if isinstance(layer, tf.keras.layers.Conv2D):
                    conv_name = layer.name
                    break
            hm, pred = scorecam_cnn(model, img, conv_name)
            label = 'Frost' if pred > 0.5 else 'Non-Frost'
            title_extra = f"p={pred:.2f}"

        elif model_name == 'BNN':
            hm, mean_p, std_p = scorecam_bnn_mc(
                model, img, 'last_conv', mc_passes=MC_PASSES
            )
            pred = mean_p
            label = 'Frost' if mean_p > 0.5 else 'Non-Frost'
            title_extra = f"p={mean_p:.2f}\u00b1{std_p:.3f}"

        elif model_name == 'MobileNetV2':
            candidates = ['block_16_project_BN', 'block_16_project',
                          'block_15_project', 'block_14_project', 'Conv_1']
            cam = ScoreCAM_Transfer(model, 'mobilenet', candidates)
            hm, pred = cam.generate_cam(img)
            label = 'Frost' if pred > 0.5 else 'Non-Frost'
            title_extra = f"p={pred:.2f}"

        elif model_name == 'EfficientNetV2B0':
            candidates = ['block6h_add', 'block6a_expand_conv', 'block5e_add',
                          'block6a_project_conv', 'top_conv']
            cam = ScoreCAM_Transfer(model, 'efficientnet', candidates)
            hm, pred = cam.generate_cam(img)
            label = 'Frost' if pred > 0.5 else 'Non-Frost'
            title_extra = f"p={pred:.2f}"

        elif model_name == 'ResNet50':
            candidates = ['conv5_block3_out', 'conv5_block3_add',
                          'conv5_block3_3_conv', 'conv4_block6_out']
            cam = ScoreCAM_Transfer(model, 'resnet', candidates)
            hm, pred = cam.generate_cam(img)
            label = 'Frost' if pred > 0.5 else 'Non-Frost'
            title_extra = f"p={pred:.2f}"

        model_heatmaps[model_name][img_name] = {
            'heatmap': hm,
            'pred': pred,
            'label': label,
            'title_extra': title_extra,
        }
        print(f"{label} ({title_extra})")

    del model
    tf.keras.backend.clear_session()

# ============================================================================
# GRID 1: Top-X% Pixel Masks
# ============================================================================
print("\n" + "=" * 60)
print(f"GRID 1: Top {TOP_PCT}% Pixel Masks")
print("=" * 60)

n_images = len(SELECTED_IMAGES)
n_cols = 1 + len(model_names_list)

fig, axes = plt.subplots(n_images, n_cols, figsize=(4 * n_cols, 4.5 * n_images))
if n_images == 1:
    axes = axes[np.newaxis, :]

for row, img_name in enumerate(SELECTED_IMAGES):
    img = selected_images[img_name]
    axes[row, 0].imshow(img)
    axes[row, 0].set_title(f"Original\n{img_name}", fontsize=10, fontweight='bold')
    axes[row, 0].axis('off')

    for col, model_name in enumerate(model_names_list):
        data = model_heatmaps[model_name][img_name]
        overlay, mass = make_pixel_mask_overlay(img, data['heatmap'], TOP_PCT)
        axes[row, col + 1].imshow(overlay)
        axes[row, col + 1].set_title(
            f"{model_name}\n{data['label']} ({data['title_extra']})\n"
            f"Top {TOP_PCT}% \u2192 {mass:.1f}% mass",
            fontsize=9
        )
        axes[row, col + 1].axis('off')

plt.suptitle(
    f"Score-CAM: Top {TOP_PCT}% Most Important Pixels Across All 5 Architectures",
    fontsize=16, fontweight='bold', y=1.01
)
plt.tight_layout()
save_fig(fig, os.path.join(output_dir, f'grid1_pixel_masks_top{TOP_PCT}pct'))
plt.show()

# ============================================================================
# GRID 2: Heatmap Overlays
# ============================================================================
print("\n" + "=" * 60)
print("GRID 2: Heatmap Overlays")
print("=" * 60)

fig, axes = plt.subplots(n_images, n_cols, figsize=(4 * n_cols, 4.5 * n_images))
if n_images == 1:
    axes = axes[np.newaxis, :]

for row, img_name in enumerate(SELECTED_IMAGES):
    img = selected_images[img_name]
    axes[row, 0].imshow(img)
    axes[row, 0].set_title(f"Original\n{img_name}", fontsize=10, fontweight='bold')
    axes[row, 0].axis('off')

    for col, model_name in enumerate(model_names_list):
        data = model_heatmaps[model_name][img_name]
        hm = data['heatmap']
        hm_uint8 = np.uint8(255 * hm / (hm.max() + 1e-8))
        hm_color = cv2.applyColorMap(hm_uint8, cv2.COLORMAP_JET)
        hm_color = cv2.cvtColor(hm_color, cv2.COLOR_BGR2RGB)
        hm_color = cv2.resize(hm_color, (SIZE, SIZE))
        superimposed = cv2.addWeighted(
            (img * 255).astype(np.uint8), 0.6, hm_color, 0.4, 0
        )
        axes[row, col + 1].imshow(superimposed)
        axes[row, col + 1].set_title(
            f"{model_name}\n{data['label']} ({data['title_extra']})", fontsize=9
        )
        axes[row, col + 1].axis('off')

plt.suptitle(
    "Score-CAM Heatmap Overlays Across All 5 Architectures",
    fontsize=16, fontweight='bold', y=1.01
)
plt.tight_layout()
save_fig(fig, os.path.join(output_dir, 'grid2_heatmap_overlays'))
plt.show()

# ============================================================================
# GRID 3: Multi-threshold Pixel Masks (per image)
# ============================================================================
print("\n" + "=" * 60)
print("GRID 3: Multi-threshold Pixel Masks")
print("=" * 60)

TOP_PCTS = [10, 20, 50]

for ref_image in SELECTED_IMAGES:
    n_rows_g3 = len(model_names_list)
    n_cols_g3 = 1 + len(TOP_PCTS)

    fig, axes = plt.subplots(n_rows_g3, n_cols_g3,
                             figsize=(4.5 * n_cols_g3, 4 * n_rows_g3))
    img = selected_images[ref_image]

    for row, model_name in enumerate(model_names_list):
        data = model_heatmaps[model_name][ref_image]
        axes[row, 0].imshow(img)
        axes[row, 0].set_title(
            f"{model_name}\n{data['label']} ({data['title_extra']})",
            fontsize=10, fontweight='bold'
        )
        axes[row, 0].axis('off')

        for col, pct in enumerate(TOP_PCTS):
            overlay, mass = make_pixel_mask_overlay(img, data['heatmap'], pct)
            axes[row, col + 1].imshow(overlay)
            axes[row, col + 1].set_title(
                f"Top {pct}% pixels\n({mass:.1f}% mass)", fontsize=9
            )
            axes[row, col + 1].axis('off')

    plt.suptitle(
        f"Score-CAM Pixel Importance: {ref_image} \u2014 All 5 Models \u00d7 Multiple Thresholds",
        fontsize=15, fontweight='bold', y=1.01
    )
    plt.tight_layout()
    save_fig(fig, os.path.join(output_dir, f'grid3_multithreshold_{ref_image}'))
    plt.show()

# ============================================================================
# GRID 4: Cumulative Curves — Per Image (all models overlaid)
# ============================================================================
print("\n" + "=" * 60)
print("GRID 4: Cumulative Curves Per Image")
print("=" * 60)

fig, axes = plt.subplots(1, n_images, figsize=(7 * n_images, 6), sharey=True)
if n_images == 1:
    axes = [axes]

for idx, img_name in enumerate(SELECTED_IMAGES):
    ax = axes[idx]

    for model_name in model_names_list:
        data = model_heatmaps[model_name][img_name]
        x_pct, y_pct = compute_cumulative_curve(data['heatmap'])
        if x_pct is not None:
            ax.plot(x_pct, y_pct,
                    color=MODEL_COLORS[model_name],
                    linewidth=2.5, alpha=0.85,
                    label=model_name)

    # Diagonal reference (uniform)
    ax.plot([0, 100], [0, 100], color='grey', linestyle=':', linewidth=1.5, alpha=0.5)

    for t in [50, 80, 90]:
        ax.axhline(y=t, color='grey', linestyle='--', alpha=0.3, linewidth=0.8)

    ax.set_xlabel('% of pixels (sorted by importance)', fontsize=12)
    if idx == 0:
        ax.set_ylabel('Cumulative % of activation mass', fontsize=12)
    ax.set_title(f'{img_name}', fontsize=13, fontweight='bold')
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 105)
    ax.legend(fontsize=9, loc='lower right', framealpha=0.9)

plt.suptitle(
    'Score-CAM Cumulative Distribution: Per Image, All 5 Models',
    fontsize=16, fontweight='bold', y=1.02
)
plt.tight_layout()
save_fig(fig, os.path.join(output_dir, 'grid4_cumulative_per_image'))
plt.show()

# ============================================================================
# GRID 5: Cumulative Curves — All Models, All Images Combined
# ============================================================================
print("\n" + "=" * 60)
print("GRID 5: Combined Cumulative Curves")
print("=" * 60)

fig, ax = plt.subplots(figsize=(10, 7))

for model_name in model_names_list:
    color = MODEL_COLORS[model_name]
    for img_idx, img_name in enumerate(SELECTED_IMAGES):
        data = model_heatmaps[model_name][img_name]
        x_pct, y_pct = compute_cumulative_curve(data['heatmap'])
        if x_pct is not None:
            lbl = model_name if img_idx == 0 else None
            ax.plot(x_pct, y_pct,
                    color=color, linewidth=1.8, alpha=0.5,
                    label=lbl)

# Diagonal reference
ax.plot([0, 100], [0, 100], color='grey', linestyle=':', linewidth=1.5, alpha=0.5,
        label='Uniform (no concentration)')

for t in [50, 80, 90]:
    ax.axhline(y=t, color='grey', linestyle='--', alpha=0.3, linewidth=0.8)

ax.set_xlabel('% of pixels (sorted by importance)', fontsize=13)
ax.set_ylabel('Cumulative % of activation mass', fontsize=13)
ax.set_title('Score-CAM Long-Tail Distribution: All 5 Models, All Selected Images',
             fontsize=15, fontweight='bold', pad=15)
ax.set_xlim(0, 100)
ax.set_ylim(0, 105)
ax.legend(fontsize=10, loc='lower right', framealpha=0.9, edgecolor='#cccccc')

plt.tight_layout()
save_fig(fig, os.path.join(output_dir, 'grid5_cumulative_combined'))
plt.show()

# ============================================================================
# GRID 6: Cumulative Curves — Per Model (images overlaid with linestyles)
# ============================================================================
print("\n" + "=" * 60)
print("GRID 6: Cumulative Curves Per Model")
print("=" * 60)

fig, axes = plt.subplots(1, len(model_names_list),
                         figsize=(5 * len(model_names_list), 5.5), sharey=True)

img_linestyles = ['-', '--', ':']

for i, model_name in enumerate(model_names_list):
    ax = axes[i]
    color = MODEL_COLORS[model_name]

    for j, img_name in enumerate(SELECTED_IMAGES):
        data = model_heatmaps[model_name][img_name]
        x_pct, y_pct = compute_cumulative_curve(data['heatmap'])
        if x_pct is not None:
            ls = img_linestyles[j % len(img_linestyles)]
            ax.plot(x_pct, y_pct,
                    color=color, linewidth=2.5, alpha=0.85,
                    linestyle=ls,
                    label=f"{img_name} ({data['label']})")

    ax.plot([0, 100], [0, 100], color='grey', linestyle=':', linewidth=1, alpha=0.4)

    for t in [50, 80, 90]:
        ax.axhline(y=t, color='grey', linestyle='--', alpha=0.25, linewidth=0.8)

    ax.set_title(model_name, fontsize=12, fontweight='bold')
    ax.set_xlabel('% of pixels', fontsize=10)
    if i == 0:
        ax.set_ylabel('Cumulative % of activation mass', fontsize=11)
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 105)
    ax.legend(fontsize=8, loc='lower right', framealpha=0.9)

plt.suptitle(
    'Score-CAM Cumulative Distribution: Per Model, All Selected Images',
    fontsize=15, fontweight='bold', y=1.02
)
plt.tight_layout()
save_fig(fig, os.path.join(output_dir, 'grid6_cumulative_per_model'))
plt.show()

# ============================================================================
# SUMMARY TABLE
# ============================================================================
print("\n" + "=" * 60)
print("SUMMARY TABLE")
print("=" * 60)

THRESHOLDS_REPORT = [50, 80, 90, 95]

print(f"\n{'Image':<18} {'Model':<18}", end="")
for t in THRESHOLDS_REPORT:
    print(f" Top->{t}%", end="")
print()
print("-" * (18 + 18 + 10 * len(THRESHOLDS_REPORT)))

for img_name in SELECTED_IMAGES:
    for mn in model_names_list:
        data = model_heatmaps[mn][img_name]
        hm = data['heatmap']
        flat = hm.flatten()

        print(f"  {img_name:<16} {mn:<18}", end="")

        if flat.sum() > 0:
            flat_norm = flat / flat.sum()
            sorted_vals = np.sort(flat_norm)[::-1]
            cumsum = np.cumsum(sorted_vals)
            for t in THRESHOLDS_REPORT:
                idx = np.searchsorted(cumsum, t / 100)
                pct = (idx + 1) / len(flat) * 100
                print(f" {pct:>7.1f}%", end="")
        else:
            for t in THRESHOLDS_REPORT:
                print(f"     N/A", end="")
        print()
    print()

print(f"\nAll outputs saved to: {output_dir}")
print("=" * 60)

from google.colab import drive
drive.mount('/content/drive')

output_dir = "/content/drive/MyDrive/frost"

!pip freeze > {output_dir}/requirements.txt