# -*- coding: utf-8 -*-
"""neu_bnn_multiclass

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJOewWobpYzWZFNhtajIpRqpjIkOd0FK
"""

!pip install tf-keras-vis

"""End-to-end multiclass Bayesian CNN pipeline for microstructure image
classification with MC Dropout uncertainty and Score-CAM explanations.

This cell:
1. Sets seeds, mounts Google Drive, and defines project paths for a multiclass
   microstructure dataset organized in subfolders (one per class).
2. Loads and resizes images from all class directories, normalizes pixel
   values, encodes class labels, and saves a stratified train/validation/test
   split (with the test split persisted for reuse).
3. Applies extensive data augmentation (rotations, flips) and computes class
   weights to mitigate class imbalance in the multiclass setting.
4. Defines a CNN with MC Dropout layers (Bayesian-style) and a softmax
   output, and implements an MC-dropout prediction routine that returns
   per-class predictive means and total uncertainty.
5. Phase 1: Performs stratified K-fold cross-validation, logging per-fold
   metrics (including per-class precision/recall/F1), and saving training
   curves and confusion matrices to disk.
6. Phase 2: Trains a final multiclass model on the full augmented training
   set using callbacks (checkpointing, learning-rate scheduling, CSV logging),
   then evaluates on the held-out test set with MC Dropout to obtain accuracy,
   macro/weighted F1 scores, confusion matrices, and uncertainty-aware plots.
7. Visualizes misclassified test samples together with their predicted class,
   confidence, and uncertainty, summarizes all performance and uncertainty
   statistics to CSV, and optionally generates Score-CAM heatmaps on selected
   test images for qualitative inspection of class-specific attention patterns.
"""

import cv2
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (classification_report, confusion_matrix, ConfusionMatrixDisplay,
                             accuracy_score, precision_score, recall_score, f1_score)
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Input, Conv2D, MaxPooling2D, GlobalMaxPooling2D,
                                     Dense, BatchNormalization, Dropout)
from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, CSVLogger
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from sklearn.utils import class_weight
from google.colab import drive
import pickle

# ============================================================================
# SETUP & REPRODUCIBILITY
# ============================================================================
sns.set_style("darkgrid")
sns.set_palette("colorblind")

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)
os.environ["TF_DETERMINISTIC_OPS"] = "1"

# Mount Drive
drive.mount('/content/drive')

# Paths
image_directory = '/content/drive/My Drive/frost/frost_non_frost/microstructures'
save_dir = '/content/drive/My Drive/frost/models_saved2'
os.makedirs(save_dir, exist_ok=True)

# Constants
SIZE = 512
BATCH_SIZE = 32
EPOCHS = 25
AUGMENTATION_FACTOR = 11
N_FOLDS = 5

# ============================================================================
# DATA LOADING - MULTICLASS
# ============================================================================
print("Loading images from subdirectories...")
dataset = []
labels = []
class_names = []

# Automatically detect class folders
for class_idx, class_name in enumerate(sorted(os.listdir(image_directory))):
    class_path = os.path.join(image_directory, class_name)

    # Skip if not a directory
    if not os.path.isdir(class_path):
        continue

    class_names.append(class_name)
    print(f"Loading class {class_idx}: {class_name}")

    # Load images from this class
    for image_name in os.listdir(class_path):
        if image_name.lower().endswith(('tif', 'png', 'jpg', 'jpeg')):
            image_path = os.path.join(class_path, image_name)
            image = cv2.imread(image_path)
            if image is None:
                continue
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            image = cv2.resize(image, (SIZE, SIZE))
            dataset.append(image)
            labels.append(class_idx)

# Normalize to [0, 1]
dataset = np.array(dataset, dtype=np.float32) / 255.0
labels = np.array(labels)
NUM_CLASSES = len(class_names)

print(f"\nTotal samples: {len(dataset)}")
print(f"Number of classes: {NUM_CLASSES}")
print(f"Class names: {class_names}")
print(f"Class distribution: {np.unique(labels, return_counts=True)}")

# Save class names for later use
with open(os.path.join(save_dir, 'class_names.pkl'), 'wb') as f:
    pickle.dump(class_names, f)

# ============================================================================
# DATA SPLITTING (CONSISTENT ACROSS ALL MODELS)
# ============================================================================
print("\nCreating train/val/test splits...")
X_train, X_temp, y_train, y_temp = train_test_split(
    dataset, labels, test_size=0.3, random_state=SEED, stratify=labels
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=SEED, stratify=y_temp
)

print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

# Save splits for consistency across models
np.save(os.path.join(save_dir, 'X_test.npy'), X_test)
np.save(os.path.join(save_dir, 'y_test.npy'), y_test)

# ============================================================================
# DATA AUGMENTATION
# ============================================================================
print("\nAugmenting training data...")
train_datagen = ImageDataGenerator(
    rotation_range=30,
    horizontal_flip=True,
    vertical_flip = True,
    fill_mode='reflect'
)

def augment_data(X, y, factor=AUGMENTATION_FACTOR):
    aug_images = []
    aug_labels = []
    for i in range(len(X)):
        image = np.expand_dims(X[i], axis=0)
        label = y[i]
        aug_iter = train_datagen.flow(image, batch_size=1)
        for _ in range(factor):
            aug_images.append(next(aug_iter)[0])
            aug_labels.append(label)

    X_aug = np.concatenate([X, np.array(aug_images)], axis=0).astype(np.float32)
    y_aug = np.concatenate([y, np.array(aug_labels)], axis=0).astype(int)
    return X_aug, y_aug

X_train_aug, y_train_aug = augment_data(X_train, y_train)
print(f"Augmented training data: {X_train_aug.shape}")

# Class weights
class_weights = class_weight.compute_class_weight(
    'balanced',
    classes=np.unique(y_train_aug),
    y=y_train_aug
)
class_weights = dict(enumerate(class_weights))
print(f"Class weights: {class_weights}")

# ============================================================================
# MC DROPOUT LAYER
# ============================================================================
class MCDropout(Dropout):
    def call(self, inputs, training=None):
        return super().call(inputs, training=True)

# ============================================================================
# MULTICLASS BNN MODEL DEFINITION
# ============================================================================
def create_bnn_model(input_shape=(SIZE, SIZE, 3), num_classes=NUM_CLASSES):
    inputs = Input(shape=input_shape)

    # Keep MaxPooling for better feature localization
    x = Conv2D(16, (3, 3), activation='relu')(inputs)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = Conv2D(32, (3, 3), activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = Conv2D(64, (3, 3), activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = Conv2D(128, (3, 3), activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    # Additional conv layer for richer features (better Score-CAM)
    x = Conv2D(190, (3, 3), activation='relu', name='last_conv')(x)
    x = BatchNormalization()(x)

    # Use GlobalMaxPooling for better spatial feature retention
    x = GlobalMaxPooling2D()(x)

    # Larger dense layers for better feature learning
    x = Dense(45, activation='relu', kernel_regularizer=l2(0.0002))(x)
    x = BatchNormalization()(x)
    x = MCDropout(0.5)(x)

    x = Dense(16, activation='relu', kernel_regularizer=l2(0.0002))(x)
    x = BatchNormalization()(x)
    x = MCDropout(0.3)(x)

    outputs = Dense(num_classes, activation='softmax', kernel_regularizer=l2(0.0001))(x)

    model = Model(inputs=inputs, outputs=outputs)
    model.compile(
        optimizer=Adam(learning_rate=0.0002),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# ============================================================================
# MC DROPOUT PREDICTION - MULTICLASS
# ============================================================================
def mc_prediction(model, X, T=20):
    # Returns probabilities for all classes
    predictions = np.array([model(X, training=True).numpy() for _ in range(T)])
    mean_pred = predictions.mean(axis=0)  # Shape: (n_samples, num_classes)
    std_pred = predictions.std(axis=0)    # Shape: (n_samples, num_classes)

    # Total uncertainty: average std across all classes
    total_uncertainty = std_pred.mean(axis=1)

    return mean_pred, std_pred, total_uncertainty

# ============================================================================
# PHASE 1: CROSS-VALIDATION
# ============================================================================
print("\n" + "="*60)
print("PHASE 1: CROSS-VALIDATION")
print("="*60)

skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
cv_results = []

for fold_idx, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train), start=1):
    print(f"\n--- Fold {fold_idx}/{N_FOLDS} ---")

    # Split fold data
    X_fold_train = X_train[train_idx]
    y_fold_train = y_train[train_idx]
    X_fold_val = X_train[val_idx]
    y_fold_val = y_train[val_idx]

    # Augment fold training data
    X_fold_aug, y_fold_aug = augment_data(X_fold_train, y_fold_train)

    # Fold class weights
    fold_cw = class_weight.compute_class_weight(
        'balanced', classes=np.unique(y_fold_aug), y=y_fold_aug
    )
    fold_cw = dict(enumerate(fold_cw))

    # Create and train model
    model = create_bnn_model()
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-6, verbose=0)

    history = model.fit(
        X_fold_aug, y_fold_aug,
        validation_data=(X_fold_val, y_fold_val),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        shuffle=True,
        class_weight=fold_cw,
        callbacks=[reduce_lr],
        verbose=1
    )

    # Get predictions
    y_pred_probs = model.predict(X_fold_val, batch_size=32, verbose=0)
    y_pred = np.argmax(y_pred_probs, axis=1)

    # Calculate metrics
    report = classification_report(y_fold_val, y_pred, output_dict=True, zero_division=0)

    # Print classification report
    print(f"\nClassification Report - Fold {fold_idx}:")
    print(classification_report(y_fold_val, y_pred, target_names=class_names, zero_division=0))

    # PLOT 1: Training curves
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy', linewidth=2)
    plt.plot(history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
    plt.title(f'Accuracy - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss', linewidth=2)
    plt.plot(history.history['val_loss'], label='Val Loss', linewidth=2)
    plt.title(f'Loss - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    plt.suptitle(f'Training Curves - Fold {fold_idx}/{N_FOLDS}', fontsize=16)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'bnn_fold_{fold_idx}_curves.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # PLOT 2: Confusion matrix
    plt.figure(figsize=(10, 8))
    cm = confusion_matrix(y_fold_val, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
    disp.plot(cmap='Blues')
    plt.title(f'Confusion Matrix - Fold {fold_idx}/{N_FOLDS}', fontsize=14, fontweight='bold')
    plt.grid(False)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'bnn_fold_{fold_idx}_confusion.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # Save fold results with per-class metrics
    fold_result = {
        'Fold': fold_idx,
        'Accuracy': report['accuracy'],
        'Macro_Avg_Precision': report['macro avg']['precision'],
        'Macro_Avg_Recall': report['macro avg']['recall'],
        'Macro_Avg_F1': report['macro avg']['f1-score'],
        'Weighted_Avg_F1': report['weighted avg']['f1-score'],
        'Loss': history.history['val_loss'][-1],
    }

    # Add per-class metrics
    for i, class_name in enumerate(class_names):
        if str(i) in report:
            fold_result[f'F1_{class_name}'] = report[str(i)]['f1-score']
            fold_result[f'Precision_{class_name}'] = report[str(i)]['precision']
            fold_result[f'Recall_{class_name}'] = report[str(i)]['recall']

    cv_results.append(fold_result)

    print(f"Accuracy: {fold_result['Accuracy']:.4f}, Macro F1: {fold_result['Macro_Avg_F1']:.4f}")

    # Clear memory
    del model, history, y_pred_probs, y_pred
    tf.keras.backend.clear_session()

# Save CV results
cv_df = pd.DataFrame(cv_results)
cv_df.to_csv(os.path.join(save_dir, 'bnn_cv_results.csv'), index=False)

print("\n" + "="*60)
print("CROSS-VALIDATION SUMMARY")
print("="*60)
print(cv_df.describe())

# ============================================================================
# PHASE 2: FINAL MODEL TRAINING
# ============================================================================
print("\n" + "="*60)
print("PHASE 2: FINAL MODEL TRAINING")
print("="*60)

# Train final model on full augmented training data
final_model = create_bnn_model()

checkpoint_cb = ModelCheckpoint(
    filepath=os.path.join(save_dir, 'bnn_best_model_multiclass.h5'),
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-6, verbose=1)
csv_logger = CSVLogger(os.path.join(save_dir, 'bnn_training_log_multiclass.csv'))

final_history = final_model.fit(
    X_train_aug, y_train_aug,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    class_weight=class_weights,
    callbacks=[checkpoint_cb, reduce_lr, csv_logger],
    verbose=1
)

# ============================================================================
# FINAL TEST SET EVALUATION
# ============================================================================
print("\n" + "="*60)
print("TEST SET EVALUATION")
print("="*60)

# MC Dropout predictions on test set
mean_test_preds, std_test_preds, total_uncertainty = mc_prediction(final_model, X_test, T=20)
y_test_pred = np.argmax(mean_test_preds, axis=1)

# Classification report
print("\nClassification Report - Test Set:")
print(classification_report(y_test, y_test_pred, target_names=class_names))

# PLOT 1: Training curves for final model
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(final_history.history['accuracy'], label='Train Accuracy', linewidth=2)
plt.plot(final_history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
plt.title('Model Accuracy - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(final_history.history['loss'], label='Train Loss', linewidth=2)
plt.plot(final_history.history['val_loss'], label='Val Loss', linewidth=2)
plt.title('Model Loss - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.suptitle('Final Model Training Curves', fontsize=16)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'bnn_final_training_curves.png'), dpi=300, bbox_inches='tight')
plt.show()

# PLOT 2: Confusion Matrix for test set
plt.figure(figsize=(10, 8))
cm = confusion_matrix(y_test, y_test_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap='Blues')
plt.title("Confusion Matrix - Test Set", fontsize=14, fontweight='bold')
plt.grid(False)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'bnn_test_confusion_matrix.png'), dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# UNCERTAINTY ANALYSIS
# ============================================================================
print("\n" + "="*60)
print("UNCERTAINTY ANALYSIS")
print("="*60)

# Uncertainty histogram
plt.figure(figsize=(8, 6))
plt.hist(total_uncertainty, bins=50, color='mediumslateblue', edgecolor='black')
plt.title('Prediction Uncertainty (MC Dropout Std Dev)')
plt.xlabel('Average Standard Deviation')
plt.ylabel('Frequency')
plt.grid(True)
plt.savefig(os.path.join(save_dir, 'bnn_uncertainty_hist.png'), dpi=300, bbox_inches='tight')
plt.show()

# Confidence vs Uncertainty scatter
max_confidence = mean_test_preds.max(axis=1)
plt.figure(figsize=(8, 6))
plt.scatter(max_confidence, total_uncertainty, alpha=0.6, c=y_test, cmap='tab10', edgecolor='k')
plt.colorbar(label='True Class', ticks=range(NUM_CLASSES))
plt.title("MC Dropout: Confidence vs Uncertainty")
plt.xlabel("Max Predicted Probability")
plt.ylabel("Average Standard Deviation (Uncertainty)")
plt.grid(True)
plt.savefig(os.path.join(save_dir, 'bnn_confidence_uncertainty.png'), dpi=300, bbox_inches='tight')
plt.show()

# Misclassified images
misclassified_idx = np.where(y_test_pred != y_test)[0]
print(f"\nTotal misclassified: {len(misclassified_idx)}")

if len(misclassified_idx) > 0:
    n_samples = min(12, len(misclassified_idx))
    plt.figure(figsize=(16, 10))

    for i, idx in enumerate(misclassified_idx[:n_samples]):
        plt.subplot(3, 4, i + 1)
        img = X_test[idx]
        plt.imshow(np.clip(img, 0, 1))
        plt.axis('off')

        true_class = class_names[y_test[idx]]
        pred_class = class_names[y_test_pred[idx]]
        confidence = mean_test_preds[idx, y_test_pred[idx]]
        unc = total_uncertainty[idx]

        plt.title(
            f"True: {true_class}\n"
            f"Pred: {pred_class}\n"
            f"Conf: {confidence:.2f}\n"
            f"Unc: {unc:.3f}",
            fontsize=9
        )

    plt.suptitle("Misclassified Test Images", fontsize=18)
    plt.tight_layout(rect=(0, 0, 1, 0.94))
    plt.savefig(os.path.join(save_dir, 'bnn_misclassified.png'), dpi=300, bbox_inches='tight')
    plt.show()

# ============================================================================
# SAVE FINAL RESULTS
# ============================================================================
final_results = {
    'Model': 'BNN_Multiclass',
    'Num_Classes': NUM_CLASSES,
    'Test_Accuracy': accuracy_score(y_test, y_test_pred),
    'Test_Macro_Precision': precision_score(y_test, y_test_pred, average='macro'),
    'Test_Macro_Recall': recall_score(y_test, y_test_pred, average='macro'),
    'Test_Macro_F1': f1_score(y_test, y_test_pred, average='macro'),
    'Test_Weighted_F1': f1_score(y_test, y_test_pred, average='weighted'),
    'CV_Accuracy_Mean': cv_df['Accuracy'].mean(),
    'CV_Accuracy_Std': cv_df['Accuracy'].std(),
    'Mean_Uncertainty': np.mean(total_uncertainty),
    'Misclassifications': len(misclassified_idx)
}

pd.DataFrame([final_results]).to_csv(
    os.path.join(save_dir, 'bnn_final_results.csv'), index=False
)

print("\n" + "="*60)
print("FINAL RESULTS")
print("="*60)
for key, value in final_results.items():
    print(f"{key}: {value}")

print("\n✅ All results saved to:", save_dir)

# ============================================================================
# SCORE-CAM VISUALIZATION (Optional Analysis)
# ============================================================================
RUN_SCORECAM = True  # Set to False to skip

if RUN_SCORECAM:
    print("\n" + "="*60)
    print("SCORE-CAM VISUALIZATION")
    print("="*60)

    try:
        from tf_keras_vis.scorecam import ScoreCAM
        from tf_keras_vis.utils.model_modifiers import ReplaceToLinear

        # Load best model
        print("Loading best model for Score-CAM...")
        best_model = tf.keras.models.load_model(
            os.path.join(save_dir, 'bnn_best_model_multiclass.h5'),
            custom_objects={'MCDropout': MCDropout}
        )

        # Score function for multiclass
        def score_function(output):
            # For each sample, return the predicted class score
            return tf.reduce_max(output, axis=-1)

        # Create Score-CAM object with model modifier
        def model_modifier(m):
            m.layers[-1].activation = tf.keras.activations.linear
            return m

        scorecam = ScoreCAM(best_model, model_modifier=model_modifier)

        # Select diverse samples to visualize
        correct_idx = np.where(y_test_pred == y_test)[0]
        uncertain_idx = np.argsort(total_uncertainty)[-10:]

        # Get sample indices
        sample_indices = []
        if len(correct_idx) >= 3:
            sample_indices.extend(correct_idx[:3])
        if len(misclassified_idx) >= 3:
            sample_indices.extend(misclassified_idx[:3])
        if len(uncertain_idx) >= 3:
            sample_indices.extend(uncertain_idx[:3])

        sample_indices = np.array(sample_indices[:9])

        if len(sample_indices) > 0:
            print(f"Generating Score-CAM for {len(sample_indices)} samples...")

            X_samples = X_test[sample_indices]
            cam = scorecam(
                score_function,
                X_samples,
                penultimate_layer='last_conv'
            )

            # Visualize
            n_rows = (len(sample_indices) + 2) // 3
            fig, axes = plt.subplots(n_rows, 3, figsize=(15, 5*n_rows))
            if n_rows > 1:
                axes = axes.ravel()
            elif n_rows == 1:
                axes = axes if isinstance(axes, np.ndarray) else np.array(axes)

            for i, idx in enumerate(sample_indices):
                ax = axes[i]
                img = X_test[idx]

                # Overlay CAM
                heatmap = cam[i]
                heatmap = np.uint8(255 * heatmap)
                heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
                heatmap = cv2.resize(heatmap, (SIZE, SIZE))

                superimposed = cv2.addWeighted(
                    (img * 255).astype(np.uint8), 0.6,
                    heatmap, 0.4, 0
                )

                ax.imshow(superimposed)
                ax.axis('off')

                true_label = class_names[y_test[idx]]
                pred_label = class_names[y_test_pred[idx]]
                confidence = mean_test_preds[idx, y_test_pred[idx]]
                unc = total_uncertainty[idx]

                status = "✓" if y_test[idx] == y_test_pred[idx] else "✗"
                ax.set_title(
                    f"{status} True: {true_label} | Pred: {pred_label}\n"
                    f"Confidence: {confidence:.2f} | Uncertainty: {unc:.3f}",
                    fontsize=10
                )

            for i in range(len(sample_indices), len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM Visualizations - BNN Multiclass", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'bnn_scorecam.png'), dpi=300, bbox_inches='tight')
            plt.show()

            print(f"✓ Score-CAM visualizations saved")
        else:
            print("⚠ Not enough samples for Score-CAM visualization")

    except ImportError:
        print("⚠ tf-keras-vis not installed. Run: pip install tf-keras-vis")
    except Exception as e:
        print(f"⚠ Score-CAM failed: {str(e)}")
        import traceback
        print(traceback.format_exc())
else:
    print("\n⏭ Skipping Score-CAM (set RUN_SCORECAM=True to enable)")

print("\n" + "="*60)
print("✅ ANALYSIS COMPLETE")
print("="*60)

"""Additional multiclass Score-CAM visualizations for detailed inspection of
BNN attention and uncertainty patterns.

This cell:
1. Reuses the trained multiclass BNN, ScoreCAM object, and MC Dropout-based
   predictions to generate supplementary heatmaps on held-out data.
2. Produces Score-CAM overlays for: (a) randomly sampled test images
   (showing predicted class, confidence, and uncertainty), (b) selected
   validation images (correct and misclassified), and (c) correctly classified
   test samples from each class to visualize per-class attention patterns.
3. Compares low- vs high-uncertainty correctly classified test samples via
   paired Score-CAM panels, highlighting how spatial focus changes across
   confidence regimes.
4. Saves all figure panels (random test, validation subset, per-class, and
   low/high-uncertainty comparisons) to disk, providing a comprehensive,
   qualitative complement to the quantitative uncertainty analyses.
"""

# ============================================================================
# ADDITIONAL SCORE-CAM VISUALIZATIONS - MULTICLASS
# ============================================================================
print("\n" + "="*60)
print("ADDITIONAL SCORE-CAM ANALYSIS")
print("="*60)

if RUN_SCORECAM:
    try:
        # We already have the ScoreCAM object from previous cell
        print("Generating additional Score-CAM visualizations...")

        # Option 1: Show more test samples (random selection)
        print("\n--- Random Test Samples ---")
        np.random.seed(42)  # For reproducible selection
        random_test_indices = np.random.choice(len(X_test), size=6, replace=False)

        X_random = X_test[random_test_indices]
        cam_random = scorecam(score_function, X_random, penultimate_layer='last_conv')

        fig, axes = plt.subplots(2, 3, figsize=(15, 10))
        axes = axes.ravel()

        for i, idx in enumerate(random_test_indices):
            ax = axes[i]

            # Original image
            img = X_test[idx]

            # Overlay CAM
            heatmap = cam_random[i]
            heatmap = np.uint8(255 * heatmap)
            heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
            heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
            heatmap = cv2.resize(heatmap, (SIZE, SIZE))

            # Superimpose
            superimposed = cv2.addWeighted(
                (img * 255).astype(np.uint8), 0.6,
                heatmap, 0.4, 0
            )

            ax.imshow(superimposed)
            ax.axis('off')

            # Get prediction for this sample
            pred_class = y_test_pred[idx]
            true_class = y_test[idx]
            confidence = mean_test_preds[idx, pred_class]
            uncertainty = total_uncertainty[idx]

            true_label = class_names[true_class]
            pred_label = class_names[pred_class]
            status = "✓" if true_class == pred_class else "✗"

            ax.set_title(
                f"{status} True: {true_label} | Pred: {pred_label}\n"
                f"Conf: {confidence:.2f} | Unc: {uncertainty:.3f}",
                fontsize=10
            )

        plt.suptitle("Score-CAM: Random Test Samples", fontsize=16, fontweight='bold')
        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, 'bnn_scorecam_random.png'), dpi=300, bbox_inches='tight')
        plt.show()

        # Option 2: Show validation samples
        print("\n--- Validation Samples ---")

        # Get validation predictions
        val_pred_probs = final_model.predict(X_val, batch_size=32, verbose=0)
        val_pred = np.argmax(val_pred_probs, axis=1)

        # Select interesting validation samples
        val_correct = np.where(val_pred == y_val)[0]
        val_misclassified = np.where(val_pred != y_val)[0]

        val_sample_indices = []
        if len(val_correct) >= 3:
            val_sample_indices.extend(val_correct[:3])
        if len(val_misclassified) >= 3:
            val_sample_indices.extend(val_misclassified[:3])

        if len(val_sample_indices) > 0:
            val_sample_indices = np.array(val_sample_indices[:6])  # Max 6 samples

            X_val_samples = X_val[val_sample_indices]
            cam_val = scorecam(score_function, X_val_samples, penultimate_layer='last_conv')

            n_val_samples = len(val_sample_indices)
            n_rows_val = (n_val_samples + 2) // 3

            fig, axes = plt.subplots(n_rows_val, 3, figsize=(15, 5*n_rows_val))
            if n_rows_val == 1:
                axes = axes if isinstance(axes, np.ndarray) else np.array([axes])
            else:
                axes = axes.ravel()

            for i, idx in enumerate(val_sample_indices):
                ax = axes[i]

                # Original image
                img = X_val[idx]

                # Overlay CAM
                heatmap = cam_val[i]
                heatmap = np.uint8(255 * heatmap)
                heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
                heatmap = cv2.resize(heatmap, (SIZE, SIZE))

                # Superimpose
                superimposed = cv2.addWeighted(
                    (img * 255).astype(np.uint8), 0.6,
                    heatmap, 0.4, 0
                )

                ax.imshow(superimposed)
                ax.axis('off')

                # Validation predictions
                true_label = class_names[y_val[idx]]
                pred_label = class_names[val_pred[idx]]
                pred_prob = val_pred_probs[idx, val_pred[idx]]
                status = "✓" if y_val[idx] == val_pred[idx] else "✗"

                ax.set_title(
                    f"{status} True: {true_label} | Pred: {pred_label}\n"
                    f"Confidence: {pred_prob:.2f}",
                    fontsize=10
                )

            # Hide unused subplots
            for i in range(len(val_sample_indices), len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: Validation Samples", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'bnn_scorecam_validation.png'), dpi=300, bbox_inches='tight')
            plt.show()
        else:
            print("No validation samples available for Score-CAM")

        # Option 3: Per-Class Analysis (show samples from each class)
        print("\n--- Per-Class Analysis ---")

        # Get correctly classified samples from each class
        per_class_samples = []
        for class_idx in range(NUM_CLASSES):
            class_test_indices = np.where(y_test == class_idx)[0]
            class_correct = [idx for idx in class_test_indices if y_test_pred[idx] == class_idx]

            # Take up to 2 samples per class
            if len(class_correct) >= 2:
                per_class_samples.extend(class_correct[:2])
            elif len(class_correct) == 1:
                per_class_samples.append(class_correct[0])

        if len(per_class_samples) >= 3:
            per_class_samples = per_class_samples[:9]  # Max 9 samples (3x3 grid)

            X_class_samples = X_test[per_class_samples]
            cam_class = scorecam(score_function, X_class_samples, penultimate_layer='last_conv')

            n_samples = len(per_class_samples)
            n_rows = (n_samples + 2) // 3

            fig, axes = plt.subplots(n_rows, 3, figsize=(15, 5*n_rows))
            if n_rows == 1:
                axes = axes if isinstance(axes, np.ndarray) else np.array([axes])
            else:
                axes = axes.ravel()

            for i, idx in enumerate(per_class_samples):
                ax = axes[i]

                # Original image
                img = X_test[idx]

                # Overlay CAM
                heatmap = cam_class[i]
                heatmap = np.uint8(255 * heatmap)
                heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
                heatmap = cv2.resize(heatmap, (SIZE, SIZE))

                # Superimpose
                superimposed = cv2.addWeighted(
                    (img * 255).astype(np.uint8), 0.6,
                    heatmap, 0.4, 0
                )

                ax.imshow(superimposed)
                ax.axis('off')

                true_label = class_names[y_test[idx]]
                pred_class = y_test_pred[idx]
                confidence = mean_test_preds[idx, pred_class]
                uncertainty = total_uncertainty[idx]

                ax.set_title(
                    f"✓ {true_label}\n"
                    f"Conf: {confidence:.2f} | Unc: {uncertainty:.3f}",
                    fontsize=11
                )

            # Hide unused subplots
            for i in range(len(per_class_samples), len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: Per-Class Attention Patterns",
                        fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'bnn_scorecam_per_class.png'), dpi=300, bbox_inches='tight')
            plt.show()

        # Option 4: High vs Low Uncertainty Comparison
        print("\n--- Uncertainty Comparison ---")

        # Get highest and lowest uncertainty samples (that are correctly classified)
        correct_indices = np.where(y_test_pred == y_test)[0]
        correct_uncertainties = total_uncertainty[correct_indices]

        # Sort by uncertainty
        sorted_correct_idx = correct_indices[np.argsort(correct_uncertainties)]

        low_unc_samples = sorted_correct_idx[:3]  # 3 lowest uncertainty
        high_unc_samples = sorted_correct_idx[-3:]  # 3 highest uncertainty

        uncertainty_samples = np.concatenate([low_unc_samples, high_unc_samples])

        if len(uncertainty_samples) >= 4:
            X_unc_samples = X_test[uncertainty_samples]
            cam_unc = scorecam(score_function, X_unc_samples, penultimate_layer='last_conv')

            fig, axes = plt.subplots(2, 3, figsize=(15, 10))
            axes = axes.ravel()

            for i, idx in enumerate(uncertainty_samples):
                ax = axes[i]

                # Original image
                img = X_test[idx]

                # Overlay CAM
                heatmap = cam_unc[i]
                heatmap = np.uint8(255 * heatmap)
                heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
                heatmap = cv2.resize(heatmap, (SIZE, SIZE))

                # Superimpose
                superimposed = cv2.addWeighted(
                    (img * 255).astype(np.uint8), 0.6,
                    heatmap, 0.4, 0
                )

                ax.imshow(superimposed)
                ax.axis('off')

                true_label = class_names[y_test[idx]]
                pred_class = y_test_pred[idx]
                confidence = mean_test_preds[idx, pred_class]
                uncertainty = total_uncertainty[idx]

                unc_level = "LOW" if i < 3 else "HIGH"

                ax.set_title(
                    f"✓ {true_label} ({unc_level} UNC)\n"
                    f"Conf: {confidence:.2f} | Unc: {uncertainty:.3f}",
                    fontsize=10
                )

            plt.suptitle("Score-CAM: Low Uncertainty (Top) vs High Uncertainty (Bottom)",
                        fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'bnn_scorecam_uncertainty.png'), dpi=300, bbox_inches='tight')
            plt.show()

        print("✓ Additional Score-CAM visualizations complete!")

    except Exception as e:
        print(f"⚠ Additional Score-CAM failed: {str(e)}")
        import traceback
        print(traceback.format_exc())

else:
    print("⏭ Skipping additional Score-CAM (RUN_SCORECAM is False)")

print("\n" + "="*60)
print("✅ ALL VISUALIZATIONS COMPLETE")
print("="*60)