# -*- coding: utf-8 -*-
"""neu_resnet_multiclass

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAXIN23h0VhQ2p5uJVwxHzqS9nL3I1XL

Transfer-learning ResNet50 multiclass pipeline for microstructure image
classification, with stratified evaluation, rich misclassification logs, and
multiclass Score-CAM explainability.

This cell:
1. Sets seeds, mounts Google Drive, loads a folder-structured multiclass
   microstructure dataset (one subdirectory per class), builds a stable
   class-to-label mapping, resizes/normalizes images, and creates a stratified
   train/validation/test split while saving test data and mappings for reuse.
2. Applies strong data augmentation and class weighting to handle limited and
   imbalanced data, converts labels to one-hot encodings, and defines a
   ResNet50-based model (ImageNet backbone with its later layers unfrozen)
   followed by L2-regularized dense layers and dropout with a softmax output
   for multiclass prediction.
3. Phase 1: Runs stratified K-fold cross-validation, logging accuracy, macro
   and weighted averages, and per-class F1 scores, while saving training
   curves and confusion matrices for each fold and aggregating results to a
   cross-validation summary CSV.
4. Phase 2: Trains a final ResNet50 model on the full augmented training set
   with checkpointing, learning-rate scheduling, and CSV logging, evaluates it
   on the held-out test set, generates a confusion matrix and a per-class
   precision/recall/F1 bar chart, and saves overall performance metrics and
   misclassification counts to CSV.
5. Visualizes misclassified test images with true/predicted labels and
   confidences, writes a detailed misclassification table (including full
   class probability vectors) and a summary of misclassification patterns, and
   implements a multiclass Score-CAM for ResNet50 that (a) produces triplets
   of original/heatmap/overlay for predicted-class attention and (b) generates
   all-class CAM comparison panels for selected samples, revealing class-
   specific attention patterns across the entire label set.
"""

import cv2
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (classification_report, confusion_matrix, ConfusionMatrixDisplay,
                             accuracy_score, precision_score, recall_score, f1_score)
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Input, GlobalAveragePooling2D,
                                     Dense, BatchNormalization, Dropout)
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, CSVLogger
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from sklearn.utils import class_weight
from google.colab import drive
import pickle

# ============================================================================
# SETUP & REPRODUCIBILITY
# ============================================================================
sns.set_style("darkgrid")
sns.set_palette("colorblind")

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)
os.environ["TF_DETERMINISTIC_OPS"] = "1"

# Mount Drive
drive.mount('/content/drive')

# Paths
image_directory = '/content/drive/My Drive/frost/frost_non_frost/microstructures'
save_dir = '/content/drive/My Drive/frost/models_saved/multiclass2'
os.makedirs(save_dir, exist_ok=True)

# Constants
SIZE = 512
BATCH_SIZE = 32
EPOCHS = 20
AUGMENTATION_FACTOR = 11
N_FOLDS = 5

# ============================================================================
# DATA LOADING - MULTICLASS
# ============================================================================
print("Loading images from subdirectories...")
dataset = []
labels = []
class_names = []

# Get all subdirectories (each represents a class)
subdirs = [d for d in os.listdir(image_directory)
           if os.path.isdir(os.path.join(image_directory, d))]
subdirs.sort()  # Ensure consistent ordering

print(f"Found {len(subdirs)} classes: {subdirs}")

# Create class name to label mapping
class_to_label = {name: idx for idx, name in enumerate(subdirs)}
label_to_class = {idx: name for name, idx in class_to_label.items()}

print(f"\nClass mapping:")
for name, label in class_to_label.items():
    print(f"  {label}: {name}")

# Load images from each class subdirectory
for class_name in subdirs:
    class_path = os.path.join(image_directory, class_name)
    label = class_to_label[class_name]

    image_count = 0
    for image_name in os.listdir(class_path):
        if image_name.lower().endswith(('tif', 'png', 'jpg', 'jpeg', 'bmp')):
            image_path = os.path.join(class_path, image_name)
            image = cv2.imread(image_path)
            if image is None:
                continue
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            image = cv2.resize(image, (SIZE, SIZE))
            dataset.append(image)
            labels.append(label)
            image_count += 1

    print(f"Loaded {image_count} images from class '{class_name}' (label {label})")

# Normalize to [0, 1]
dataset = np.array(dataset, dtype=np.float32) / 255.0
labels = np.array(labels)
num_classes = len(subdirs)

print(f"\nTotal samples: {len(dataset)}")
print(f"Number of classes: {num_classes}")
unique, counts = np.unique(labels, return_counts=True)
for u, c in zip(unique, counts):
    print(f"  Class {u} ({label_to_class[u]}): {c} samples")

# Save class mapping
with open(os.path.join(save_dir, 'class_mapping.pkl'), 'wb') as f:
    pickle.dump({'class_to_label': class_to_label, 'label_to_class': label_to_class}, f)

# ============================================================================
# DATA SPLITTING (CONSISTENT ACROSS ALL MODELS)
# ============================================================================
print("\nCreating train/val/test splits...")
X_train, X_temp, y_train, y_temp = train_test_split(
    dataset, labels, test_size=0.3, random_state=SEED, stratify=labels
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=SEED, stratify=y_temp
)

print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

# Save splits for consistency
np.save(os.path.join(save_dir, 'X_test.npy'), X_test)
np.save(os.path.join(save_dir, 'y_test.npy'), y_test)

# ============================================================================
# DATA AUGMENTATION
# ============================================================================
print("\nAugmenting training data...")
train_datagen = ImageDataGenerator(
    rotation_range=30,
    horizontal_flip=True,
    vertical_flip=True,
    fill_mode='reflect'
)

def augment_data(X, y, factor=AUGMENTATION_FACTOR):
    aug_images = []
    aug_labels = []
    for i in range(len(X)):
        image = np.expand_dims(X[i], axis=0)
        label = y[i]
        aug_iter = train_datagen.flow(image, batch_size=1)
        for _ in range(factor):
            aug_images.append(next(aug_iter)[0])
            aug_labels.append(label)

    X_aug = np.concatenate([X, np.array(aug_images)], axis=0).astype(np.float32)
    y_aug = np.concatenate([y, np.array(aug_labels)], axis=0).astype(int)
    return X_aug, y_aug

X_train_aug, y_train_aug = augment_data(X_train, y_train)
print(f"Augmented training data: {X_train_aug.shape}")

# Class weights for multiclass
class_weights = class_weight.compute_class_weight(
    'balanced',
    classes=np.unique(y_train_aug),
    y=y_train_aug
)
class_weights = dict(enumerate(class_weights))
print(f"Class weights: {class_weights}")

# Convert labels to categorical for training
y_train_aug_cat = to_categorical(y_train_aug, num_classes)
y_val_cat = to_categorical(y_val, num_classes)
y_test_cat = to_categorical(y_test, num_classes)

# ============================================================================
# MOBILENETV2 MODEL DEFINITION - MULTICLASS
# ============================================================================
def create_resnet_model(input_shape=(SIZE, SIZE, 3), num_classes=num_classes):
    # Base MobileNetV2
    base_model = ResNet50(include_top=False, weights='imagenet', input_shape=input_shape)

    # Freeze all but the last 15 layers
    for layer in base_model.layers[:-25]:
        layer.trainable = False
    for layer in base_model.layers[-25:]:
        layer.trainable = True

    # Functional graph
    inputs = Input(shape=input_shape)
    x = base_model(inputs, training=False)
    x = GlobalAveragePooling2D()(x)

    x = Dense(128, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.5)(x)

    x = Dense(64, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.4)(x)

    # Output layer - softmax for multiclass
    outputs = Dense(num_classes, activation='softmax', kernel_regularizer=l2(0.0001))(x)

    model = Model(inputs, outputs)

    model.compile(
        optimizer=Adam(learning_rate=3e-5),
        loss='categorical_crossentropy',  # Changed from binary_crossentropy
        metrics=['accuracy']
    )
    return model

# ============================================================================
# PHASE 1: CROSS-VALIDATION
# ============================================================================
print("\n" + "="*60)
print("PHASE 1: CROSS-VALIDATION")
print("="*60)

skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
cv_results = []

for fold_idx, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train), start=1):
    print(f"\n--- Fold {fold_idx}/{N_FOLDS} ---")

    # Split fold data
    X_fold_train = X_train[train_idx]
    y_fold_train = y_train[train_idx]
    X_fold_val = X_train[val_idx]
    y_fold_val = y_train[val_idx]

    # Augment fold training data
    X_fold_aug, y_fold_aug = augment_data(X_fold_train, y_fold_train)
    y_fold_aug_cat = to_categorical(y_fold_aug, num_classes)
    y_fold_val_cat = to_categorical(y_fold_val, num_classes)

    # Fold class weights
    fold_cw = class_weight.compute_class_weight(
        'balanced', classes=np.unique(y_fold_aug), y=y_fold_aug
    )
    fold_cw = dict(enumerate(fold_cw))

    # Create and train model
    model = create_resnet_model()
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-7, verbose=0)

    history = model.fit(
        X_fold_aug, y_fold_aug_cat,
        validation_data=(X_fold_val, y_fold_val_cat),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        shuffle=True,
        class_weight=fold_cw,
        callbacks=[reduce_lr],
        verbose=1
    )

    # Get predictions
    y_pred_probs = model.predict(X_fold_val, batch_size=32, verbose=0)
    y_pred = np.argmax(y_pred_probs, axis=1)

    # Calculate metrics
    report = classification_report(y_fold_val, y_pred, output_dict=True, zero_division=0)

    # Print classification report
    print(f"\nClassification Report - Fold {fold_idx}:")
    print(classification_report(y_fold_val, y_pred,
                                target_names=[label_to_class[i] for i in range(num_classes)],
                                zero_division=0))

    # PLOT 1: Training curves
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy', linewidth=2)
    plt.plot(history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
    plt.title(f'Accuracy - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss', linewidth=2)
    plt.plot(history.history['val_loss'], label='Val Loss', linewidth=2)
    plt.title(f'Loss - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    plt.suptitle(f'Training Curves - Fold {fold_idx}/{N_FOLDS}', fontsize=16)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'resnet_fold_{fold_idx}_curves.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # PLOT 2: Confusion matrix
    plt.figure(figsize=(10, 8))
    cm = confusion_matrix(y_fold_val, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                                   display_labels=[label_to_class[i] for i in range(num_classes)])
    disp.plot(cmap='Blues', xticks_rotation=45)
    plt.title(f'Confusion Matrix - Fold {fold_idx}/{N_FOLDS}', fontsize=14, fontweight='bold')
    plt.grid(False)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'resnet_fold_{fold_idx}_confusion.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # Save fold results
    fold_result = {
        'Fold': fold_idx,
        'Accuracy': report['accuracy'],
        'Macro_Avg_Precision': report['macro avg']['precision'],
        'Macro_Avg_Recall': report['macro avg']['recall'],
        'Macro_Avg_F1': report['macro avg']['f1-score'],
        'Weighted_Avg_Precision': report['weighted avg']['precision'],
        'Weighted_Avg_Recall': report['weighted avg']['recall'],
        'Weighted_Avg_F1': report['weighted avg']['f1-score'],
        'Loss': history.history['val_loss'][-1]
    }

    # Add per-class F1 scores
    for i in range(num_classes):
        class_label = str(i)
        if class_label in report:
            fold_result[f'F1_{label_to_class[i]}'] = report[class_label]['f1-score']

    cv_results.append(fold_result)

    print(f"Accuracy: {fold_result['Accuracy']:.4f}, Macro F1: {fold_result['Macro_Avg_F1']:.4f}")

    # Clear memory
    del model, history, y_pred_probs, y_pred
    tf.keras.backend.clear_session()

# Save CV results
cv_df = pd.DataFrame(cv_results)
cv_df.to_csv(os.path.join(save_dir, 'resnet_cv_results.csv'), index=False)

print("\n" + "="*60)
print("CROSS-VALIDATION SUMMARY")
print("="*60)
print(cv_df.describe())

# ============================================================================
# PHASE 2: FINAL MODEL TRAINING
# ============================================================================
print("\n" + "="*60)
print("PHASE 2: FINAL MODEL TRAINING")
print("="*60)

# Train final model on full augmented training data
final_model = create_resnet_model()

checkpoint_cb = ModelCheckpoint(
    filepath=os.path.join(save_dir, 'resnet_best_model_multiclass.h5'),
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-7, verbose=1)
csv_logger = CSVLogger(os.path.join(save_dir, 'resnet_training_log.csv'))

final_history = final_model.fit(
    X_train_aug, y_train_aug_cat,
    validation_data=(X_val, y_val_cat),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    class_weight=class_weights,
    callbacks=[checkpoint_cb, reduce_lr, csv_logger],
    verbose=1
)

# ============================================================================
# FINAL TEST SET EVALUATION
# ============================================================================
print("\n" + "="*60)
print("TEST SET EVALUATION")
print("="*60)

# Predictions on test set
y_test_pred_probs = final_model.predict(X_test, batch_size=32, verbose=0)
y_test_pred = np.argmax(y_test_pred_probs, axis=1)

# Classification report
print("\nClassification Report - Test Set:")
print(classification_report(y_test, y_test_pred,
                            target_names=[label_to_class[i] for i in range(num_classes)]))

# PLOT 1: Training curves for final model
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(final_history.history['accuracy'], label='Train Accuracy', linewidth=2)
plt.plot(final_history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
plt.title('Model Accuracy - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(final_history.history['loss'], label='Train Loss', linewidth=2)
plt.plot(final_history.history['val_loss'], label='Val Loss', linewidth=2)
plt.title('Model Loss - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.suptitle('Final Model Training Curves', fontsize=16)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'resnet_final_training_curves.png'), dpi=300, bbox_inches='tight')
plt.show()

# PLOT 2: Confusion Matrix for test set
plt.figure(figsize=(10, 8))
cm = confusion_matrix(y_test, y_test_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                               display_labels=[label_to_class[i] for i in range(num_classes)])
disp.plot(cmap='Blues', xticks_rotation=45)
plt.title("Confusion Matrix - Test Set", fontsize=14, fontweight='bold')
plt.grid(False)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'resnet_test_confusion_matrix.png'), dpi=300, bbox_inches='tight')
plt.show()

# PLOT 3: Per-class performance bar chart
test_report = classification_report(y_test, y_test_pred, output_dict=True, zero_division=0)
class_metrics = []
for i in range(num_classes):
    if str(i) in test_report:
        class_metrics.append({
            'Class': label_to_class[i],
            'Precision': test_report[str(i)]['precision'],
            'Recall': test_report[str(i)]['recall'],
            'F1-Score': test_report[str(i)]['f1-score']
        })

metrics_df = pd.DataFrame(class_metrics)
fig, ax = plt.subplots(figsize=(12, 6))
x = np.arange(len(metrics_df))
width = 0.25

ax.bar(x - width, metrics_df['Precision'], width, label='Precision')
ax.bar(x, metrics_df['Recall'], width, label='Recall')
ax.bar(x + width, metrics_df['F1-Score'], width, label='F1-Score')

ax.set_xlabel('Class', fontsize=12)
ax.set_ylabel('Score', fontsize=12)
ax.set_title('Per-Class Performance Metrics - Test Set', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(metrics_df['Class'], rotation=45, ha='right')
ax.legend()
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'resnet_per_class_metrics.png'), dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# SAVE FINAL RESULTS
# ============================================================================
# Calculate misclassifications
misclassified_idx = np.where(y_test_pred != y_test)[0]

final_results = {
    'Model': 'MobileNetV2_Multiclass',
    'Num_Classes': num_classes,
    'Test_Accuracy': accuracy_score(y_test, y_test_pred),
    'Test_Macro_Precision': precision_score(y_test, y_test_pred, average='macro'),
    'Test_Macro_Recall': recall_score(y_test, y_test_pred, average='macro'),
    'Test_Macro_F1': f1_score(y_test, y_test_pred, average='macro'),
    'Test_Weighted_Precision': precision_score(y_test, y_test_pred, average='weighted'),
    'Test_Weighted_Recall': recall_score(y_test, y_test_pred, average='weighted'),
    'Test_Weighted_F1': f1_score(y_test, y_test_pred, average='weighted'),
    'CV_Accuracy_Mean': cv_df['Accuracy'].mean(),
    'CV_Accuracy_Std': cv_df['Accuracy'].std(),
    'Misclassifications': len(misclassified_idx)
}

pd.DataFrame([final_results]).to_csv(
    os.path.join(save_dir, 'resnet_final_results.csv'), index=False
)

print("\n" + "="*60)
print("FINAL RESULTS")
print("="*60)
for key, value in final_results.items():
    print(f"{key}: {value}")

print("\n✅ All results saved to:", save_dir)



# ============================================================================
# MISCLASSIFIED IMAGES VISUALIZATION
# ============================================================================
print("\n" + "="*60)
print("VISUALIZING MISCLASSIFIED IMAGES")
print("="*60)

# Find misclassified samples
misclassified_idx = np.where(y_test_pred != y_test)[0]
print(f"Number of misclassified images: {len(misclassified_idx)}")

if len(misclassified_idx) > 0:
    # Visualize up to 20 misclassified images
    num_to_show = min(20, len(misclassified_idx))

    # Create figure with subplots
    fig, axes = plt.subplots(4, 5, figsize=(20, 16))
    axes = axes.flatten()

    for i, idx in enumerate(misclassified_idx[:num_to_show]):
        img = X_test[idx]
        true_label = label_to_class[y_test[idx]]
        pred_label = label_to_class[y_test_pred[idx]]
        confidence = y_test_pred_probs[idx, y_test_pred[idx]]  # Confidence for predicted class

        axes[i].imshow(img)
        axes[i].set_title(f'True: {true_label}\nPred: {pred_label}\nConf: {confidence:.2%}',
                         fontsize=10, fontweight='bold')
        axes[i].axis('off')

    # Hide unused subplots
    for i in range(num_to_show, len(axes)):
        axes[i].axis('off')

    plt.suptitle('Misclassified Images on Test Set', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'resnet_misclassified_images.png'), dpi=300, bbox_inches='tight')
    plt.show()

    # Save detailed misclassification info
    misclass_info = []
    for i, idx in enumerate(misclassified_idx):
        true_class_idx = y_test[idx]
        pred_class_idx = y_test_pred[idx]

        info_dict = {
            'Sample_Index': int(idx),
            'True_Label': label_to_class[true_class_idx],
            'True_Label_ID': int(true_class_idx),
            'Predicted_Label': label_to_class[pred_class_idx],
            'Predicted_Label_ID': int(pred_class_idx),
            'Confidence': float(y_test_pred_probs[idx, pred_class_idx]),
            'True_Class_Probability': float(y_test_pred_probs[idx, true_class_idx])
        }

        # Add probabilities for all classes
        for class_idx in range(num_classes):
            info_dict[f'Prob_{label_to_class[class_idx]}'] = float(y_test_pred_probs[idx, class_idx])

        misclass_info.append(info_dict)

    misclass_df = pd.DataFrame(misclass_info)
    misclass_df.to_csv(os.path.join(save_dir, 'resnet_misclassifications.csv'), index=False)
    print(f"Saved misclassification details to: {os.path.join(save_dir, 'mobilenet_misclassifications.csv')}")

    # Print summary of misclassification patterns
    print("\nMisclassification Summary:")
    print("-" * 40)
    misclass_summary = misclass_df.groupby(['True_Label', 'Predicted_Label']).size().reset_index(name='Count')
    misclass_summary = misclass_summary.sort_values('Count', ascending=False)
    print(misclass_summary.to_string(index=False))

print("\n✅ All results saved to:", save_dir)


# ============================================================================
# SCORE-CAM IMPLEMENTATION FOR MULTICLASS CLASSIFICATION (ResNet50)
# ============================================================================
print("\n" + "="*60)
print("MULTICLASS SCORE-CAM IMPLEMENTATION & VISUALIZATION (ResNet50)")
print("="*60)

# Define Multiclass ScoreCAM class
class MulticlassScoreCAM:
    def __init__(self, model, layer_name=None):
        self.model = model
        self.layer_name = layer_name
        self.num_classes = model.output_shape[-1]  # Get number of classes from output layer

        # Find the last convolutional layer if layer_name is not specified
        if self.layer_name is None:
            # For ResNet50 models, look for the base model layers
            resnet_layer = None
            for layer in self.model.layers:
                if 'resnet' in layer.name.lower():
                    resnet_layer = layer
                    break

            if resnet_layer is not None:
                # Look for good layers in ResNet50
                for sublayer in reversed(resnet_layer.layers):
                    # Try to find the last conv block output
                    if ('conv5_block3' in sublayer.name and ('out' in sublayer.name or 'add' in sublayer.name)) or \
                       ('conv5_block3_3_conv' in sublayer.name) or \
                       ('conv4_block6' in sublayer.name and ('out' in sublayer.name or 'add' in sublayer.name)):
                        self.layer_name = sublayer.name
                        self.base_model = resnet_layer
                        break

                # If not found, try any conv layer in the last stages
                if self.layer_name is None:
                    for sublayer in reversed(resnet_layer.layers):
                        if 'conv' in sublayer.name.lower() and ('conv5' in sublayer.name or 'conv4' in sublayer.name):
                            if hasattr(sublayer, 'output_shape') and len(sublayer.output_shape) == 4:
                                self.layer_name = sublayer.name
                                self.base_model = resnet_layer
                                break
            else:
                # If no ResNet layer found, search in the main model
                for layer in reversed(self.model.layers):
                    if 'conv' in layer.name.lower() and hasattr(layer, 'output_shape') and len(layer.output_shape) == 4:
                        self.layer_name = layer.name
                        break

        if self.layer_name is None:
            # Manual fallback - use a known good layer name for ResNet50
            self.layer_name = 'conv5_block3_out'
            resnet_layer = None
            for layer in self.model.layers:
                if 'resnet' in layer.name.lower():
                    resnet_layer = layer
                    break
            self.base_model = resnet_layer

        # Create a model that outputs feature maps from the specified layer
        try:
            if hasattr(self, 'base_model') and self.base_model is not None:
                target_layer = self.base_model.get_layer(self.layer_name)
                self.feature_model = tf.keras.models.Model(
                    inputs=self.base_model.input,
                    outputs=target_layer.output
                )
            else:
                self.feature_model = tf.keras.models.Model(
                    inputs=self.model.input,
                    outputs=self.model.get_layer(self.layer_name).output
                )
        except Exception as e:
            # Try alternative layers for ResNet50
            alternative_layers = [
                'conv5_block3_out',
                'conv5_block3_add',
                'conv5_block3_3_conv',
                'conv5_block2_out',
                'conv4_block6_out',
                'conv5_block1_out'
            ]
            for alt_layer in alternative_layers:
                try:
                    if hasattr(self, 'base_model') and self.base_model is not None:
                        target_layer = self.base_model.get_layer(alt_layer)
                        self.feature_model = tf.keras.models.Model(
                            inputs=self.base_model.input,
                            outputs=target_layer.output
                        )
                        self.layer_name = alt_layer
                        break
                except:
                    continue

        print(f"Score-CAM using layer: {self.layer_name}")
        print(f"Number of classes detected: {self.num_classes}")

    def generate_cam(self, input_image, target_class=None):
        """
        Generate Score-CAM for a specific class.

        Args:
            input_image: Input image (H, W, 3) or (1, H, W, 3)
            target_class: Target class index (int). If None, uses predicted class.

        Returns:
            cam: Class Activation Map
            class_scores: All class probabilities
            target_class: The class used for CAM generation
        """
        if len(input_image.shape) == 3:
            input_image = np.expand_dims(input_image, axis=0)

        # Get feature maps
        feature_maps = self.feature_model.predict(input_image, verbose=0)

        # Get original prediction scores for all classes
        class_scores = self.model.predict(input_image, verbose=0)[0]

        # Determine target class if not specified
        if target_class is None:
            target_class = np.argmax(class_scores)

        # Initialize weights for each feature map
        weights = []

        # Sample every nth feature map to speed up computation
        n_features = feature_maps.shape[-1]
        step = max(1, n_features // 50)  # Use at most 50 feature maps

        for i in range(0, n_features, step):
            # Extract single feature map
            feature_map = feature_maps[0, :, :, i]

            # Resize feature map to input image size
            resized_feature_map = cv2.resize(feature_map, (input_image.shape[2], input_image.shape[1]))

            # Normalize feature map to [0, 1]
            if resized_feature_map.max() > resized_feature_map.min():
                normalized_feature_map = (resized_feature_map - resized_feature_map.min()) / \
                                       (resized_feature_map.max() - resized_feature_map.min())
            else:
                normalized_feature_map = np.zeros_like(resized_feature_map)

            # Create masked image
            masked_image = input_image[0] * np.expand_dims(normalized_feature_map, axis=-1)
            masked_image = np.expand_dims(masked_image, axis=0)

            # Get prediction score for masked image for target class
            try:
                masked_scores = self.model.predict(masked_image, verbose=0)[0]
                masked_score = masked_scores[target_class]  # Get score for target class
                weights.append(masked_score)
            except:
                weights.append(0.0)

        weights = np.array(weights)

        # Generate weighted combination of feature maps
        cam = np.zeros((feature_maps.shape[1], feature_maps.shape[2]), dtype=np.float32)

        for idx, i in enumerate(range(0, n_features, step)):
            cam += weights[idx] * feature_maps[0, :, :, i]

        # Apply ReLU and normalize CAM
        cam = np.maximum(cam, 0)
        if cam.max() > cam.min():
            cam = (cam - cam.min()) / (cam.max() - cam.min())

        return cam, class_scores, target_class

    def generate_cams_all_classes(self, input_image):
        """
        Generate Score-CAMs for all classes.

        Args:
            input_image: Input image (H, W, 3) or (1, H, W, 3)

        Returns:
            cams: List of CAMs for each class
            class_scores: All class probabilities
        """
        cams = []
        for class_idx in range(self.num_classes):
            cam, class_scores, _ = self.generate_cam(input_image, target_class=class_idx)
            cams.append(cam)

        return cams, class_scores


def overlay_heatmap_scorecam(img, heatmap, alpha=0.4, colormap=cv2.COLORMAP_JET):
    """
    Overlay heatmap on image.

    Args:
        img: Original image (H, W, 3) in range [0, 1]
        heatmap: Heatmap (H, W) in range [0, 1]
        alpha: Transparency of heatmap
        colormap: OpenCV colormap

    Returns:
        Overlayed image
    """
    # Convert heatmap to RGB
    heatmap_uint8 = np.uint8(255 * heatmap)
    heatmap_colored = cv2.applyColorMap(heatmap_uint8, colormap)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)
    heatmap_colored = heatmap_colored.astype(np.float32) / 255.0

    # Convert image to proper format
    img_display = img.copy()

    # Overlay
    overlayed = heatmap_colored * alpha + img_display * (1 - alpha)
    overlayed = np.clip(overlayed, 0, 1)

    return overlayed


# Initialize Score-CAM with the final model
try:
    score_cam = MulticlassScoreCAM(final_model)
    print("Multiclass Score-CAM initialized successfully!")
except Exception as e:
    print(f"Error initializing Score-CAM: {e}")
    score_cam = None

# Define class names (MODIFY THIS based on your dataset)
class_names = ['Class 0', 'Class 1', 'Class 2', 'Class 3']  # Example - update with your class names

# Select samples for Score-CAM visualization
samples_to_visualize = []

# Get correctly classified samples from each class (2 per class)
for class_idx in range(len(class_names)):
    correct_class = np.where((y_test == class_idx) & (y_test_pred == class_idx))[0]
    if len(correct_class) > 0:
        samples_to_visualize.extend(correct_class[:2])

# Add misclassified images
if len(misclassified_idx) > 0:
    samples_to_visualize.extend(misclassified_idx[:4])

# ============================================================================
# VISUALIZATION 1: SINGLE CAM PER IMAGE (PREDICTED CLASS)
# ============================================================================
print("\n" + "-"*60)
print("VISUALIZATION 1: Score-CAM for Predicted Class")
print("-"*60)

if score_cam is not None and len(samples_to_visualize) > 0:
    print(f"Generating Score-CAM for {len(samples_to_visualize)} samples...")

    num_samples = len(samples_to_visualize)
    fig, axes = plt.subplots(num_samples, 3, figsize=(15, 5*num_samples))
    if num_samples == 1:
        axes = axes.reshape(1, -1)

    for i, idx in enumerate(samples_to_visualize):
        img = X_test[idx]
        true_label = class_names[y_test[idx]]
        pred_label = class_names[y_test_pred[idx]]

        try:
            # Generate Score-CAM for predicted class
            cam, class_scores, target_class = score_cam.generate_cam(img)
            confidence = class_scores[target_class]

            # Resize CAM to match image size
            cam_resized = cv2.resize(cam, (SIZE, SIZE))

            # Create overlay
            overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)

        except Exception as e:
            print(f"Error generating Score-CAM for sample {idx}: {str(e)}")
            cam_resized = np.zeros((SIZE, SIZE))
            overlay = img
            confidence = 0.0

        # Plot original image
        axes[i, 0].imshow(img)
        axes[i, 0].set_title(f'Original\nTrue: {true_label}\nPred: {pred_label} ({confidence:.2%})',
                            fontsize=10, fontweight='bold')
        axes[i, 0].axis('off')

        # Plot heatmap
        im = axes[i, 1].imshow(cam_resized, cmap='jet')
        axes[i, 1].set_title(f'Score-CAM Heatmap\n(Class: {pred_label})',
                            fontsize=10, fontweight='bold')
        axes[i, 1].axis('off')
        plt.colorbar(im, ax=axes[i, 1], fraction=0.046, pad=0.04)

        # Plot overlay
        axes[i, 2].imshow(overlay)
        axes[i, 2].set_title('Overlay', fontsize=10, fontweight='bold')
        axes[i, 2].axis('off')

    plt.suptitle('Multiclass Score-CAM Visualizations (ResNet50)', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'resnet50_scorecam_multiclass.png'), dpi=300, bbox_inches='tight')
    plt.show()

    print("Score-CAM visualization complete!")
    print(f"Results saved to: {os.path.join(save_dir, 'resnet50_scorecam_multiclass.png')}")
else:
    print("Score-CAM visualization skipped")

# ============================================================================
# VISUALIZATION 2: ALL CLASSES CAM COMPARISON
# ============================================================================
print("\n" + "-"*60)
print("VISUALIZATION 2: Score-CAM for All Classes (Comparison)")
print("-"*60)

if score_cam is not None and len(samples_to_visualize) > 0:
    # Select a few samples for all-class visualization
    sample_indices = samples_to_visualize[:3]  # Visualize first 3 samples

    for sample_num, idx in enumerate(sample_indices):
        img = X_test[idx]
        true_label = class_names[y_test[idx]]
        pred_label = class_names[y_test_pred[idx]]

        print(f"Generating CAMs for all classes for sample {sample_num+1}/{len(sample_indices)}...")

        try:
            # Generate CAMs for all classes
            cams, class_scores = score_cam.generate_cams_all_classes(img)

            # Create figure with original + CAM for each class
            n_cols = len(class_names) + 1
            fig, axes = plt.subplots(1, n_cols, figsize=(5*n_cols, 5))

            # Plot original image
            axes[0].imshow(img)
            axes[0].set_title(f'Original\nTrue: {true_label}\nPred: {pred_label}',
                            fontsize=10, fontweight='bold')
            axes[0].axis('off')

            # Plot CAM for each class
            for class_idx in range(len(class_names)):
                cam = cams[class_idx]
                cam_resized = cv2.resize(cam, (SIZE, SIZE))
                overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)

                axes[class_idx + 1].imshow(overlay)
                axes[class_idx + 1].set_title(
                    f'{class_names[class_idx]}\nScore: {class_scores[class_idx]:.2%}',
                    fontsize=10,
                    fontweight='bold',
                    color='green' if class_idx == y_test_pred[idx] else 'black'
                )
                axes[class_idx + 1].axis('off')

            plt.suptitle(f'All-Class Score-CAM Comparison - Sample {sample_num+1}',
                        fontsize=14, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, f'resnet50_scorecam_allclasses_sample{sample_num+1}.png'),
                       dpi=300, bbox_inches='tight')
            plt.show()

        except Exception as e:
            print(f"Error generating all-class CAMs for sample {idx}: {str(e)}")

    print("All-class comparison visualizations complete!")
else:
    print("All-class visualization skipped")

print("\n" + "="*60)
print("ALL MULTICLASS SCORE-CAM PROCESSING COMPLETE!")
print("="*60)

"""Extended multiclass Score-CAM analysis for the image classifier, probing
confidence regimes, class confusions, and per-class behavior.

This cell:
1. Reuses the trained multiclass model, test predictions, and a previously
   defined Score-CAM implementation, verifies that all required variables are
   available, and then runs a series of post-hoc visual analyses without any
   retraining.
2. For each class, contrasts high- vs low-confidence correct predictions via
   Score-CAM overlays, visualizes class-confusion pairs (true vs predicted
   class) to see where attention shifts when the model confuses labels, and
   inspects uncertain cases where the top probability is low or the top two
   classes are close in score.
3. Builds per-class grids of representative correct predictions across
   confidence levels and a comprehensive grid mixing correct samples and
   misclassifications from all classes, saving all corresponding Score-CAM
   panels to disk for side-by-side qualitative comparison.
4. Prints summary statistics on overall accuracy, per-class accuracy, pairwise
   confusion counts, and the distribution of high-confidence vs uncertain
   predictions, providing a compact numerical overview to accompany the
   visual diagnostics.
"""

# ============================================================================
# ADDITIONAL SCORE-CAM VISUALIZATIONS - EXTENDED ANALYSIS (MULTICLASS)
# Run this cell separately after the main training code
# ============================================================================
print("\n" + "="*80)
print("EXTENDED SCORE-CAM ANALYSIS - MULTICLASS")
print("="*80)

# Check if required variables exist
try:
    _ = final_model, X_test, y_test, y_test_pred, y_test_pred_probs, X_val, y_val
    _ = label_to_class, num_classes
    print("All required variables found. Proceeding with analysis...")
except NameError as e:
    print(f"Error: Missing required variable - {e}")
    print("Please run the main training code first!")
    raise

# Initialize Score-CAM if not already done
if 'score_cam' not in locals() and 'score_cam' not in globals():
    print("\nInitializing Score-CAM...")
    try:
        score_cam = ScoreCAM(final_model)
        print("Score-CAM initialized successfully!")
    except Exception as e:
        print(f"Error initializing Score-CAM: {e}")
        score_cam = None

# ============================================================================
# VISUALIZATION 1: CONFIDENCE-BASED ANALYSIS (PER CLASS)
# ============================================================================
print("\n" + "-"*80)
print("1. HIGH VS LOW CONFIDENCE PREDICTIONS")
print("-"*80)

if score_cam is not None:
    try:
        selected_indices = []

        # For each class, get high and low confidence samples
        for class_idx in range(num_classes):
            # High confidence correct predictions for this class
            high_conf = np.where(
                (y_test_pred == class_idx) &
                (y_test == class_idx) &
                (y_test_pred_probs[:, class_idx] > 0.9)
            )[0]
            if len(high_conf) > 0:
                selected_indices.append(('high_correct', class_idx, high_conf[0]))

            # Low confidence correct predictions for this class
            low_conf = np.where(
                (y_test_pred == class_idx) &
                (y_test == class_idx) &
                (y_test_pred_probs[:, class_idx] < 0.7)
            )[0]
            if len(low_conf) > 0:
                selected_indices.append(('low_correct', class_idx, low_conf[0]))

        if len(selected_indices) > 0:
            n_samples = min(len(selected_indices), 12)
            selected_indices = selected_indices[:n_samples]

            n_cols = 4
            n_rows = (n_samples + n_cols - 1) // n_cols

            fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 5*n_rows))
            if n_rows == 1:
                axes = np.array([axes])
            axes = axes.ravel()

            for i, (conf_type, class_idx, idx) in enumerate(selected_indices):
                img = X_test[idx]

                try:
                    cam, cam_confidence, target_class = score_cam.generate_cam(img, target_class=class_idx)
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)
                except:
                    overlay = img

                axes[i].imshow(overlay)
                axes[i].axis('off')

                pred_prob = y_test_pred_probs[idx, class_idx]
                conf_label = "HIGH" if conf_type == 'high_correct' else "LOW"

                axes[i].set_title(
                    f"✓ {conf_label} Confidence\n"
                    f"Class: {label_to_class[class_idx]}\n"
                    f"Prob: {pred_prob:.3f}",
                    fontsize=9, fontweight='bold'
                )

            for i in range(len(selected_indices), len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: High vs Low Confidence Predictions", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'mobilenet_scorecam_confidence.png'), dpi=300, bbox_inches='tight')
            plt.show()
            print("Confidence analysis complete!")
        else:
            print("No samples found matching confidence criteria")

    except Exception as e:
        print(f"Error in confidence analysis: {e}")

# ============================================================================
# VISUALIZATION 2: CONFUSION PATTERNS
# ============================================================================
print("\n" + "-"*80)
print("2. CONFUSION PATTERNS BETWEEN CLASSES")
print("-"*80)

if score_cam is not None:
    try:
        # Find confused pairs
        confusion_samples = []

        for true_class in range(num_classes):
            for pred_class in range(num_classes):
                if true_class != pred_class:
                    confused = np.where((y_test == true_class) & (y_test_pred == pred_class))[0]
                    if len(confused) > 0:
                        # Take up to 2 samples of each confusion type
                        for idx in confused[:2]:
                            confusion_samples.append((true_class, pred_class, idx))

        if len(confusion_samples) > 0:
            n_samples = min(len(confusion_samples), 12)
            confusion_samples = confusion_samples[:n_samples]

            n_cols = 4
            n_rows = (n_samples + n_cols - 1) // n_cols

            fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 5*n_rows))
            if n_rows == 1:
                axes = np.array([axes])
            axes = axes.ravel()

            for i, (true_class, pred_class, idx) in enumerate(confusion_samples):
                img = X_test[idx]

                try:
                    # Generate CAM for the predicted class
                    cam, cam_confidence, target_class = score_cam.generate_cam(img, target_class=pred_class)
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)
                except:
                    overlay = img

                axes[i].imshow(overlay)
                axes[i].axis('off')

                pred_prob = y_test_pred_probs[idx, pred_class]
                true_prob = y_test_pred_probs[idx, true_class]

                axes[i].set_title(
                    f"✗ CONFUSED\n"
                    f"True: {label_to_class[true_class]} ({true_prob:.2f})\n"
                    f"Pred: {label_to_class[pred_class]} ({pred_prob:.2f})",
                    fontsize=9, fontweight='bold', color='red'
                )

            for i in range(len(confusion_samples), len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: Class Confusion Analysis", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'mobilenet_scorecam_confusion.png'), dpi=300, bbox_inches='tight')
            plt.show()
            print(f"Found {len(confusion_samples)} confusion cases")
        else:
            print("No confusion cases found - perfect classification!")

    except Exception as e:
        print(f"Error in confusion analysis: {e}")

# ============================================================================
# VISUALIZATION 3: BORDERLINE/UNCERTAIN PREDICTIONS
# ============================================================================
print("\n" + "-"*80)
print("3. UNCERTAIN PREDICTIONS")
print("-"*80)

if score_cam is not None:
    try:
        # Find samples where the top probability is not very high
        max_probs = np.max(y_test_pred_probs, axis=1)
        uncertain_indices = np.where(max_probs < 0.8)[0]

        # Also find samples where top 2 classes are close
        sorted_probs = np.sort(y_test_pred_probs, axis=1)
        prob_diff = sorted_probs[:, -1] - sorted_probs[:, -2]
        close_indices = np.where(prob_diff < 0.3)[0]

        # Combine both types of uncertainty
        borderline_indices = np.unique(np.concatenate([uncertain_indices, close_indices]))

        if len(borderline_indices) > 0:
            sample_indices = borderline_indices[:12]

            n_cols = 4
            n_rows = (len(sample_indices) + n_cols - 1) // n_cols

            fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 5*n_rows))
            if n_rows == 1:
                axes = np.array([axes])
            axes = axes.ravel()

            for i, idx in enumerate(sample_indices):
                img = X_test[idx]

                try:
                    cam, cam_confidence, target_class = score_cam.generate_cam(img, target_class=y_test_pred[idx])
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)
                except:
                    overlay = img

                axes[i].imshow(overlay)
                axes[i].axis('off')

                status = "✓" if y_test[idx] == y_test_pred[idx] else "✗"

                # Get top 2 predictions
                top2_idx = np.argsort(y_test_pred_probs[idx])[-2:][::-1]
                top1_class = label_to_class[top2_idx[0]]
                top1_prob = y_test_pred_probs[idx, top2_idx[0]]
                top2_class = label_to_class[top2_idx[1]]
                top2_prob = y_test_pred_probs[idx, top2_idx[1]]

                axes[i].set_title(
                    f"{status} True: {label_to_class[y_test[idx]]}\n"
                    f"1st: {top1_class} ({top1_prob:.2f})\n"
                    f"2nd: {top2_class} ({top2_prob:.2f})",
                    fontsize=9, fontweight='bold'
                )

            for i in range(len(sample_indices), len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: Uncertain Predictions", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'mobilenet_scorecam_borderline.png'), dpi=300, bbox_inches='tight')
            plt.show()
            print(f"Found {len(borderline_indices)} uncertain cases")
        else:
            print("No uncertain cases found")

    except Exception as e:
        print(f"Error in borderline analysis: {e}")

# ============================================================================
# VISUALIZATION 4: PER-CLASS CORRECT PREDICTIONS
# ============================================================================
print("\n" + "-"*80)
print("4. REPRESENTATIVE SAMPLES PER CLASS")
print("-"*80)

if score_cam is not None:
    try:
        fig, axes = plt.subplots(num_classes, 4, figsize=(20, 5*num_classes))
        if num_classes == 1:
            axes = np.array([axes])

        for class_idx in range(num_classes):
            # Get correct predictions for this class
            correct_class = np.where((y_test == class_idx) & (y_test_pred == class_idx))[0]

            if len(correct_class) >= 4:
                # Select 4 diverse samples (high conf, medium conf, etc)
                probs = y_test_pred_probs[correct_class, class_idx]
                sorted_idx = np.argsort(probs)[::-1]

                # Pick from different confidence levels
                selected = [
                    correct_class[sorted_idx[0]],  # Highest confidence
                    correct_class[sorted_idx[len(sorted_idx)//3]],
                    correct_class[sorted_idx[2*len(sorted_idx)//3]],
                    correct_class[sorted_idx[-1]]  # Lowest confidence
                ]
            else:
                selected = correct_class[:4]

            for col_idx, idx in enumerate(selected):
                img = X_test[idx]

                try:
                    cam, cam_confidence, target_class = score_cam.generate_cam(img, target_class=class_idx)
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)
                except:
                    overlay = img

                ax = axes[class_idx, col_idx] if num_classes > 1 else axes[col_idx]
                ax.imshow(overlay)
                ax.axis('off')

                pred_prob = y_test_pred_probs[idx, class_idx]
                ax.set_title(f"Prob: {pred_prob:.3f}", fontsize=9)

            # Hide unused subplots for this class
            for col_idx in range(len(selected), 4):
                ax = axes[class_idx, col_idx] if num_classes > 1 else axes[col_idx]
                ax.axis('off')

            # Add class label
            if num_classes > 1:
                axes[class_idx, 0].text(-0.1, 0.5, label_to_class[class_idx],
                                       transform=axes[class_idx, 0].transAxes,
                                       fontsize=14, fontweight='bold',
                                       rotation=90, va='center')

        plt.suptitle("Score-CAM: Representative Samples Per Class", fontsize=16, fontweight='bold')
        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, 'mobilenet_scorecam_per_class.png'), dpi=300, bbox_inches='tight')
        plt.show()
        print("Per-class analysis complete!")

    except Exception as e:
        print(f"Error in per-class analysis: {e}")

# ============================================================================
# VISUALIZATION 5: COMPREHENSIVE GRID
# ============================================================================
print("\n" + "-"*80)
print("5. COMPREHENSIVE DIVERSE SAMPLE GRID")
print("-"*80)

if score_cam is not None:
    try:
        diverse_samples = []

        # 2 correct samples per class
        for class_idx in range(num_classes):
            correct_class = np.where((y_test == class_idx) & (y_test_pred == class_idx))[0]
            if len(correct_class) >= 2:
                diverse_samples.extend([(class_idx, class_idx, correct_class[0], 'correct'),
                                       (class_idx, class_idx, correct_class[1], 'correct')])

        # Add misclassified samples
        for true_class in range(num_classes):
            for pred_class in range(num_classes):
                if true_class != pred_class:
                    confused = np.where((y_test == true_class) & (y_test_pred == pred_class))[0]
                    if len(confused) > 0:
                        diverse_samples.append((true_class, pred_class, confused[0], 'error'))

        if len(diverse_samples) > 0:
            n_samples = min(len(diverse_samples), 16)
            diverse_samples = diverse_samples[:n_samples]

            n_cols = 4
            n_rows = (n_samples + n_cols - 1) // n_cols

            fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 5*n_rows))
            if n_rows == 1:
                axes = np.array([axes])
            axes = axes.ravel()

            for i, (true_class, pred_class, idx, sample_type) in enumerate(diverse_samples):
                img = X_test[idx]

                try:
                    cam, cam_confidence, target_class = score_cam.generate_cam(img, target_class=pred_class)
                    cam_resized = cv2.resize(cam, (SIZE, SIZE))
                    overlay = overlay_heatmap_scorecam(img, cam_resized, alpha=0.4)
                except:
                    overlay = img

                axes[i].imshow(overlay)
                axes[i].axis('off')

                status = "✓" if sample_type == 'correct' else "✗"
                color = 'green' if sample_type == 'correct' else 'red'

                axes[i].set_title(
                    f"{status} True: {label_to_class[true_class]}\n"
                    f"Pred: {label_to_class[pred_class]}\n"
                    f"Conf: {y_test_pred_probs[idx, pred_class]:.3f}",
                    fontsize=9, color=color
                )

            for i in range(n_samples, len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: Comprehensive Sample Grid", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'mobilenet_scorecam_diverse.png'), dpi=300, bbox_inches='tight')
            plt.show()
            print("Comprehensive grid complete!")

    except Exception as e:
        print(f"Error in comprehensive grid: {e}")

# ============================================================================
# SUMMARY STATISTICS
# ============================================================================
print("\n" + "="*80)
print("SUMMARY STATISTICS")
print("="*80)

if score_cam is not None:
    try:
        print(f"\nTotal test samples: {len(X_test)}")
        print(f"Correct predictions: {np.sum(y_test == y_test_pred)}")
        print(f"Incorrect predictions: {np.sum(y_test != y_test_pred)}")

        print("\nPer-class statistics:")
        for class_idx in range(num_classes):
            class_mask = y_test == class_idx
            correct = np.sum((y_test == class_idx) & (y_test_pred == class_idx))
            total = np.sum(class_mask)
            print(f"  {label_to_class[class_idx]}: {correct}/{total} correct ({100*correct/total:.1f}%)")

        print("\nConfusion patterns:")
        for true_class in range(num_classes):
            for pred_class in range(num_classes):
                if true_class != pred_class:
                    confused = np.sum((y_test == true_class) & (y_test_pred == pred_class))
                    if confused > 0:
                        print(f"  {label_to_class[true_class]} → {label_to_class[pred_class]}: {confused} cases")

        max_probs = np.max(y_test_pred_probs, axis=1)
        uncertain = np.sum(max_probs < 0.8)
        high_conf = np.sum(max_probs > 0.9)

        print(f"\nConfidence distribution:")
        print(f"  High confidence (>0.9): {high_conf}")
        print(f"  Uncertain (<0.8): {uncertain}")

        print(f"\nAll Score-CAM visualizations saved to: {save_dir}")

    except Exception as e:
        print(f"Error generating summary: {e}")

print("\n" + "="*80)
print("EXTENDED SCORE-CAM ANALYSIS COMPLETE!")
print("="*80)