# -*- coding: utf-8 -*-
"""bnn_binary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUekM0LLYNzbyz9LEeoRQt6aZ7v0Htnk
"""

!pip install tf-keras-vis

"""End-to-end Bayesian CNN pipeline for frost vs non-frost image classification
with MC Dropout uncertainty and Score-CAM explanations.

Steps:
1. Set seeds and plotting style, mount Google Drive, and define project paths.
2. Load frost/non-frost images from Drive, resize to 512×512, normalize, and
   create stratified train/validation/test splits (saving the test split for reuse).
3. Perform data augmentation on the training set (rotations and flips) and compute
   class weights to handle imbalance.
4. Define a CNN with MC Dropout layers (Bayesian Neural Network-style) and
   a binary cross-entropy loss with label smoothing.
5. Phase 1: Run stratified K-fold cross-validation, plotting training curves and
   confusion matrices for each fold and saving metrics to CSV.
6. Phase 2: Train a final model on the full augmented training data with callbacks
   (ReduceLROnPlateau, ModelCheckpoint, CSVLogger).
7. Evaluate on the held-out test set using MC Dropout to obtain predictive
   mean and uncertainty, generate training curves, confusion matrix, and
   misclassified-image panels.
8. Perform uncertainty analysis (histogram, confidence-vs-uncertainty scatter),
   aggregate final metrics and uncertainty into CSV, and optionally compute
   Score-CAM heatmaps on selected test images for qualitative interpretation.
"""

import cv2
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (classification_report, confusion_matrix, ConfusionMatrixDisplay,
                             accuracy_score, precision_score, recall_score, f1_score)
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Input, Conv2D, MaxPooling2D, GlobalMaxPooling2D,
                                     Dense, BatchNormalization, Dropout)
from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, CSVLogger
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from sklearn.utils import class_weight
from google.colab import drive
import pickle

# ============================================================================
# SETUP & REPRODUCIBILITY
# ============================================================================
sns.set_style("darkgrid")
sns.set_palette("colorblind")

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)
os.environ["TF_DETERMINISTIC_OPS"] = "1"

# Mount Drive
drive.mount('/content/drive')

# Paths
image_directory = '/content/drive/My Drive/frost/frost_non_frost'
non_frost_images_path = os.path.join(image_directory, 'non_frost')
frost_images_path = os.path.join(image_directory, 'frost')
save_dir = '/content/drive/My Drive/frost/models_saved'
os.makedirs(save_dir, exist_ok=True)

# Constants
SIZE = 512
BATCH_SIZE = 25
EPOCHS = 20
AUGMENTATION_FACTOR = 4
N_FOLDS = 5

# ============================================================================
# DATA LOADING
# ============================================================================
print("Loading images...")
dataset = []
labels = []

# Load non-frost images (label 0)
for image_name in os.listdir(non_frost_images_path):
    if image_name.lower().endswith(('tif', 'png', 'jpg', 'jpeg')):
        image_path = os.path.join(non_frost_images_path, image_name)
        image = cv2.imread(image_path)
        if image is None:
            continue
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (SIZE, SIZE))
        dataset.append(image)
        labels.append(0)

# Load frost images (label 1)
for image_name in os.listdir(frost_images_path):
    if image_name.lower().endswith(('tif', 'png', 'jpg', 'jpeg')):
        image_path = os.path.join(frost_images_path, image_name)
        image = cv2.imread(image_path)
        if image is None:
            continue
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (SIZE, SIZE))
        dataset.append(image)
        labels.append(1)

# Normalize to [0, 1]
dataset = np.array(dataset, dtype=np.float32) / 255.0
labels = np.array(labels)

print(f"Total samples: {len(dataset)}")
print(f"Class distribution: {np.unique(labels, return_counts=True)}")

# ============================================================================
# DATA SPLITTING (CONSISTENT ACROSS ALL MODELS)
# ============================================================================
print("\nCreating train/val/test splits...")
X_train, X_temp, y_train, y_temp = train_test_split(
    dataset, labels, test_size=0.3, random_state=SEED, stratify=labels
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=SEED, stratify=y_temp
)

print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

# Save splits for consistency across models
np.save(os.path.join(save_dir, 'X_test.npy'), X_test)
np.save(os.path.join(save_dir, 'y_test.npy'), y_test)

# ============================================================================
# DATA AUGMENTATION
# ============================================================================
print("\nAugmenting training data...")
train_datagen = ImageDataGenerator(
    rotation_range=30,
    horizontal_flip=True,
    fill_mode='reflect'
)

def augment_data(X, y, factor=AUGMENTATION_FACTOR):
    aug_images = []
    aug_labels = []
    for i in range(len(X)):
        image = np.expand_dims(X[i], axis=0)
        label = y[i]
        aug_iter = train_datagen.flow(image, batch_size=1)
        for _ in range(factor):
            aug_images.append(next(aug_iter)[0])
            aug_labels.append(label)

    X_aug = np.concatenate([X, np.array(aug_images)], axis=0).astype(np.float32)
    y_aug = np.concatenate([y, np.array(aug_labels)], axis=0).astype(int)
    return X_aug, y_aug

X_train_aug, y_train_aug = augment_data(X_train, y_train)
print(f"Augmented training data: {X_train_aug.shape}")

# Class weights
class_weights = class_weight.compute_class_weight(
    'balanced',
    classes=np.unique(y_train_aug),
    y=y_train_aug
)
class_weights = dict(enumerate(class_weights))
print(f"Class weights: {class_weights}")

# ============================================================================
# MC DROPOUT LAYER
# ============================================================================
class MCDropout(Dropout):
    def call(self, inputs, training=None):
        return super().call(inputs, training=True)

# ============================================================================
# BNN MODEL DEFINITION
# ============================================================================
def create_bnn_model(input_shape=(SIZE, SIZE, 3)):
    inputs = Input(shape=input_shape)

    x = Conv2D(16, (3, 3), activation='relu')(inputs)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = Conv2D(32, (3, 3), activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = Conv2D(64, (3, 3), activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = Conv2D(100, (3, 3), activation='relu', name='last_conv')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = GlobalMaxPooling2D()(x)

    x = Dense(100, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = BatchNormalization()(x)
    x = MCDropout(0.6)(x)

    x = Dense(50, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = BatchNormalization()(x)
    x = MCDropout(0.5)(x)

    outputs = Dense(1, activation='sigmoid', kernel_regularizer=l2(0.001))(x)

    model = Model(inputs=inputs, outputs=outputs)
    model.compile(
        optimizer=Adam(learning_rate=0.0002),
        loss=tf.keras.losses.BinaryCrossentropy(label_smoothing=0.15),
        metrics=['accuracy']
    )
    return model

# ============================================================================
# MC DROPOUT PREDICTION
# ============================================================================
def mc_prediction(model, X, T=20):
    predictions = np.array([model(X, training=True).numpy().flatten() for _ in range(T)])
    mean_pred = predictions.mean(axis=0)
    std_pred = predictions.std(axis=0)
    return mean_pred, std_pred

# ============================================================================
# PHASE 1: CROSS-VALIDATION
# ============================================================================
print("\n" + "="*60)
print("PHASE 1: CROSS-VALIDATION")
print("="*60)

skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
cv_results = []

for fold_idx, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train), start=1):
    print(f"\n--- Fold {fold_idx}/{N_FOLDS} ---")

    # Split fold data
    X_fold_train = X_train[train_idx]
    y_fold_train = y_train[train_idx]
    X_fold_val = X_train[val_idx]
    y_fold_val = y_train[val_idx]

    # Augment fold training data
    X_fold_aug, y_fold_aug = augment_data(X_fold_train, y_fold_train)

    # Fold class weights
    fold_cw = class_weight.compute_class_weight(
        'balanced', classes=np.unique(y_fold_aug), y=y_fold_aug
    )
    fold_cw = dict(enumerate(fold_cw))

    # Create and train model
    model = create_bnn_model()
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-7, verbose=0, min_delta=0.0001)

    history = model.fit(
        X_fold_aug, y_fold_aug,
        validation_data=(X_fold_val, y_fold_val),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        shuffle=True,
        class_weight=fold_cw,
        callbacks=[reduce_lr],
        verbose=1
    )

    # Get predictions FIRST
    y_pred_probs = model.predict(X_fold_val, batch_size=32, verbose=0)
    y_pred = (y_pred_probs > 0.5).astype(int).flatten()

    # Calculate metrics
    report = classification_report(y_fold_val, y_pred, output_dict=True, zero_division=0)

    # Print classification report
    print(f"\nClassification Report - Fold {fold_idx}:")
    print(classification_report(y_fold_val, y_pred, target_names=['Non-Frost', 'Frost'], zero_division=0))

    # PLOT 1: Training curves
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy', linewidth=2)
    plt.plot(history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
    plt.title(f'Accuracy - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss', linewidth=2)
    plt.plot(history.history['val_loss'], label='Val Loss', linewidth=2)
    plt.title(f'Loss - Fold {fold_idx}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    plt.suptitle(f'Training Curves - Fold {fold_idx}/{N_FOLDS}', fontsize=16)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'bnn_fold_{fold_idx}_curves.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # PLOT 2: Confusion matrix (NOW y_pred exists!)
    plt.figure(figsize=(8, 6))
    cm = confusion_matrix(y_fold_val, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Non-Frost', 'Frost'])
    disp.plot(cmap='Blues')
    plt.title(f'Confusion Matrix - Fold {fold_idx}/{N_FOLDS}', fontsize=14, fontweight='bold')
    plt.grid(False)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f'bnn_fold_{fold_idx}_confusion.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # Save fold results
    fold_result = {
        'Fold': fold_idx,
        'Accuracy': report['accuracy'],
        'Precision_Frost': report.get('1', {}).get('precision', 0),
        'Recall_Frost': report.get('1', {}).get('recall', 0),
        'F1_Frost': report.get('1', {}).get('f1-score', 0),
        'Precision_Non_Frost': report.get('0', {}).get('precision', 0),
        'Recall_Non_Frost': report.get('0', {}).get('recall', 0),
        'F1_Non_Frost': report.get('0', {}).get('f1-score', 0),
        'Loss': history.history['val_loss'][-1],
        'Mean_Uncertainty': 0.0  # No uncertainty in CV
    }
    cv_results.append(fold_result)

    print(f"Accuracy: {fold_result['Accuracy']:.4f}, F1 (Frost): {fold_result['F1_Frost']:.4f}")

    # Clear memory
    del model, history, y_pred_probs, y_pred
    tf.keras.backend.clear_session()

# Save CV results
cv_df = pd.DataFrame(cv_results)
cv_df.to_csv(os.path.join(save_dir, 'bnn_cv_results.csv'), index=False)

print("\n" + "="*60)
print("CROSS-VALIDATION SUMMARY")
print("="*60)
print(cv_df.describe())

# ============================================================================
# PHASE 2: FINAL MODEL TRAINING (SINGLE RUN WITH FULL ANALYSIS)
# ============================================================================
print("\n" + "="*60)
print("PHASE 2: FINAL MODEL TRAINING")
print("="*60)

# Train final model on full augmented training data
final_model = create_bnn_model()

checkpoint_cb = ModelCheckpoint(
    filepath=os.path.join(save_dir, 'bnn_best_model.h5'),
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-6, verbose=1)
csv_logger = CSVLogger(os.path.join(save_dir, 'bnn_training_log.csv'))

final_history = final_model.fit(
    X_train_aug, y_train_aug,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    class_weight=class_weights,
    callbacks=[checkpoint_cb, reduce_lr, csv_logger],
    verbose=1
)

# ============================================================================
# FINAL TEST SET EVALUATION
# ============================================================================
print("\n" + "="*60)
print("TEST SET EVALUATION")
print("="*60)

# MC Dropout predictions on test set
mean_test_preds, std_test_preds = mc_prediction(final_model, X_test, T=20)
y_test_pred = (mean_test_preds > 0.5).astype(int)

# Classification report
print("\nClassification Report - Test Set:")
print(classification_report(y_test, y_test_pred, target_names=['Non-Frost', 'Frost']))

# PLOT 1: Training curves for final model
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(final_history.history['accuracy'], label='Train Accuracy', linewidth=2)
plt.plot(final_history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
plt.title('Model Accuracy - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(final_history.history['loss'], label='Train Loss', linewidth=2)
plt.plot(final_history.history['val_loss'], label='Val Loss', linewidth=2)
plt.title('Model Loss - Final Model', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.suptitle('Final Model Training Curves', fontsize=16)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'bnn_final_training_curves.png'), dpi=300, bbox_inches='tight')
plt.show()

# PLOT 2: Confusion Matrix for test set
plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_test_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Non-Frost', 'Frost'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix - Test Set", fontsize=14, fontweight='bold')
plt.grid(False)
plt.tight_layout()
plt.savefig(os.path.join(save_dir, 'bnn_test_confusion_matrix.png'), dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# UNCERTAINTY ANALYSIS
# ============================================================================
print("\n" + "="*60)
print("UNCERTAINTY ANALYSIS")
print("="*60)

# Uncertainty histogram
plt.figure(figsize=(8, 6))
plt.hist(std_test_preds, bins=50, color='mediumslateblue', edgecolor='black')
plt.title('Prediction Uncertainty (MC Dropout Std Dev)')
plt.xlabel('Standard Deviation')
plt.ylabel('Frequency')
plt.grid(True)
plt.savefig(os.path.join(save_dir, 'bnn_uncertainty_hist.png'), dpi=300, bbox_inches='tight')
plt.show()

# Confidence vs Uncertainty scatter
plt.figure(figsize=(8, 6))
plt.scatter(mean_test_preds, std_test_preds, alpha=0.6, c=y_test, cmap='coolwarm', edgecolor='k')
plt.colorbar(label='True Class')
plt.title("MC Dropout: Confidence vs Uncertainty")
plt.xlabel("Mean Predicted Probability")
plt.ylabel("Standard Deviation (Uncertainty)")
plt.grid(True)
plt.savefig(os.path.join(save_dir, 'bnn_confidence_uncertainty.png'), dpi=300, bbox_inches='tight')
plt.show()

# Misclassified images
misclassified_idx = np.where(y_test_pred != y_test)[0]
print(f"\nTotal misclassified: {len(misclassified_idx)}")

if len(misclassified_idx) > 0:
    n_samples = min(12, len(misclassified_idx))
    plt.figure(figsize=(16, 10))
    class_names = ['Non-Frost', 'Frost']

    for i, idx in enumerate(misclassified_idx[:n_samples]):
        plt.subplot(3, 4, i + 1)
        img = X_test[idx]
        plt.imshow(np.clip(img, 0, 1))
        plt.axis('off')
        plt.title(
            f"True: {class_names[y_test[idx]]}\n"
            f"Pred: {class_names[y_test_pred[idx]]}\n"
            f"Prob: {mean_test_preds[idx]:.2f}\n"
            f"Unc: {std_test_preds[idx]:.2f}"
        )

    plt.suptitle("Misclassified Test Images", fontsize=18)
    plt.tight_layout(rect=(0, 0, 1, 0.94))
    plt.savefig(os.path.join(save_dir, 'bnn_misclassified.png'), dpi=300, bbox_inches='tight')
    plt.show()

# ============================================================================
# SAVE FINAL RESULTS
# ============================================================================
final_results = {
    'Model': 'BNN',
    'Test_Accuracy': accuracy_score(y_test, y_test_pred),
    'Test_Precision': precision_score(y_test, y_test_pred),
    'Test_Recall': recall_score(y_test, y_test_pred),
    'Test_F1': f1_score(y_test, y_test_pred),
    'CV_Accuracy_Mean': cv_df['Accuracy'].mean(),
    'CV_Accuracy_Std': cv_df['Accuracy'].std(),
    'Mean_Uncertainty': np.mean(std_test_preds),
    'Misclassifications': len(misclassified_idx)
}

pd.DataFrame([final_results]).to_csv(
    os.path.join(save_dir, 'bnn_final_results.csv'), index=False
)

print("\n" + "="*60)
print("FINAL RESULTS")
print("="*60)
for key, value in final_results.items():
    print(f"{key}: {value}")

print("\n✅ All results saved to:", save_dir)



# ============================================================================
# SCORE-CAM VISUALIZATION (Optional Analysis)
# ============================================================================
RUN_SCORECAM = True  # Set to False to skip

if RUN_SCORECAM:
    print("\n" + "="*60)
    print("SCORE-CAM VISUALIZATION")
    print("="*60)

    try:
        from tf_keras_vis.scorecam import ScoreCAM
        from tf_keras_vis.utils.model_modifiers import ReplaceToLinear

        # Load best model
        print("Loading best model for Score-CAM...")
        best_model = tf.keras.models.load_model(
            os.path.join(save_dir, 'bnn_best_model.h5'),
            custom_objects={'MCDropout': MCDropout}
        )

        # IMPORTANT: Use the model in inference mode (training=False)
        # This turns OFF MC Dropout for consistent Score-CAM heatmaps
        def score_function(output):
            return output[:, 0]

        # Create Score-CAM object with model modifier
        def model_modifier(m):
            # Replace sigmoid with linear for better gradients
            m.layers[-1].activation = tf.keras.activations.linear
            return m

        scorecam = ScoreCAM(best_model, model_modifier=model_modifier)

        # Select diverse samples to visualize
        correct_idx = np.where(y_test_pred == y_test)[0]
        uncertain_idx = np.argsort(std_test_preds)[-10:]  # Top 10 most uncertain

        # Get sample indices: 3 correct, 3 misclassified, 3 uncertain
        sample_indices = []
        if len(correct_idx) >= 3:
            sample_indices.extend(correct_idx[:3])
        if len(misclassified_idx) >= 3:
            sample_indices.extend(misclassified_idx[:3])
        if len(uncertain_idx) >= 3:
            sample_indices.extend(uncertain_idx[:3])

        sample_indices = np.array(sample_indices[:9])  # Max 9 samples

        if len(sample_indices) > 0:
            print(f"Generating Score-CAM for {len(sample_indices)} samples...")

            # Generate Score-CAM - this automatically uses training=False
            X_samples = X_test[sample_indices]
            cam = scorecam(
                score_function,
                X_samples,
                penultimate_layer='last_conv'  # Named layer in model
            )

            # Visualize
            class_names = ['Non-Frost', 'Frost']
            n_rows = (len(sample_indices) + 2) // 3
            fig, axes = plt.subplots(n_rows, 3, figsize=(15, 5*n_rows))
            if n_rows > 1:
                axes = axes.ravel()
            elif n_rows == 1:
                axes = axes if isinstance(axes, np.ndarray) else np.array(axes)

            for i, idx in enumerate(sample_indices):
                ax = axes[i]

                # Original image
                img = X_test[idx]

                # Overlay CAM
                heatmap = cam[i]
                heatmap = np.uint8(255 * heatmap)
                heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
                heatmap = cv2.resize(heatmap, (SIZE, SIZE))

                # Superimpose
                superimposed = cv2.addWeighted(
                    (img * 255).astype(np.uint8), 0.6,
                    heatmap, 0.4, 0
                )

                ax.imshow(superimposed)
                ax.axis('off')

                # Title with prediction info
                true_label = class_names[y_test[idx]]
                pred_label = class_names[y_test_pred[idx]]
                prob = mean_test_preds[idx]
                unc = std_test_preds[idx]

                status = "✓" if y_test[idx] == y_test_pred[idx] else "✗"
                ax.set_title(
                    f"{status} True: {true_label} | Pred: {pred_label}\n"
                    f"Confidence: {prob:.2f} | Uncertainty: {unc:.2f}",
                    fontsize=10
                )

            # Hide unused subplots
            for i in range(len(sample_indices), len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM Visualizations - BNN Model", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'bnn_scorecam.png'), dpi=300, bbox_inches='tight')
            plt.show()

            print(f"✓ Score-CAM visualizations saved to: {os.path.join(save_dir, 'bnn_scorecam.png')}")
        else:
            print("⚠ Not enough samples for Score-CAM visualization")

    except ImportError:
        print("⚠ tf-keras-vis not installed. Run: pip install tf-keras-vis")
    except Exception as e:
        print(f"⚠ Score-CAM failed: {str(e)}")
        import traceback
        print(traceback.format_exc())
        print("Continuing without Score-CAM visualization...")
else:
    print("\n⏭ Skipping Score-CAM (set RUN_SCORECAM=True to enable)")

print("\n" + "="*60)
print("✅ ANALYSIS COMPLETE")
print("="*60)

"""Additional Score-CAM visualizations for qualitative model interpretation.

This cell:
1. Reuses the previously defined ScoreCAM object, score function, and trained
   BNN to generate supplementary heatmaps.
2. Produces Score-CAM overlays for:
   (a) randomly sampled test images (showing confidence and MC-dropout
       uncertainty alongside class-specific attention),
   (b) selected validation images (both correctly classified and
       misclassified), and
   (c) correctly classified Frost and Non-Frost test samples to compare
       class-specific focus patterns.
3. Saves all panels (random test, validation subset, class-specific examples)
   to disk, enabling detailed visual inspection of what image regions drive
   the model’s decisions across datasets.
"""

# ============================================================================
# ADDITIONAL SCORE-CAM VISUALIZATIONS
# ============================================================================
print("\n" + "="*60)
print("ADDITIONAL SCORE-CAM ANALYSIS")
print("="*60)

if RUN_SCORECAM:
    try:
        # We already have the ScoreCAM object from previous cell
        print("Generating additional Score-CAM visualizations...")

        # Option 1: Show more test samples (random selection)
        print("\n--- Random Test Samples ---")
        np.random.seed(42)  # For reproducible selection
        random_test_indices = np.random.choice(len(X_test), size=6, replace=False)

        X_random = X_test[random_test_indices]
        cam_random = scorecam(score_function, X_random, penultimate_layer='last_conv')

        fig, axes = plt.subplots(2, 3, figsize=(15, 10))
        axes = axes.ravel()

        for i, idx in enumerate(random_test_indices):
            ax = axes[i]

            # Original image
            img = X_test[idx]

            # Overlay CAM
            heatmap = cam_random[i]
            heatmap = np.uint8(255 * heatmap)
            heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
            heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
            heatmap = cv2.resize(heatmap, (SIZE, SIZE))

            # Superimpose
            superimposed = cv2.addWeighted(
                (img * 255).astype(np.uint8), 0.6,
                heatmap, 0.4, 0
            )

            ax.imshow(superimposed)
            ax.axis('off')

            # Get prediction for this sample
            pred_prob = mean_test_preds[idx]
            pred_class = y_test_pred[idx]
            true_class = y_test[idx]
            uncertainty = std_test_preds[idx]

            true_label = class_names[true_class]
            pred_label = class_names[pred_class]
            status = "✓" if true_class == pred_class else "✗"

            ax.set_title(
                f"{status} True: {true_label} | Pred: {pred_label}\n"
                f"Conf: {pred_prob:.2f} | Unc: {uncertainty:.2f}",
                fontsize=10
            )

        plt.suptitle("Score-CAM: Random Test Samples", fontsize=16, fontweight='bold')
        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, 'bnn_scorecam_random.png'), dpi=300, bbox_inches='tight')
        plt.show()

        # Option 2: Show validation samples (need to get validation predictions first)
        print("\n--- Validation Samples ---")

        # Get validation predictions
        val_pred_probs = final_model.predict(X_val, batch_size=32, verbose=0)
        val_pred = (val_pred_probs > 0.5).astype(int).flatten()

        # Select interesting validation samples
        val_correct = np.where(val_pred == y_val)[0]
        val_misclassified = np.where(val_pred != y_val)[0]

        val_sample_indices = []
        if len(val_correct) >= 3:
            val_sample_indices.extend(val_correct[:3])
        if len(val_misclassified) >= 3:
            val_sample_indices.extend(val_misclassified[:3])

        if len(val_sample_indices) > 0:
            val_sample_indices = np.array(val_sample_indices[:6])  # Max 6 samples

            X_val_samples = X_val[val_sample_indices]
            cam_val = scorecam(score_function, X_val_samples, penultimate_layer='last_conv')

            n_val_samples = len(val_sample_indices)
            n_rows_val = (n_val_samples + 2) // 3

            fig, axes = plt.subplots(n_rows_val, 3, figsize=(15, 5*n_rows_val))
            if n_rows_val == 1:
                axes = axes if isinstance(axes, np.ndarray) else np.array([axes])
            else:
                axes = axes.ravel()

            for i, idx in enumerate(val_sample_indices):
                ax = axes[i]

                # Original image
                img = X_val[idx]

                # Overlay CAM
                heatmap = cam_val[i]
                heatmap = np.uint8(255 * heatmap)
                heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
                heatmap = cv2.resize(heatmap, (SIZE, SIZE))

                # Superimpose
                superimposed = cv2.addWeighted(
                    (img * 255).astype(np.uint8), 0.6,
                    heatmap, 0.4, 0
                )

                ax.imshow(superimposed)
                ax.axis('off')

                # Validation predictions
                true_label = class_names[y_val[idx]]
                pred_label = class_names[val_pred[idx]]
                pred_prob = val_pred_probs[idx][0]
                status = "✓" if y_val[idx] == val_pred[idx] else "✗"

                ax.set_title(
                    f"{status} True: {true_label} | Pred: {pred_label}\n"
                    f"Confidence: {pred_prob:.2f}",
                    fontsize=10
                )

            # Hide unused subplots
            for i in range(len(val_sample_indices), len(axes)):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: Validation Samples", fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'bnn_scorecam_validation.png'), dpi=300, bbox_inches='tight')
            plt.show()
        else:
            print("No validation samples available for Score-CAM")

        # Option 3: Compare Frost vs Non-Frost focus
        print("\n--- Class-Specific Analysis ---")

        # Get samples by class
        frost_indices = np.where(y_test == 1)[0]
        non_frost_indices = np.where(y_test == 0)[0]

        # Select 3 of each class (correctly classified)
        frost_correct = [idx for idx in frost_indices if y_test_pred[idx] == 1][:3]
        non_frost_correct = [idx for idx in non_frost_indices if y_test_pred[idx] == 0][:3]

        class_indices = frost_correct + non_frost_correct

        if len(class_indices) >= 4:  # At least 2 of each class
            X_class_samples = X_test[class_indices]
            cam_class = scorecam(score_function, X_class_samples, penultimate_layer='last_conv')

            fig, axes = plt.subplots(2, 3, figsize=(15, 10))
            axes = axes.ravel()

            for i, idx in enumerate(class_indices):
                if i >= 6:  # Max 6 samples
                    break

                ax = axes[i]

                # Original image
                img = X_test[idx]

                # Overlay CAM
                heatmap = cam_class[i]
                heatmap = np.uint8(255 * heatmap)
                heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
                heatmap = cv2.resize(heatmap, (SIZE, SIZE))

                # Superimpose
                superimposed = cv2.addWeighted(
                    (img * 255).astype(np.uint8), 0.6,
                    heatmap, 0.4, 0
                )

                ax.imshow(superimposed)
                ax.axis('off')

                true_label = class_names[y_test[idx]]
                pred_prob = mean_test_preds[idx]
                uncertainty = std_test_preds[idx]

                ax.set_title(
                    f"✓ {true_label}\n"
                    f"Conf: {pred_prob:.2f} | Unc: {uncertainty:.2f}",
                    fontsize=11
                )

            # Hide unused subplots
            for i in range(len(class_indices), 6):
                axes[i].axis('off')

            plt.suptitle("Score-CAM: Class-Specific Attention (Top: Frost, Bottom: Non-Frost)",
                        fontsize=16, fontweight='bold')
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, 'bnn_scorecam_classes.png'), dpi=300, bbox_inches='tight')
            plt.show()

        print("✓ Additional Score-CAM visualizations complete!")

    except Exception as e:
        print(f"⚠ Additional Score-CAM failed: {str(e)}")
        import traceback
        print(traceback.format_exc())

else:
    print("⏭ Skipping additional Score-CAM (RUN_SCORECAM is False)")
